/**
 * OrbPro Plugin SDK - Propagator Plugin Header
 *
 * Defines the binary data structures and function signatures for
 * propagator plugins that compute orbital state vectors from TLE,
 * Keplerian elements, or other orbital data.
 *
 * Binary format: 64-byte StateVector, 8-byte aligned
 *
 * @file orbpro_propagator.h
 *
 * =========================================================================
 * NORMATIVE — UNITS. READ THIS BEFORE WRITING A SINGLE BYTE.
 * =========================================================================
 *
 *   OrbProStateVector.position IS IN METERS.
 *   OrbProStateVector.velocity IS IN METERS PER SECOND.
 *
 * There is no km variant, no per-plugin unit flag, and no negotiation. A
 * plugin that writes kilometres into this struct is off by 1000x and its
 * satellites render INSIDE the Earth. There is no runtime check that can
 * catch it for you: 6778 and 6778000 are both finite doubles.
 *
 * This block is normative because the file previously contradicted itself —
 * the struct field comments said km while the layout block three lines below
 * said METERS. The binding truth is what the shipped runtimes actually do,
 * and both of them emit meters:
 *
 *   - packages/orbpro-integration/propagator.sgp4/index.js
 *       "Output: ECEF positions in meters" — reads position[] straight out
 *       of this struct with NO scaling.
 *   - packages/orbpro-integration/propagator.hpop/index.js
 *       "Output: ECEF positions in meters (always — no JS-side unit
 *       normalization)".
 *
 * and the engine writes plugin output directly into Cesium Cartesian3, whose
 * unit is metres. km was never true anywhere on this seam.
 *
 * The ONE place km survives is OrbProOrbitalElements.semi_major_axis, an
 * INPUT struct that is not this state vector. It is labelled km there and
 * stays km; do not "unify" it silently.
 *
 * Ruling: graph/findings/official-harness-shapes.md §4.1 / §8.1
 * Task:   graph/tasks/harness-w0-immediate-fixes.md (W0.1)
 * =========================================================================
 *
 * @example
 * #include "orbpro_plugin.h"
 * #include "orbpro_propagator.h"
 *
 * static OrbProStateVector state;
 *
 * ORBPRO_EXPORT int32_t plugin_init(const uint8_t* data, size_t len) {
 *     // Parse TLE or orbital elements from data buffer
 *     return ORBPRO_OK;
 * }
 *
 * ORBPRO_EXPORT int32_t plugin_propagate(
 *     double julian_date, uint32_t entity_index, OrbProStateVector* out
 * ) {
 *     // Compute position/velocity at julian_date.
 *     // METERS and METERS/SECOND — see the NORMATIVE UNITS block above.
 *     out->epoch = julian_date;
 *     out->position[0] = x_m;
 *     out->position[1] = y_m;
 *     out->position[2] = z_m;
 *     out->velocity[0] = vx_m_s;
 *     out->velocity[1] = vy_m_s;
 *     out->velocity[2] = vz_m_s;
 *     out->reference_frame = ORBPRO_FRAME_TEME;
 *     out->flags = ORBPRO_STATE_VALID;
 *     return 0;
 * }
 */

#ifndef ORBPRO_PROPAGATOR_H
#define ORBPRO_PROPAGATOR_H

#include "orbpro_plugin.h"

/* memset() for orbpro_state_init(); offsetof() for the layout static_asserts. */
#include <string.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================= */
/* THE ABI ITSELF — GENERATED, NOT DECLARED HERE                             */
/* ========================================================================= */

/*
 * Every ABI struct, enum, size lock, offset lock and writer helper below this
 * line comes from ONE source of truth:
 *
 *     space-data-module-sdk/schemas/orbpro/Propagator.fbs
 *
 * and is generated by that package's `scripts/generate-propagator-abi.mjs`.
 * The committed copy here is verified byte-for-byte against the pinned SDK by
 * `sdk/tests/PropagatorAbiSpec.js`.
 *
 * WHY THIS FILE NO LONGER DECLARES THE STRUCTS
 * --------------------------------------------
 * It used to, and so did four other places: the SDK IDL, the sgp4 module's
 * schema copy, the sgp4 module's verbatim header copy, and poly-coverage's
 * retyped struct. Five hand-maintained mirrors of one binary contract. They
 * drifted exactly as you would expect — this very file said the position
 * field was in kilometres in its struct comments and METERS in its layout
 * block three lines below, a 1000x error a plugin author could compile
 * against for months. Worse, the directory the committed bindings were
 * supposedly generated from (`sdk/schemas/`) never existed in this
 * repository's history, so nothing could be regenerated and no difference
 * could be detected.
 *
 * What remains in THIS file is the normative prose that a generator has no
 * business emitting, plus the compatibility aliases below.
 *
 * Contract document: space-data-module-sdk/docs/propagator-abi.md
 * Ruling: graph/findings/official-harness-shapes.md §3 / §7 SHIP-1
 * Task:   graph/tasks/harness-w1-propagator-abi-and-reference.md (W1.1)
 */
#include "generated/orbpro_propagator_abi.h"


/* ========================================================================= */
/* Required Exported Functions                                               */
/* ========================================================================= */

/**
 * Initialize the propagator.
 *
 * Called by PropagatorPlugin.initFromTLE() or initFromElements().
 * The data buffer contains either UTF-8 TLE text or binary orbital elements.
 *
 * @param data   Pointer to initialization data (TLE string or elements array)
 * @param len    Length of data in bytes
 * @return       Number of entities initialized (>0) or negative error code
 *
 * REQUIRED: At least plugin_init must be exported.
 */
/* ORBPRO_EXPORT int32_t plugin_init(const uint8_t* data, size_t len); */

/**
 * Propagate a single entity to a given Julian date.
 *
 * @param julian_date   Target time as Julian date (float64)
 * @param entity_index  Index of the entity to propagate (0-based)
 * @param out           Pointer to output OrbProStateVector (64 bytes)
 * @return              0 on success, negative error code on failure
 *
 * REQUIRED: At least one of plugin_propagate or plugin_propagate_batch.
 */
/* ORBPRO_EXPORT int32_t plugin_propagate(
       double julian_date, uint32_t entity_index, OrbProStateVector* out); */

/* ========================================================================= */
/* Optional Exported Functions                                               */
/* ========================================================================= */

/**
 * Initialize from TLE data specifically.
 *
 * If exported, PropagatorPlugin.initFromTLE() calls this instead of
 * plugin_init. The buffer contains UTF-8 encoded TLE lines.
 *
 * @param tle_data  UTF-8 encoded TLE text
 * @param len       Length in bytes
 * @return          Number of satellites initialized or negative error code
 */
/* ORBPRO_EXPORT int32_t plugin_init_tle(
       const uint8_t* tle_data, size_t len); */

/**
 * Initialize from orbital elements.
 *
 * If exported, PropagatorPlugin.initFromElements() calls this instead of
 * plugin_init. The buffer contains an array of OrbProOrbitalElements.
 *
 * @param elements  Pointer to array of OrbProOrbitalElements
 * @param count     Number of element sets
 * @return          Number of entities initialized or negative error code
 */
/* ORBPRO_EXPORT int32_t plugin_init_elements(
       const OrbProOrbitalElements* elements, uint32_t count); */

/**
 * Propagate all entities to a given time (batch operation).
 *
 * If exported, PropagatorPlugin.propagateBatch() calls this for efficient
 * batch processing instead of calling plugin_propagate in a loop.
 *
 * @param julian_date  Target time as Julian date
 * @param out          Pointer to output buffer (count × 64 bytes)
 * @param count        Number of entities to propagate
 * @return             0 on success, negative error code on failure
 */
/* ORBPRO_EXPORT int32_t plugin_propagate_batch(
       double julian_date, OrbProStateVector* out, uint32_t count); */

/**
 * Get information about an initialized entity.
 *
 * @param entity_index  Index of the entity
 * @param out           Output buffer (256 bytes, format plugin-defined)
 * @return              0 on success, negative error code if not available
 */
/* ORBPRO_EXPORT int32_t get_entity_info(
       uint32_t entity_index, uint8_t* out); */

/**
 * Clean up all resources. Called when the plugin is being unloaded.
 */
/* ORBPRO_EXPORT void plugin_destroy(void); */

/* ========================================================================= */
/* Helper Functions                                                          */
/* ========================================================================= */

/*
 * COMPATIBILITY ALIASES.
 *
 * `orbpro_state_init()` and `orbpro_state_set_reference_frame()` are now
 * GENERATED into generated/orbpro_propagator_abi.h from the IDL — including
 * the padding-clearing behaviour, which is derived from the declared layout
 * rather than hand-counted. `orbpro_state_set_frame()` is the name this
 * header shipped that behaviour under, kept as a one-line alias so existing
 * plugin sources keep compiling.
 */

/**
 * Set the reference frame AND clear the three IDL-reserved bytes.
 *
 * USE THIS (or the generated `orbpro_state_set_reference_frame`) instead of
 * assigning `sv->reference_frame` directly. The field is a single byte, so a
 * direct assignment leaves the padding holding whatever was in the buffer
 * before — and a consumer that reads offset 56 as a 32-bit word (which
 * several do, on the little-endian assumption the old `uint32_t` declaration
 * invited) then sees garbage in the high bytes.
 */
static inline void orbpro_state_set_frame(
    OrbProStateVector* sv, OrbProReferenceFrame frame
) {
    orbpro_state_set_reference_frame(sv, frame);
}

/**
 * Set position on a state vector — METERS.
 * See the NORMATIVE UNITS block at the top of this file.
 */
static inline void orbpro_state_set_position(
    OrbProStateVector* sv, double x, double y, double z
) {
    sv->position[0] = x;
    sv->position[1] = y;
    sv->position[2] = z;
}

/**
 * Set velocity on a state vector — METERS PER SECOND.
 * See the NORMATIVE UNITS block at the top of this file.
 */
static inline void orbpro_state_set_velocity(
    OrbProStateVector* sv, double vx, double vy, double vz
) {
    sv->velocity[0] = vx;
    sv->velocity[1] = vy;
    sv->velocity[2] = vz;
}

/**
 * Mark a state vector as valid.
 */
static inline void orbpro_state_set_valid(OrbProStateVector* sv) {
    sv->flags |= ORBPRO_STATE_VALID;
}

/**
 * Check if a state vector is valid.
 */
static inline bool orbpro_state_is_valid(const OrbProStateVector* sv) {
    return (sv->flags & ORBPRO_STATE_VALID) != 0;
}

#ifdef __cplusplus
}
#endif

#endif /* ORBPRO_PROPAGATOR_H */
