# automatically generated by the FlatBuffers compiler, do not modify

# namespace: entity

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EntityMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EntityMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEntityMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EntityMetadataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x4E\x54\x4D", size_prefixed=size_prefixed)

    # EntityMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntityMetadata
    def EntityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def EntityKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def Subtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def ParentEntityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def PrimarySchemaFileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def PrimaryRowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def WasmHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def PositionRegionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def PositionRecordIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def VelocityRegionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def VelocityRecordIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def VisibilityRegionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def VisibilityRecordIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def NoradCatId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EntityMetadata
    def ObjectName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def ObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def CatObjectName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def CatObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def FacilityType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def SearchText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def Owner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def StatusCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def LaunchDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def LaunchYear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def OrbitRegime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EntityMetadata
    def Period(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def Inclination(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def Apogee(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def Perigee(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def MeanMotion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def Eccentricity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def Bstar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EntityMetadata
    def HasGp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def EntityMetadataStart(builder):
    builder.StartObject(34)

def Start(builder):
    EntityMetadataStart(builder)

def EntityMetadataAddEntityId(builder, entityId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entityId), 0)

def AddEntityId(builder, entityId):
    EntityMetadataAddEntityId(builder, entityId)

def EntityMetadataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    EntityMetadataAddName(builder, name)

def EntityMetadataAddEntityKind(builder, entityKind):
    builder.PrependUint8Slot(2, entityKind, 0)

def AddEntityKind(builder, entityKind):
    EntityMetadataAddEntityKind(builder, entityKind)

def EntityMetadataAddSubtype(builder, subtype):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(subtype), 0)

def AddSubtype(builder, subtype):
    EntityMetadataAddSubtype(builder, subtype)

def EntityMetadataAddParentEntityId(builder, parentEntityId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(parentEntityId), 0)

def AddParentEntityId(builder, parentEntityId):
    EntityMetadataAddParentEntityId(builder, parentEntityId)

def EntityMetadataAddPrimarySchemaFileId(builder, primarySchemaFileId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(primarySchemaFileId), 0)

def AddPrimarySchemaFileId(builder, primarySchemaFileId):
    EntityMetadataAddPrimarySchemaFileId(builder, primarySchemaFileId)

def EntityMetadataAddPrimaryRowId(builder, primaryRowId):
    builder.PrependFloat64Slot(6, primaryRowId, 0.0)

def AddPrimaryRowId(builder, primaryRowId):
    EntityMetadataAddPrimaryRowId(builder, primaryRowId)

def EntityMetadataAddWasmHandle(builder, wasmHandle):
    builder.PrependUint32Slot(7, wasmHandle, 0)

def AddWasmHandle(builder, wasmHandle):
    EntityMetadataAddWasmHandle(builder, wasmHandle)

def EntityMetadataAddPositionRegionId(builder, positionRegionId):
    builder.PrependUint32Slot(8, positionRegionId, 0)

def AddPositionRegionId(builder, positionRegionId):
    EntityMetadataAddPositionRegionId(builder, positionRegionId)

def EntityMetadataAddPositionRecordIndex(builder, positionRecordIndex):
    builder.PrependUint32Slot(9, positionRecordIndex, 0)

def AddPositionRecordIndex(builder, positionRecordIndex):
    EntityMetadataAddPositionRecordIndex(builder, positionRecordIndex)

def EntityMetadataAddVelocityRegionId(builder, velocityRegionId):
    builder.PrependUint32Slot(10, velocityRegionId, 0)

def AddVelocityRegionId(builder, velocityRegionId):
    EntityMetadataAddVelocityRegionId(builder, velocityRegionId)

def EntityMetadataAddVelocityRecordIndex(builder, velocityRecordIndex):
    builder.PrependUint32Slot(11, velocityRecordIndex, 0)

def AddVelocityRecordIndex(builder, velocityRecordIndex):
    EntityMetadataAddVelocityRecordIndex(builder, velocityRecordIndex)

def EntityMetadataAddVisibilityRegionId(builder, visibilityRegionId):
    builder.PrependUint32Slot(12, visibilityRegionId, 0)

def AddVisibilityRegionId(builder, visibilityRegionId):
    EntityMetadataAddVisibilityRegionId(builder, visibilityRegionId)

def EntityMetadataAddVisibilityRecordIndex(builder, visibilityRecordIndex):
    builder.PrependUint32Slot(13, visibilityRecordIndex, 0)

def AddVisibilityRecordIndex(builder, visibilityRecordIndex):
    EntityMetadataAddVisibilityRecordIndex(builder, visibilityRecordIndex)

def EntityMetadataAddNoradCatId(builder, noradCatId):
    builder.PrependUint32Slot(14, noradCatId, 0)

def AddNoradCatId(builder, noradCatId):
    EntityMetadataAddNoradCatId(builder, noradCatId)

def EntityMetadataAddObjectName(builder, objectName):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(objectName), 0)

def AddObjectName(builder, objectName):
    EntityMetadataAddObjectName(builder, objectName)

def EntityMetadataAddObjectId(builder, objectId):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(objectId), 0)

def AddObjectId(builder, objectId):
    EntityMetadataAddObjectId(builder, objectId)

def EntityMetadataAddCatObjectName(builder, catObjectName):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(catObjectName), 0)

def AddCatObjectName(builder, catObjectName):
    EntityMetadataAddCatObjectName(builder, catObjectName)

def EntityMetadataAddCatObjectId(builder, catObjectId):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(catObjectId), 0)

def AddCatObjectId(builder, catObjectId):
    EntityMetadataAddCatObjectId(builder, catObjectId)

def EntityMetadataAddFacilityType(builder, facilityType):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(facilityType), 0)

def AddFacilityType(builder, facilityType):
    EntityMetadataAddFacilityType(builder, facilityType)

def EntityMetadataAddSearchText(builder, searchText):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(searchText), 0)

def AddSearchText(builder, searchText):
    EntityMetadataAddSearchText(builder, searchText)

def EntityMetadataAddOwner(builder, owner):
    builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(owner), 0)

def AddOwner(builder, owner):
    EntityMetadataAddOwner(builder, owner)

def EntityMetadataAddStatusCode(builder, statusCode):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(statusCode), 0)

def AddStatusCode(builder, statusCode):
    EntityMetadataAddStatusCode(builder, statusCode)

def EntityMetadataAddLaunchDate(builder, launchDate):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(launchDate), 0)

def AddLaunchDate(builder, launchDate):
    EntityMetadataAddLaunchDate(builder, launchDate)

def EntityMetadataAddLaunchYear(builder, launchYear):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(launchYear), 0)

def AddLaunchYear(builder, launchYear):
    EntityMetadataAddLaunchYear(builder, launchYear)

def EntityMetadataAddOrbitRegime(builder, orbitRegime):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(orbitRegime), 0)

def AddOrbitRegime(builder, orbitRegime):
    EntityMetadataAddOrbitRegime(builder, orbitRegime)

def EntityMetadataAddPeriod(builder, period):
    builder.PrependFloat64Slot(26, period, 0.0)

def AddPeriod(builder, period):
    EntityMetadataAddPeriod(builder, period)

def EntityMetadataAddInclination(builder, inclination):
    builder.PrependFloat64Slot(27, inclination, 0.0)

def AddInclination(builder, inclination):
    EntityMetadataAddInclination(builder, inclination)

def EntityMetadataAddApogee(builder, apogee):
    builder.PrependFloat64Slot(28, apogee, 0.0)

def AddApogee(builder, apogee):
    EntityMetadataAddApogee(builder, apogee)

def EntityMetadataAddPerigee(builder, perigee):
    builder.PrependFloat64Slot(29, perigee, 0.0)

def AddPerigee(builder, perigee):
    EntityMetadataAddPerigee(builder, perigee)

def EntityMetadataAddMeanMotion(builder, meanMotion):
    builder.PrependFloat64Slot(30, meanMotion, 0.0)

def AddMeanMotion(builder, meanMotion):
    EntityMetadataAddMeanMotion(builder, meanMotion)

def EntityMetadataAddEccentricity(builder, eccentricity):
    builder.PrependFloat64Slot(31, eccentricity, 0.0)

def AddEccentricity(builder, eccentricity):
    EntityMetadataAddEccentricity(builder, eccentricity)

def EntityMetadataAddBstar(builder, bstar):
    builder.PrependFloat64Slot(32, bstar, 0.0)

def AddBstar(builder, bstar):
    EntityMetadataAddBstar(builder, bstar)

def EntityMetadataAddHasGp(builder, hasGp):
    builder.PrependBoolSlot(33, hasGp, 0)

def AddHasGp(builder, hasGp):
    EntityMetadataAddHasGp(builder, hasGp)

def EntityMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return EntityMetadataEnd(builder)


class EntityMetadataT(object):

    # EntityMetadataT
    def __init__(
        self,
        entityId = None,
        name = None,
        entityKind = 0,
        subtype = None,
        parentEntityId = None,
        primarySchemaFileId = None,
        primaryRowId = 0.0,
        wasmHandle = 0,
        positionRegionId = 0,
        positionRecordIndex = 0,
        velocityRegionId = 0,
        velocityRecordIndex = 0,
        visibilityRegionId = 0,
        visibilityRecordIndex = 0,
        noradCatId = 0,
        objectName = None,
        objectId = None,
        catObjectName = None,
        catObjectId = None,
        facilityType = None,
        searchText = None,
        owner = None,
        statusCode = None,
        launchDate = None,
        launchYear = None,
        orbitRegime = None,
        period = 0.0,
        inclination = 0.0,
        apogee = 0.0,
        perigee = 0.0,
        meanMotion = 0.0,
        eccentricity = 0.0,
        bstar = 0.0,
        hasGp = False,
    ):
        self.entityId = entityId  # type: Optional[str]
        self.name = name  # type: Optional[str]
        self.entityKind = entityKind  # type: int
        self.subtype = subtype  # type: Optional[str]
        self.parentEntityId = parentEntityId  # type: Optional[str]
        self.primarySchemaFileId = primarySchemaFileId  # type: Optional[str]
        self.primaryRowId = primaryRowId  # type: float
        self.wasmHandle = wasmHandle  # type: int
        self.positionRegionId = positionRegionId  # type: int
        self.positionRecordIndex = positionRecordIndex  # type: int
        self.velocityRegionId = velocityRegionId  # type: int
        self.velocityRecordIndex = velocityRecordIndex  # type: int
        self.visibilityRegionId = visibilityRegionId  # type: int
        self.visibilityRecordIndex = visibilityRecordIndex  # type: int
        self.noradCatId = noradCatId  # type: int
        self.objectName = objectName  # type: Optional[str]
        self.objectId = objectId  # type: Optional[str]
        self.catObjectName = catObjectName  # type: Optional[str]
        self.catObjectId = catObjectId  # type: Optional[str]
        self.facilityType = facilityType  # type: Optional[str]
        self.searchText = searchText  # type: Optional[str]
        self.owner = owner  # type: Optional[str]
        self.statusCode = statusCode  # type: Optional[str]
        self.launchDate = launchDate  # type: Optional[str]
        self.launchYear = launchYear  # type: Optional[str]
        self.orbitRegime = orbitRegime  # type: Optional[str]
        self.period = period  # type: float
        self.inclination = inclination  # type: float
        self.apogee = apogee  # type: float
        self.perigee = perigee  # type: float
        self.meanMotion = meanMotion  # type: float
        self.eccentricity = eccentricity  # type: float
        self.bstar = bstar  # type: float
        self.hasGp = hasGp  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        entityMetadata = EntityMetadata()
        entityMetadata.Init(buf, pos)
        return cls.InitFromObj(entityMetadata)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, entityMetadata):
        x = EntityMetadataT()
        x._UnPack(entityMetadata)
        return x

    # EntityMetadataT
    def _UnPack(self, entityMetadata):
        if entityMetadata is None:
            return
        self.entityId = entityMetadata.EntityId()
        self.name = entityMetadata.Name()
        self.entityKind = entityMetadata.EntityKind()
        self.subtype = entityMetadata.Subtype()
        self.parentEntityId = entityMetadata.ParentEntityId()
        self.primarySchemaFileId = entityMetadata.PrimarySchemaFileId()
        self.primaryRowId = entityMetadata.PrimaryRowId()
        self.wasmHandle = entityMetadata.WasmHandle()
        self.positionRegionId = entityMetadata.PositionRegionId()
        self.positionRecordIndex = entityMetadata.PositionRecordIndex()
        self.velocityRegionId = entityMetadata.VelocityRegionId()
        self.velocityRecordIndex = entityMetadata.VelocityRecordIndex()
        self.visibilityRegionId = entityMetadata.VisibilityRegionId()
        self.visibilityRecordIndex = entityMetadata.VisibilityRecordIndex()
        self.noradCatId = entityMetadata.NoradCatId()
        self.objectName = entityMetadata.ObjectName()
        self.objectId = entityMetadata.ObjectId()
        self.catObjectName = entityMetadata.CatObjectName()
        self.catObjectId = entityMetadata.CatObjectId()
        self.facilityType = entityMetadata.FacilityType()
        self.searchText = entityMetadata.SearchText()
        self.owner = entityMetadata.Owner()
        self.statusCode = entityMetadata.StatusCode()
        self.launchDate = entityMetadata.LaunchDate()
        self.launchYear = entityMetadata.LaunchYear()
        self.orbitRegime = entityMetadata.OrbitRegime()
        self.period = entityMetadata.Period()
        self.inclination = entityMetadata.Inclination()
        self.apogee = entityMetadata.Apogee()
        self.perigee = entityMetadata.Perigee()
        self.meanMotion = entityMetadata.MeanMotion()
        self.eccentricity = entityMetadata.Eccentricity()
        self.bstar = entityMetadata.Bstar()
        self.hasGp = entityMetadata.HasGp()

    # EntityMetadataT
    def Pack(self, builder):
        if self.entityId is not None:
            entityId = builder.CreateString(self.entityId)
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.subtype is not None:
            subtype = builder.CreateString(self.subtype)
        if self.parentEntityId is not None:
            parentEntityId = builder.CreateString(self.parentEntityId)
        if self.primarySchemaFileId is not None:
            primarySchemaFileId = builder.CreateString(self.primarySchemaFileId)
        if self.objectName is not None:
            objectName = builder.CreateString(self.objectName)
        if self.objectId is not None:
            objectId = builder.CreateString(self.objectId)
        if self.catObjectName is not None:
            catObjectName = builder.CreateString(self.catObjectName)
        if self.catObjectId is not None:
            catObjectId = builder.CreateString(self.catObjectId)
        if self.facilityType is not None:
            facilityType = builder.CreateString(self.facilityType)
        if self.searchText is not None:
            searchText = builder.CreateString(self.searchText)
        if self.owner is not None:
            owner = builder.CreateString(self.owner)
        if self.statusCode is not None:
            statusCode = builder.CreateString(self.statusCode)
        if self.launchDate is not None:
            launchDate = builder.CreateString(self.launchDate)
        if self.launchYear is not None:
            launchYear = builder.CreateString(self.launchYear)
        if self.orbitRegime is not None:
            orbitRegime = builder.CreateString(self.orbitRegime)
        EntityMetadataStart(builder)
        if self.entityId is not None:
            EntityMetadataAddEntityId(builder, entityId)
        if self.name is not None:
            EntityMetadataAddName(builder, name)
        EntityMetadataAddEntityKind(builder, self.entityKind)
        if self.subtype is not None:
            EntityMetadataAddSubtype(builder, subtype)
        if self.parentEntityId is not None:
            EntityMetadataAddParentEntityId(builder, parentEntityId)
        if self.primarySchemaFileId is not None:
            EntityMetadataAddPrimarySchemaFileId(builder, primarySchemaFileId)
        EntityMetadataAddPrimaryRowId(builder, self.primaryRowId)
        EntityMetadataAddWasmHandle(builder, self.wasmHandle)
        EntityMetadataAddPositionRegionId(builder, self.positionRegionId)
        EntityMetadataAddPositionRecordIndex(builder, self.positionRecordIndex)
        EntityMetadataAddVelocityRegionId(builder, self.velocityRegionId)
        EntityMetadataAddVelocityRecordIndex(builder, self.velocityRecordIndex)
        EntityMetadataAddVisibilityRegionId(builder, self.visibilityRegionId)
        EntityMetadataAddVisibilityRecordIndex(builder, self.visibilityRecordIndex)
        EntityMetadataAddNoradCatId(builder, self.noradCatId)
        if self.objectName is not None:
            EntityMetadataAddObjectName(builder, objectName)
        if self.objectId is not None:
            EntityMetadataAddObjectId(builder, objectId)
        if self.catObjectName is not None:
            EntityMetadataAddCatObjectName(builder, catObjectName)
        if self.catObjectId is not None:
            EntityMetadataAddCatObjectId(builder, catObjectId)
        if self.facilityType is not None:
            EntityMetadataAddFacilityType(builder, facilityType)
        if self.searchText is not None:
            EntityMetadataAddSearchText(builder, searchText)
        if self.owner is not None:
            EntityMetadataAddOwner(builder, owner)
        if self.statusCode is not None:
            EntityMetadataAddStatusCode(builder, statusCode)
        if self.launchDate is not None:
            EntityMetadataAddLaunchDate(builder, launchDate)
        if self.launchYear is not None:
            EntityMetadataAddLaunchYear(builder, launchYear)
        if self.orbitRegime is not None:
            EntityMetadataAddOrbitRegime(builder, orbitRegime)
        EntityMetadataAddPeriod(builder, self.period)
        EntityMetadataAddInclination(builder, self.inclination)
        EntityMetadataAddApogee(builder, self.apogee)
        EntityMetadataAddPerigee(builder, self.perigee)
        EntityMetadataAddMeanMotion(builder, self.meanMotion)
        EntityMetadataAddEccentricity(builder, self.eccentricity)
        EntityMetadataAddBstar(builder, self.bstar)
        EntityMetadataAddHasGp(builder, self.hasGp)
        entityMetadata = EntityMetadataEnd(builder)
        return entityMetadata
