import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { createBrowserModuleHarness } from 'space-data-module-sdk/host/browser-module';
import { validateArtifactWithStandards } from 'space-data-module-sdk/compliance';

const wasm = fs.readFileSync(new URL('../dist/isomorphic/module.wasm', import.meta.url));
const manifest = JSON.parse(fs.readFileSync(new URL('../plugin-manifest.json', import.meta.url)));
// Independent live-fleet vectors: verified by the IPFS multiformats library
// during deployment, not generated by this guest. CIDv1/libp2p-key, base36:
// https://docs.ipfs.tech/how-to/address-ipfs-on-web/
const vectors = [
  ['16Uiu2HAmCL9enDzrbxJS8xKjFXVYVogjtbaJw2KQc45EYE6KkzRL','kzwfwjn5ji4pupxkysaraxurxv9mo7tb99iu3r2gna6hexozftkooiymx1qly67'],
  ['16Uiu2HAm1apfD3rAJJjgx4AC5Ms3PejRBwoqEsKpRx36uYwXuW9h','kzwfwjn5ji4pulyb1q9zuf2htgcgixasc1qqqbfdlopje54uiz12vnw4s8del58'],
];
const peerId = vectors[0][0], label = vectors[0][1], zoneId = '68ba799987854c13e1689f2dd15fc428';
const recordId = '0123456789abcdef0123456789abcdef';
const node = (extra = {}) => ({ peerId, included:true, profileVerified:true, verifiedAt:1000, originVerified:true, publicArtifactsOnly:true, originIpv4:'167.172.219.213', ...extra });
const snapshot = (nodes = [node()]) => ({ zoneId, zoneName:'spacedatanetwork.org', now:1001, nodes, records:[], recordsComplete:true, managedRecordIds:{} });
const record = (extra = {}) => ({ id:recordId, name:`${label}.spacedatanetwork.org`, type:'A', content:'167.172.219.213', ttl:1, proxied:true, comment:`sdn-peer:${label}`, ...extra });
async function harness(t) {
  const host=await createBrowserModuleHarness({wasmSource:wasm,manifest,surface:'direct'});
  t.after(()=>host.destroy()); return host;
}
async function invoke(host,value) {
  const payload=new TextEncoder().encode(JSON.stringify(value));
  return host.invoke({methodId:'plan',inputs:[{portId:'snapshot',typeRef:{wireFormat:'aligned-binary',requiredAlignment:1,byteLength:payload.length},payload}]});
}
async function plan(host,value) {
  const result=await invoke(host,value); assert.equal(result.statusCode,0,result.errorMessage);
  return JSON.parse(new TextDecoder().decode(result.outputs[0].payload));
}
test('the actual WASM artifact satisfies the SDK contract', async()=> {
  const report=await validateArtifactWithStandards({wasmPath:fileURLToPath(new URL('../dist/isomorphic/module.wasm',import.meta.url)),manifest,standardsRoot:process.env.SPACE_DATA_STANDARDS_ROOT});
  assert.equal(report.ok,true,JSON.stringify(report.issues));
});
test('derives full peer-ID hostnames and accepts the equivalent base36 identity',async t=> {
  const host=await harness(t);
  for(const [peer,expected] of vectors.slice(0,2)) for(const value of [peer,expected]) {
    const result=await plan(host,snapshot([node({peerId:value})]));
    assert.equal(result.nodes[0].hostname,`${expected}.spacedatanetwork.org`);
    assert.equal(result.actions[0].method,'POST');
    assert.equal(result.actions[0].body.proxied,true);
    assert.equal(result.applied,false);
  }
});
test('new peers default to excluded and discovery alone creates no route',async t=> {
  const host=await harness(t);
  const result=await plan(host,snapshot([{peerId}]));
  assert.deepEqual(result.actions,[]); assert.equal(result.nodes[0].status,'excluded');
});
test('requires fresh verified public origins without changing existing working records',async t=> {
  const host=await harness(t);
  for(const extra of [{profileVerified:false},{originVerified:false},{publicArtifactsOnly:false},{verifiedAt:1},{verifiedAt:1002},
    ...['127.0.0.1','10.1.2.3','172.16.2.3','192.168.1.1','169.254.1.1','100.64.1.1','198.18.1.1','192.0.2.1','203.0.113.1','224.0.0.1','01.2.3.4','167.172.219.213/path','::1'].map(originIpv4=>({originIpv4}))]) {
    const input=snapshot([node(extra)]); input.records=[record()]; input.managedRecordIds[label]=recordId;
    const result=await plan(host,input);
    assert.deepEqual(result.actions,[],JSON.stringify(extra)); assert.equal(result.nodes[0].status,'blocked');
  }
});
test('is idempotent for managed records and updates only the exact managed record',async t=> {
  const host=await harness(t),input=snapshot();input.records=[record()];input.managedRecordIds[label]=recordId;
  let result=await plan(host,input);assert.deepEqual(result.actions,[]);assert.equal(result.nodes[0].status,'included');
  input.nodes[0].originIpv4='159.203.150.8';result=await plan(host,input);
  assert.equal(result.actions.length,1);assert.equal(result.actions[0].method,'PUT');
  assert.equal(result.actions[0].path,`/zones/${zoneId}/dns_records/${recordId}`);
});
test('explicit exclusion deletes only an owned route and discloses remaining cache purge',async t=> {
  const host=await harness(t),input=snapshot([node({included:false})]);
  input.records=[record(),record({id:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',name:'www.spacedatanetwork.org',comment:'foreign'})];input.managedRecordIds[label]=recordId;
  const result=await plan(host,input);assert.equal(result.actions.length,1);assert.equal(result.actions[0].method,'DELETE');
  assert.equal(result.actions[0].recordId,recordId);assert.equal(result.nodes[0].cachePurgeRequired,true);assert.equal(result.applied,false);
  input.nodes=[];assert.deepEqual((await plan(host,input)).actions,[]);
});
test('never adopts foreign DNS, duplicates, or a changed record type',async t=> {
  const host=await harness(t);
  for(const included of [true,false]) for(const [records,managedRecordIds] of [
    [[record()],{}],[[record({comment:'foreign'})],{[label]:recordId}],
    [[record({type:'CNAME'})],{[label]:recordId}],
    [[record(),record({id:'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'})],{[label]:recordId}],
  ]) {
    const result=await plan(host,{...snapshot([node({included})]),records,managedRecordIds});
    assert.deepEqual(result.actions,[]);assert.equal(result.nodes[0].status,'conflict');
  }
});
test('rejects incomplete, ambiguous and malformed snapshots and recovers for the next call',async t=> {
  const host=await harness(t);
  for(const input of [
    {...snapshot(),recordsComplete:false},{...snapshot(),zoneId:'../another-zone'},
    {...snapshot(),zoneName:'example.org/path'},{...snapshot(),now:-1},
    snapshot([node(),node({peerId:label})]),snapshot([node({peerId:'16Uiu2HAm1yufXh215i8BDiH16PaUbULeqCt8T8WAiJxXXpuJoz5'})]),
    snapshot([node({peerId:'bafybeiaa6fk4gi775ou2l366jgo3jxjl7ib33urp556lownphi4lyblrnu'})]),
    {...snapshot(),records:[record(),record()]},snapshot([node({included:'yes'})]),
  ]) assert.notEqual((await invoke(host,input)).statusCode,0);
  assert.equal((await plan(host,snapshot())).actions.length,1);
});
