import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {compileModuleFromSource} from 'space-data-module-sdk/compiler';
import {publishedStandardsRoot} from '../terrain-source/sds-headers.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));
process.env.SPACE_DATA_STANDARDS_ROOT=publishedStandardsRoot(import.meta.url);
const pieces=['#define JSON_NOEXCEPTION'];
pieces.push(await fs.readFile(path.resolve(root,'../../propagator/sgp4/src/cpp/include/nlohmann/json.hpp'),'utf8'));
pieces.push(await fs.readFile(path.resolve(root,'../eop-request/src/eop_wire.hpp'),'utf8'));
const {generateSdsHeaders}=await import('./generate-sds-headers.mjs');
const {version,headers}=await generateSdsHeaders();
pieces.push(headers.EOP);
pieces.push(await fs.readFile(path.resolve(root,'../../files/orbit-products/src/sha256.hpp'),'utf8'));
pieces.push(await fs.readFile(path.join(root,'src/module.cpp'),'utf8'));
const manifest=JSON.parse(await fs.readFile(path.join(root,'plugin-manifest.json'),'utf8'));
const outputPath=path.join(root,'dist/isomorphic/module.wasm');
await fs.mkdir(path.dirname(outputPath),{recursive:true});
const result=await compileModuleFromSource({manifest,sourceCode:pieces.join('\n'),language:'c++',outputPath,threadModel:'single-thread'});
if(!result.report?.ok) throw new Error(JSON.stringify(result.report?.issues));
const guest=path.join(root,'dist/guest-link');await fs.mkdir(guest,{recursive:true});
await fs.writeFile(path.join(guest,'module-link.o'),result.guestLink.objectBytes);
const {format,language,threadModel,symbolPrefix,methodSymbols}=result.guestLink;
await fs.writeFile(path.join(guest,'metadata.json'),JSON.stringify({version:1,format,language,threadModel,symbolPrefix,methodSymbols},null,2)+'\n');
await fs.copyFile(path.join(root,'plugin-manifest.json'),path.join(root,'dist/plugin-manifest.json'));
console.log(`PASS SDK build ${manifest.pluginId} -> dist/isomorphic/module.wasm`);
