# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Propagator initialization request
class PropagatorInit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatorInit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatorInit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PropagatorInitBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x52\x4F\x50", size_prefixed=size_prefixed)

    # PropagatorInit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TLE data (for SGP4/SDP4 propagators)
    # PropagatorInit
    def Tle(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.legacy.orbpro.propagator.TLEData import TLEData
            obj = TLEData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropagatorInit
    def TleLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorInit
    def TleIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Keplerian elements (for numerical propagators)
    # PropagatorInit
    def Elements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.legacy.orbpro.propagator.KeplerianElements import KeplerianElements
            obj = KeplerianElements()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropagatorInit
    def ElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorInit
    def ElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Entity handles to assign results to
    # PropagatorInit
    def EntityHandles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PropagatorInit
    def EntityHandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PropagatorInit
    def EntityHandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorInit
    def EntityHandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def PropagatorInitStart(builder):
    builder.StartObject(3)

def Start(builder):
    PropagatorInitStart(builder)

def PropagatorInitAddTle(builder, tle):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tle), 0)

def AddTle(builder, tle):
    PropagatorInitAddTle(builder, tle)

def PropagatorInitStartTleVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTleVector(builder, numElems):
    return PropagatorInitStartTleVector(builder, numElems)

def PropagatorInitCreateTleVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateTleVector(builder, data):
    PropagatorInitCreateTleVector(builder, data)

def PropagatorInitAddElements(builder, elements):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elements), 0)

def AddElements(builder, elements):
    PropagatorInitAddElements(builder, elements)

def PropagatorInitStartElementsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementsVector(builder, numElems):
    return PropagatorInitStartElementsVector(builder, numElems)

def PropagatorInitCreateElementsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateElementsVector(builder, data):
    PropagatorInitCreateElementsVector(builder, data)

def PropagatorInitAddEntityHandles(builder, entityHandles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(entityHandles), 0)

def AddEntityHandles(builder, entityHandles):
    PropagatorInitAddEntityHandles(builder, entityHandles)

def PropagatorInitStartEntityHandlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntityHandlesVector(builder, numElems):
    return PropagatorInitStartEntityHandlesVector(builder, numElems)

def PropagatorInitCreateEntityHandlesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateEntityHandlesVector(builder, data):
    PropagatorInitCreateEntityHandlesVector(builder, data)

def PropagatorInitEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatorInitEnd(builder)

import spacedatanetwork_astro.invoke.legacy.orbpro.propagator.KeplerianElements
import spacedatanetwork_astro.invoke.legacy.orbpro.propagator.TLEData
try:
    from typing import List
except:
    pass

class PropagatorInitT(object):

    # PropagatorInitT
    def __init__(
        self,
        tle = None,
        elements = None,
        entityHandles = None,
    ):
        self.tle = tle  # type: Optional[List[orbpro.propagator.TLEData.TLEDataT]]
        self.elements = elements  # type: Optional[List[orbpro.propagator.KeplerianElements.KeplerianElementsT]]
        self.entityHandles = entityHandles  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatorInit = PropagatorInit()
        propagatorInit.Init(buf, pos)
        return cls.InitFromObj(propagatorInit)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatorInit):
        x = PropagatorInitT()
        x._UnPack(propagatorInit)
        return x

    # PropagatorInitT
    def _UnPack(self, propagatorInit):
        if propagatorInit is None:
            return
        if not propagatorInit.TleIsNone():
            self.tle = []
            for i in range(propagatorInit.TleLength()):
                if propagatorInit.Tle(i) is None:
                    self.tle.append(None)
                else:
                    tLEData_ = spacedatanetwork_astro.invoke.legacy.orbpro.propagator.TLEData.TLEDataT.InitFromObj(propagatorInit.Tle(i))
                    self.tle.append(tLEData_)
        if not propagatorInit.ElementsIsNone():
            self.elements = []
            for i in range(propagatorInit.ElementsLength()):
                if propagatorInit.Elements(i) is None:
                    self.elements.append(None)
                else:
                    keplerianElements_ = spacedatanetwork_astro.invoke.legacy.orbpro.propagator.KeplerianElements.KeplerianElementsT.InitFromObj(propagatorInit.Elements(i))
                    self.elements.append(keplerianElements_)
        if not propagatorInit.EntityHandlesIsNone():
            if np is None:
                self.entityHandles = []
                for i in range(propagatorInit.EntityHandlesLength()):
                    self.entityHandles.append(propagatorInit.EntityHandles(i))
            else:
                self.entityHandles = propagatorInit.EntityHandlesAsNumpy()

    # PropagatorInitT
    def Pack(self, builder):
        if self.tle is not None:
            tlelist = []
            for i in range(len(self.tle)):
                tlelist.append(self.tle[i].Pack(builder))
            PropagatorInitStartTleVector(builder, len(self.tle))
            for i in reversed(range(len(self.tle))):
                builder.PrependUOffsetTRelative(tlelist[i])
            tle = builder.EndVector()
        if self.elements is not None:
            elementslist = []
            for i in range(len(self.elements)):
                elementslist.append(self.elements[i].Pack(builder))
            PropagatorInitStartElementsVector(builder, len(self.elements))
            for i in reversed(range(len(self.elements))):
                builder.PrependUOffsetTRelative(elementslist[i])
            elements = builder.EndVector()
        if self.entityHandles is not None:
            if np is not None and type(self.entityHandles) is np.ndarray:
                entityHandles = builder.CreateNumpyVector(self.entityHandles)
            else:
                PropagatorInitStartEntityHandlesVector(builder, len(self.entityHandles))
                for i in reversed(range(len(self.entityHandles))):
                    builder.PrependUint32(self.entityHandles[i])
                entityHandles = builder.EndVector()
        PropagatorInitStart(builder)
        if self.tle is not None:
            PropagatorInitAddTle(builder, tle)
        if self.elements is not None:
            PropagatorInitAddElements(builder, elements)
        if self.entityHandles is not None:
            PropagatorInitAddEntityHandles(builder, entityHandles)
        propagatorInit = PropagatorInitEnd(builder)
        return propagatorInit
