# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

# Reference frame for state vectors
class ReferenceFrame(object):
    # True Equator Mean Equinox (SGP4 native)
    TEME = 0
    # J2000 equatorial (EME2000)
    J2000 = 1
    # International Celestial Reference Frame
    ICRF = 2
    # Earth-Centered Earth-Fixed (ITRF)
    ECEF = 3
    # Moon-Centered Inertial
    MCI = 4
    # Moon-Centered Moon-Fixed
    MCMF = 5
