// Offline end-to-end rehearsal for the global pyramid coordinator.
//
// This deliberately drives the shipped `run.mjs` once over a multi-region
// fixture and `global-build.mjs` with two OS child workers, then compares the
// non-empty $DTT address -> record-byte digests. A direct module harness would
// not test the runner's prefetch/cache/resume host boundary or worker merge.

import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import { recordSetDigest } from "./build-support.mjs";
import { iterateStreamFile, readDtt } from "./dtt-reader.mjs";

const execFileAsync = promisify(execFile);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");
const RUNNER = path.join(HERE, "run.mjs");
const COORDINATOR = path.join(HERE, "global-build.mjs");

let out;
for (let i = 2; i < process.argv.length; i += 1) {
  if (process.argv[i] === "--out") out = process.argv[++i];
  else throw new Error(`unknown argument ${process.argv[i]}`);
}
assert.ok(out, "--out <report.json> is required");

function granuleFromRequest(url) {
  const match = url.match(/Copernicus_DSM_COG_10_([NS])(\d\d)_00_([EW])(\d\d\d)_00_(DEM|WBM)\.tif$/);
  assert.ok(match, `unexpected fixture granule URL ${url}`);
  const lat = (match[1] === "S" ? -1 : 1) * Number(match[2]);
  const lon = (match[3] === "W" ? -1 : 1) * Number(match[4]);
  const water = match[5] === "WBM";
  // Keep this byte layout identical to the compiled flow's own fixture. The
  // generic source-test TIFF writer is broader (tiled/DEFLATE/predictors),
  // while this rehearsal needs a small, known-good uncompressed strip input.
  const posts = 121;
  const scale = 1 / (posts - 1);
  const sampleBytes = water ? 1 : 4;
  const raw = Buffer.alloc(posts * posts * sampleBytes);
  for (let y = 0; y < posts; y += 1) for (let x = 0; x < posts; x += 1) {
    const at = (y * posts + x) * sampleBytes;
    if (water) raw[at] = x < posts / 2 ? 0 : 1;
    else raw.writeFloatLE(Math.fround(200 + 900 * Math.sin(x / 7) * Math.cos(y / 5)), at);
  }
  const entries = [
    [256, 3, 1, posts], [257, 3, 1, posts], [258, 3, 1, water ? 8 : 32], [259, 3, 1, 1],
    [273, 4, 1, 0], [277, 3, 1, 1], [278, 3, 1, posts], [279, 4, 1, raw.length],
    [317, 3, 1, 1], [339, 3, 1, water ? 1 : 3], [33550, 12, 3, 0], [33922, 12, 6, 0],
  ];
  const ifdBytes = 2 + entries.length * 12 + 4;
  const scaleOffset = 8 + ifdBytes;
  const tiepointOffset = scaleOffset + 24;
  const dataOffset = tiepointOffset + 48;
  entries[4][3] = dataOffset; entries[10][3] = scaleOffset; entries[11][3] = tiepointOffset;
  const file = Buffer.alloc(dataOffset + raw.length);
  file.write("II", 0, "latin1"); file.writeUInt16LE(42, 2); file.writeUInt32LE(8, 4); file.writeUInt16LE(entries.length, 8);
  entries.forEach(([id, type, count, value], n) => {
    const at = 10 + n * 12;
    file.writeUInt16LE(id, at); file.writeUInt16LE(type, at + 2); file.writeUInt32LE(count, at + 4);
    if (type === 3) file.writeUInt16LE(value, at + 8); else file.writeUInt32LE(value, at + 8);
  });
  file.writeDoubleLE(scale, scaleOffset); file.writeDoubleLE(scale, scaleOffset + 8);
  file.writeDoubleLE(lon, tiepointOffset + 24); file.writeDoubleLE(lat + 1, tiepointOffset + 32);
  raw.copy(file, dataOffset);
  return file;
}

const bodies = new Map();
const server = http.createServer((request, response) => {
  try {
    const key = request.url ?? "";
    const body = bodies.get(key) ?? granuleFromRequest(key);
    bodies.set(key, body);
    response.writeHead(200, { "content-type": "image/tiff", "content-length": body.length });
    response.end(body);
  } catch (error) {
    response.writeHead(500, { "content-type": "text/plain" });
    response.end(String(error.message ?? error));
  }
});
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const address = server.address();
assert.ok(address && typeof address === "object");

const root = fs.mkdtempSync(path.join(os.tmpdir(), "terrain-global-rehearsal-"));
const config = path.join(root, "run.json");
// Two adjacent one-degree regions force independent deterministic longitude
// shards. Every requested granule is generated by the local-only server.
fs.writeFileSync(config, `${JSON.stringify({
  cache_max_bytes: 32 * 1024 * 1024,
  flow_config: {
    dataset_id: "offline-rehearsal", tileset_id: "offline-rehearsal",
    dataset_epoch: "2026-09-01T00:00:00.000Z", retrieved_at: "2026-09-01T00:00:00.000Z",
    provider_id: "offline", source_name: "offline-fixture",
    granule_base_url: `http://127.0.0.1:${address.port}/`, grid_size: 9, max_grid_size: 25,
    min_level: 8, max_level: 8, timeout_ms: 10_000,
    regions: [{ name: "fixture-west-east", west: 8, south: 44, east: 10, north: 45, max_level: 8, priority: 1 }],
  },
}, null, 2)}\n`);

async function digestStore(dir) {
  const rows = [];
  for await (const record of iterateStreamFile(path.join(dir, "tiles.dttstream"))) {
    const dtt = readDtt(record);
    rows.push([`${dtt.level}/${dtt.x}/${dtt.y}`, createHash("sha256").update(record).digest("hex")]);
  }
  assert.ok(rows.length > 0, "offline rehearsal must emit non-empty $DTT records");
  return { records: rows.length, digest: recordSetDigest(rows) };
}

try {
  const single = path.join(root, "single");
  const sharded = path.join(root, "sharded");
  const startedSingle = performance.now();
  await execFileAsync(process.execPath, [RUNNER, "--config", config, "--out", single, "--no-wasmedge-verify"], { cwd: REPO });
  const singleLaneMs = performance.now() - startedSingle;
  const startedShards = performance.now();
  await execFileAsync(process.execPath, [COORDINATOR, "--config", config, "--out", sharded, "--shards", "2", "--workers", "2", "--no-wasmedge-verify", "--skip-verify"], { cwd: REPO });
  const concurrentShardMs = performance.now() - startedShards;
  const one = await digestStore(single);
  const many = await digestStore(sharded);
  assert.equal(many.digest, one.digest, "single runner and OS-worker global coordinator must emit the same $DTT address/byte set");
  const report = {
    regions: [{ name: "fixture-west-east", west: 8, south: 44, east: 10, north: 45 }],
    records: one.records, singleLaneMs: +singleLaneMs.toFixed(3), concurrentShardMs: +concurrentShardMs.toFixed(3),
    recordSetDigest: one.digest, parity: "PASS", execution: "run.mjs single lane vs global-build.mjs (2 OS workers + merge)",
  };
  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(path.resolve(out), `${JSON.stringify(report, null, 2)}\n`);
  console.log(JSON.stringify(report));
} finally {
  await new Promise((resolve) => server.close(resolve));
  fs.rmSync(root, { recursive: true, force: true });
}
