# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Keplerian orbital elements — the OPTIONAL initialization input accepted by
# `plugin_init_elements`. 64 bytes, 8-byte aligned.
#
# UNITS NOTE: `semi_major_axis` is KILOMETRES. That is deliberate and it is
# NOT an inconsistency with StateVector's metres: this is an INPUT element
# set, not an output state vector, and the two are different structs on
# different sides of the call. Do not "unify" them — see the normative units
# block in the generated C header.
class OrbitalElements(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 64

    # OrbitalElements
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Semi-major axis in KILOMETRES.
    # OrbitalElements
    def SemiMajorAxis(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Orbital eccentricity (0 = circular, <1 = ellipse).
    # OrbitalElements
    def Eccentricity(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Inclination in RADIANS.
    # OrbitalElements
    def Inclination(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Right ascension of the ascending node in RADIANS.
    # OrbitalElements
    def Raan(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # Argument of periapsis in RADIANS.
    # OrbitalElements
    def ArgPeriapsis(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # True anomaly in RADIANS.
    # OrbitalElements
    def TrueAnomaly(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))
    # Epoch as a Julian date.
    # OrbitalElements
    def Epoch(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))
    # Reserved, MUST be written as 0.
    # OrbitalElements
    def Reserved(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(56))

def CreateOrbitalElements(builder, semiMajorAxis, eccentricity, inclination, raan, argPeriapsis, trueAnomaly, epoch, reserved):
    builder.Prep(8, 64)
    builder.PrependFloat64(reserved)
    builder.PrependFloat64(epoch)
    builder.PrependFloat64(trueAnomaly)
    builder.PrependFloat64(argPeriapsis)
    builder.PrependFloat64(raan)
    builder.PrependFloat64(inclination)
    builder.PrependFloat64(eccentricity)
    builder.PrependFloat64(semiMajorAxis)
    return builder.Offset()


class OrbitalElementsT(object):

    # OrbitalElementsT
    def __init__(
        self,
        semiMajorAxis = 0.0,
        eccentricity = 0.0,
        inclination = 0.0,
        raan = 0.0,
        argPeriapsis = 0.0,
        trueAnomaly = 0.0,
        epoch = 0.0,
        reserved = 0.0,
    ):
        self.semiMajorAxis = semiMajorAxis  # type: float
        self.eccentricity = eccentricity  # type: float
        self.inclination = inclination  # type: float
        self.raan = raan  # type: float
        self.argPeriapsis = argPeriapsis  # type: float
        self.trueAnomaly = trueAnomaly  # type: float
        self.epoch = epoch  # type: float
        self.reserved = reserved  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        orbitalElements = OrbitalElements()
        orbitalElements.Init(buf, pos)
        return cls.InitFromObj(orbitalElements)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, orbitalElements):
        x = OrbitalElementsT()
        x._UnPack(orbitalElements)
        return x

    # OrbitalElementsT
    def _UnPack(self, orbitalElements):
        if orbitalElements is None:
            return
        self.semiMajorAxis = orbitalElements.SemiMajorAxis()
        self.eccentricity = orbitalElements.Eccentricity()
        self.inclination = orbitalElements.Inclination()
        self.raan = orbitalElements.Raan()
        self.argPeriapsis = orbitalElements.ArgPeriapsis()
        self.trueAnomaly = orbitalElements.TrueAnomaly()
        self.epoch = orbitalElements.Epoch()
        self.reserved = orbitalElements.Reserved()

    # OrbitalElementsT
    def Pack(self, builder):
        return CreateOrbitalElements(builder, self.semiMajorAxis, self.eccentricity, self.inclination, self.raan, self.argPeriapsis, self.trueAnomaly, self.epoch, self.reserved)
