# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropagatorSampleTrajectoryStatesResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatorSampleTrajectoryStatesResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatorSampleTrajectoryStatesResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropagatorSampleTrajectoryStatesResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropagatorSampleTrajectoryStatesResult
    def CatalogHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def StartJd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSampleTrajectoryStatesResult
    def DurationDays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSampleTrajectoryStatesResult
    def SampleJds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SampleJdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SampleJdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SampleJdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # PropagatorSampleTrajectoryStatesResult
    def SourceHandles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SourceHandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SourceHandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def SourceHandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # PropagatorSampleTrajectoryStatesResult
    def ReferenceFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def States(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 64
            from spacedatanetwork_astro.invoke.orbpro.propagator.StateVector import StateVector
            obj = StateVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropagatorSampleTrajectoryStatesResult
    def StatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorSampleTrajectoryStatesResult
    def StatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def PropagatorSampleTrajectoryStatesResultStart(builder):
    builder.StartObject(7)

def Start(builder):
    PropagatorSampleTrajectoryStatesResultStart(builder)

def PropagatorSampleTrajectoryStatesResultAddCatalogHandle(builder, catalogHandle):
    builder.PrependUint32Slot(0, catalogHandle, 0)

def AddCatalogHandle(builder, catalogHandle):
    PropagatorSampleTrajectoryStatesResultAddCatalogHandle(builder, catalogHandle)

def PropagatorSampleTrajectoryStatesResultAddStartJd(builder, startJd):
    builder.PrependFloat64Slot(1, startJd, 0.0)

def AddStartJd(builder, startJd):
    PropagatorSampleTrajectoryStatesResultAddStartJd(builder, startJd)

def PropagatorSampleTrajectoryStatesResultAddDurationDays(builder, durationDays):
    builder.PrependFloat64Slot(2, durationDays, 0.0)

def AddDurationDays(builder, durationDays):
    PropagatorSampleTrajectoryStatesResultAddDurationDays(builder, durationDays)

def PropagatorSampleTrajectoryStatesResultAddSampleJds(builder, sampleJds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sampleJds), 0)

def AddSampleJds(builder, sampleJds):
    PropagatorSampleTrajectoryStatesResultAddSampleJds(builder, sampleJds)

def PropagatorSampleTrajectoryStatesResultStartSampleJdsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartSampleJdsVector(builder, numElems):
    return PropagatorSampleTrajectoryStatesResultStartSampleJdsVector(builder, numElems)

def PropagatorSampleTrajectoryStatesResultCreateSampleJdsVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependFloat64(item)
    return builder.EndVector()

def CreateSampleJdsVector(builder, data):
    PropagatorSampleTrajectoryStatesResultCreateSampleJdsVector(builder, data)

def PropagatorSampleTrajectoryStatesResultAddSourceHandles(builder, sourceHandles):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(sourceHandles), 0)

def AddSourceHandles(builder, sourceHandles):
    PropagatorSampleTrajectoryStatesResultAddSourceHandles(builder, sourceHandles)

def PropagatorSampleTrajectoryStatesResultStartSourceHandlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSourceHandlesVector(builder, numElems):
    return PropagatorSampleTrajectoryStatesResultStartSourceHandlesVector(builder, numElems)

def PropagatorSampleTrajectoryStatesResultCreateSourceHandlesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateSourceHandlesVector(builder, data):
    PropagatorSampleTrajectoryStatesResultCreateSourceHandlesVector(builder, data)

def PropagatorSampleTrajectoryStatesResultAddReferenceFrame(builder, referenceFrame):
    builder.PrependUint8Slot(5, referenceFrame, 0)

def AddReferenceFrame(builder, referenceFrame):
    PropagatorSampleTrajectoryStatesResultAddReferenceFrame(builder, referenceFrame)

def PropagatorSampleTrajectoryStatesResultAddStates(builder, states):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(states), 0)

def AddStates(builder, states):
    PropagatorSampleTrajectoryStatesResultAddStates(builder, states)

def PropagatorSampleTrajectoryStatesResultStartStatesVector(builder, numElems):
    return builder.StartVector(64, numElems, 8)

def StartStatesVector(builder, numElems):
    return PropagatorSampleTrajectoryStatesResultStartStatesVector(builder, numElems)

def PropagatorSampleTrajectoryStatesResultCreateStatesVector(builder, data):
    data = list(data)
    builder.StartVector(64, len(data), 8)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateStatesVector(builder, data):
    PropagatorSampleTrajectoryStatesResultCreateStatesVector(builder, data)

def PropagatorSampleTrajectoryStatesResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatorSampleTrajectoryStatesResultEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.propagator.StateVector
try:
    from typing import List
except:
    pass

class PropagatorSampleTrajectoryStatesResultT(object):

    # PropagatorSampleTrajectoryStatesResultT
    def __init__(
        self,
        catalogHandle = 0,
        startJd = 0.0,
        durationDays = 0.0,
        sampleJds = None,
        sourceHandles = None,
        referenceFrame = 0,
        states = None,
    ):
        self.catalogHandle = catalogHandle  # type: int
        self.startJd = startJd  # type: float
        self.durationDays = durationDays  # type: float
        self.sampleJds = sampleJds  # type: Optional[List[float]]
        self.sourceHandles = sourceHandles  # type: Optional[List[int]]
        self.referenceFrame = referenceFrame  # type: int
        self.states = states  # type: Optional[List[orbpro.propagator.StateVector.StateVectorT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatorSampleTrajectoryStatesResult = PropagatorSampleTrajectoryStatesResult()
        propagatorSampleTrajectoryStatesResult.Init(buf, pos)
        return cls.InitFromObj(propagatorSampleTrajectoryStatesResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatorSampleTrajectoryStatesResult):
        x = PropagatorSampleTrajectoryStatesResultT()
        x._UnPack(propagatorSampleTrajectoryStatesResult)
        return x

    # PropagatorSampleTrajectoryStatesResultT
    def _UnPack(self, propagatorSampleTrajectoryStatesResult):
        if propagatorSampleTrajectoryStatesResult is None:
            return
        self.catalogHandle = propagatorSampleTrajectoryStatesResult.CatalogHandle()
        self.startJd = propagatorSampleTrajectoryStatesResult.StartJd()
        self.durationDays = propagatorSampleTrajectoryStatesResult.DurationDays()
        if not propagatorSampleTrajectoryStatesResult.SampleJdsIsNone():
            if np is None:
                self.sampleJds = []
                for i in range(propagatorSampleTrajectoryStatesResult.SampleJdsLength()):
                    self.sampleJds.append(propagatorSampleTrajectoryStatesResult.SampleJds(i))
            else:
                self.sampleJds = propagatorSampleTrajectoryStatesResult.SampleJdsAsNumpy()
        if not propagatorSampleTrajectoryStatesResult.SourceHandlesIsNone():
            if np is None:
                self.sourceHandles = []
                for i in range(propagatorSampleTrajectoryStatesResult.SourceHandlesLength()):
                    self.sourceHandles.append(propagatorSampleTrajectoryStatesResult.SourceHandles(i))
            else:
                self.sourceHandles = propagatorSampleTrajectoryStatesResult.SourceHandlesAsNumpy()
        self.referenceFrame = propagatorSampleTrajectoryStatesResult.ReferenceFrame()
        if not propagatorSampleTrajectoryStatesResult.StatesIsNone():
            self.states = []
            for i in range(propagatorSampleTrajectoryStatesResult.StatesLength()):
                if propagatorSampleTrajectoryStatesResult.States(i) is None:
                    self.states.append(None)
                else:
                    stateVector_ = spacedatanetwork_astro.invoke.orbpro.propagator.StateVector.StateVectorT.InitFromObj(propagatorSampleTrajectoryStatesResult.States(i))
                    self.states.append(stateVector_)

    # PropagatorSampleTrajectoryStatesResultT
    def Pack(self, builder):
        if self.sampleJds is not None:
            if np is not None and type(self.sampleJds) is np.ndarray:
                sampleJds = builder.CreateNumpyVector(self.sampleJds)
            else:
                PropagatorSampleTrajectoryStatesResultStartSampleJdsVector(builder, len(self.sampleJds))
                for i in reversed(range(len(self.sampleJds))):
                    builder.PrependFloat64(self.sampleJds[i])
                sampleJds = builder.EndVector()
        if self.sourceHandles is not None:
            if np is not None and type(self.sourceHandles) is np.ndarray:
                sourceHandles = builder.CreateNumpyVector(self.sourceHandles)
            else:
                PropagatorSampleTrajectoryStatesResultStartSourceHandlesVector(builder, len(self.sourceHandles))
                for i in reversed(range(len(self.sourceHandles))):
                    builder.PrependUint32(self.sourceHandles[i])
                sourceHandles = builder.EndVector()
        if self.states is not None:
            PropagatorSampleTrajectoryStatesResultStartStatesVector(builder, len(self.states))
            for i in reversed(range(len(self.states))):
                self.states[i].Pack(builder)
            states = builder.EndVector()
        PropagatorSampleTrajectoryStatesResultStart(builder)
        PropagatorSampleTrajectoryStatesResultAddCatalogHandle(builder, self.catalogHandle)
        PropagatorSampleTrajectoryStatesResultAddStartJd(builder, self.startJd)
        PropagatorSampleTrajectoryStatesResultAddDurationDays(builder, self.durationDays)
        if self.sampleJds is not None:
            PropagatorSampleTrajectoryStatesResultAddSampleJds(builder, sampleJds)
        if self.sourceHandles is not None:
            PropagatorSampleTrajectoryStatesResultAddSourceHandles(builder, sourceHandles)
        PropagatorSampleTrajectoryStatesResultAddReferenceFrame(builder, self.referenceFrame)
        if self.states is not None:
            PropagatorSampleTrajectoryStatesResultAddStates(builder, states)
        propagatorSampleTrajectoryStatesResult = PropagatorSampleTrajectoryStatesResultEnd(builder)
        return propagatorSampleTrajectoryStatesResult
