# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropagatorDescribeSourcesBatchResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatorDescribeSourcesBatchResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatorDescribeSourcesBatchResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropagatorDescribeSourcesBatchResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropagatorDescribeSourcesBatchResult
    def CatalogHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorDescribeSourcesBatchResult
    def Sources(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.orbpro.propagator.PropagatorSourceDescription import PropagatorSourceDescription
            obj = PropagatorSourceDescription()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropagatorDescribeSourcesBatchResult
    def SourcesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorDescribeSourcesBatchResult
    def SourcesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PropagatorDescribeSourcesBatchResultStart(builder):
    builder.StartObject(2)

def Start(builder):
    PropagatorDescribeSourcesBatchResultStart(builder)

def PropagatorDescribeSourcesBatchResultAddCatalogHandle(builder, catalogHandle):
    builder.PrependUint32Slot(0, catalogHandle, 0)

def AddCatalogHandle(builder, catalogHandle):
    PropagatorDescribeSourcesBatchResultAddCatalogHandle(builder, catalogHandle)

def PropagatorDescribeSourcesBatchResultAddSources(builder, sources):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sources), 0)

def AddSources(builder, sources):
    PropagatorDescribeSourcesBatchResultAddSources(builder, sources)

def PropagatorDescribeSourcesBatchResultStartSourcesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSourcesVector(builder, numElems):
    return PropagatorDescribeSourcesBatchResultStartSourcesVector(builder, numElems)

def PropagatorDescribeSourcesBatchResultCreateSourcesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateSourcesVector(builder, data):
    PropagatorDescribeSourcesBatchResultCreateSourcesVector(builder, data)

def PropagatorDescribeSourcesBatchResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatorDescribeSourcesBatchResultEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.propagator.PropagatorSourceDescription
try:
    from typing import List
except:
    pass

class PropagatorDescribeSourcesBatchResultT(object):

    # PropagatorDescribeSourcesBatchResultT
    def __init__(
        self,
        catalogHandle = 0,
        sources = None,
    ):
        self.catalogHandle = catalogHandle  # type: int
        self.sources = sources  # type: Optional[List[orbpro.propagator.PropagatorSourceDescription.PropagatorSourceDescriptionT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatorDescribeSourcesBatchResult = PropagatorDescribeSourcesBatchResult()
        propagatorDescribeSourcesBatchResult.Init(buf, pos)
        return cls.InitFromObj(propagatorDescribeSourcesBatchResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatorDescribeSourcesBatchResult):
        x = PropagatorDescribeSourcesBatchResultT()
        x._UnPack(propagatorDescribeSourcesBatchResult)
        return x

    # PropagatorDescribeSourcesBatchResultT
    def _UnPack(self, propagatorDescribeSourcesBatchResult):
        if propagatorDescribeSourcesBatchResult is None:
            return
        self.catalogHandle = propagatorDescribeSourcesBatchResult.CatalogHandle()
        if not propagatorDescribeSourcesBatchResult.SourcesIsNone():
            self.sources = []
            for i in range(propagatorDescribeSourcesBatchResult.SourcesLength()):
                if propagatorDescribeSourcesBatchResult.Sources(i) is None:
                    self.sources.append(None)
                else:
                    propagatorSourceDescription_ = spacedatanetwork_astro.invoke.orbpro.propagator.PropagatorSourceDescription.PropagatorSourceDescriptionT.InitFromObj(propagatorDescribeSourcesBatchResult.Sources(i))
                    self.sources.append(propagatorSourceDescription_)

    # PropagatorDescribeSourcesBatchResultT
    def Pack(self, builder):
        if self.sources is not None:
            sourceslist = []
            for i in range(len(self.sources)):
                sourceslist.append(self.sources[i].Pack(builder))
            PropagatorDescribeSourcesBatchResultStartSourcesVector(builder, len(self.sources))
            for i in reversed(range(len(self.sources))):
                builder.PrependUOffsetTRelative(sourceslist[i])
            sources = builder.EndVector()
        PropagatorDescribeSourcesBatchResultStart(builder)
        PropagatorDescribeSourcesBatchResultAddCatalogHandle(builder, self.catalogHandle)
        if self.sources is not None:
            PropagatorDescribeSourcesBatchResultAddSources(builder, sources)
        propagatorDescribeSourcesBatchResult = PropagatorDescribeSourcesBatchResultEnd(builder)
        return propagatorDescribeSourcesBatchResult
