# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropagatorSourceDescription(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatorSourceDescription()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatorSourceDescription(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropagatorSourceDescription
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropagatorSourceDescription
    def SourceHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def SourceKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def ObjectName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatorSourceDescription
    def ObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatorSourceDescription
    def NoradCatId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def EpochJd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def MeanMotionRevPerDay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def Eccentricity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def InclinationDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def RaOfAscNodeDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def ArgOfPericenterDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def MeanAnomalyDeg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def EphemerisType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def ClassificationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatorSourceDescription
    def ElementSetNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def RevAtEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorSourceDescription
    def Bstar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def MeanMotionDotRevPerDay2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def MeanMotionDdotRevPerDay3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def PerigeeKm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # PropagatorSourceDescription
    def ApogeeKm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def PropagatorSourceDescriptionStart(builder):
    builder.StartObject(21)

def Start(builder):
    PropagatorSourceDescriptionStart(builder)

def PropagatorSourceDescriptionAddSourceHandle(builder, sourceHandle):
    builder.PrependUint32Slot(0, sourceHandle, 0)

def AddSourceHandle(builder, sourceHandle):
    PropagatorSourceDescriptionAddSourceHandle(builder, sourceHandle)

def PropagatorSourceDescriptionAddSourceKind(builder, sourceKind):
    builder.PrependUint8Slot(1, sourceKind, 0)

def AddSourceKind(builder, sourceKind):
    PropagatorSourceDescriptionAddSourceKind(builder, sourceKind)

def PropagatorSourceDescriptionAddObjectName(builder, objectName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(objectName), 0)

def AddObjectName(builder, objectName):
    PropagatorSourceDescriptionAddObjectName(builder, objectName)

def PropagatorSourceDescriptionAddObjectId(builder, objectId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(objectId), 0)

def AddObjectId(builder, objectId):
    PropagatorSourceDescriptionAddObjectId(builder, objectId)

def PropagatorSourceDescriptionAddNoradCatId(builder, noradCatId):
    builder.PrependUint32Slot(4, noradCatId, 0)

def AddNoradCatId(builder, noradCatId):
    PropagatorSourceDescriptionAddNoradCatId(builder, noradCatId)

def PropagatorSourceDescriptionAddEpochJd(builder, epochJd):
    builder.PrependFloat64Slot(5, epochJd, 0.0)

def AddEpochJd(builder, epochJd):
    PropagatorSourceDescriptionAddEpochJd(builder, epochJd)

def PropagatorSourceDescriptionAddMeanMotionRevPerDay(builder, meanMotionRevPerDay):
    builder.PrependFloat64Slot(6, meanMotionRevPerDay, 0.0)

def AddMeanMotionRevPerDay(builder, meanMotionRevPerDay):
    PropagatorSourceDescriptionAddMeanMotionRevPerDay(builder, meanMotionRevPerDay)

def PropagatorSourceDescriptionAddEccentricity(builder, eccentricity):
    builder.PrependFloat64Slot(7, eccentricity, 0.0)

def AddEccentricity(builder, eccentricity):
    PropagatorSourceDescriptionAddEccentricity(builder, eccentricity)

def PropagatorSourceDescriptionAddInclinationDeg(builder, inclinationDeg):
    builder.PrependFloat64Slot(8, inclinationDeg, 0.0)

def AddInclinationDeg(builder, inclinationDeg):
    PropagatorSourceDescriptionAddInclinationDeg(builder, inclinationDeg)

def PropagatorSourceDescriptionAddRaOfAscNodeDeg(builder, raOfAscNodeDeg):
    builder.PrependFloat64Slot(9, raOfAscNodeDeg, 0.0)

def AddRaOfAscNodeDeg(builder, raOfAscNodeDeg):
    PropagatorSourceDescriptionAddRaOfAscNodeDeg(builder, raOfAscNodeDeg)

def PropagatorSourceDescriptionAddArgOfPericenterDeg(builder, argOfPericenterDeg):
    builder.PrependFloat64Slot(10, argOfPericenterDeg, 0.0)

def AddArgOfPericenterDeg(builder, argOfPericenterDeg):
    PropagatorSourceDescriptionAddArgOfPericenterDeg(builder, argOfPericenterDeg)

def PropagatorSourceDescriptionAddMeanAnomalyDeg(builder, meanAnomalyDeg):
    builder.PrependFloat64Slot(11, meanAnomalyDeg, 0.0)

def AddMeanAnomalyDeg(builder, meanAnomalyDeg):
    PropagatorSourceDescriptionAddMeanAnomalyDeg(builder, meanAnomalyDeg)

def PropagatorSourceDescriptionAddEphemerisType(builder, ephemerisType):
    builder.PrependInt32Slot(12, ephemerisType, 0)

def AddEphemerisType(builder, ephemerisType):
    PropagatorSourceDescriptionAddEphemerisType(builder, ephemerisType)

def PropagatorSourceDescriptionAddClassificationType(builder, classificationType):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(classificationType), 0)

def AddClassificationType(builder, classificationType):
    PropagatorSourceDescriptionAddClassificationType(builder, classificationType)

def PropagatorSourceDescriptionAddElementSetNo(builder, elementSetNo):
    builder.PrependUint32Slot(14, elementSetNo, 0)

def AddElementSetNo(builder, elementSetNo):
    PropagatorSourceDescriptionAddElementSetNo(builder, elementSetNo)

def PropagatorSourceDescriptionAddRevAtEpoch(builder, revAtEpoch):
    builder.PrependUint32Slot(15, revAtEpoch, 0)

def AddRevAtEpoch(builder, revAtEpoch):
    PropagatorSourceDescriptionAddRevAtEpoch(builder, revAtEpoch)

def PropagatorSourceDescriptionAddBstar(builder, bstar):
    builder.PrependFloat64Slot(16, bstar, 0.0)

def AddBstar(builder, bstar):
    PropagatorSourceDescriptionAddBstar(builder, bstar)

def PropagatorSourceDescriptionAddMeanMotionDotRevPerDay2(builder, meanMotionDotRevPerDay2):
    builder.PrependFloat64Slot(17, meanMotionDotRevPerDay2, 0.0)

def AddMeanMotionDotRevPerDay2(builder, meanMotionDotRevPerDay2):
    PropagatorSourceDescriptionAddMeanMotionDotRevPerDay2(builder, meanMotionDotRevPerDay2)

def PropagatorSourceDescriptionAddMeanMotionDdotRevPerDay3(builder, meanMotionDdotRevPerDay3):
    builder.PrependFloat64Slot(18, meanMotionDdotRevPerDay3, 0.0)

def AddMeanMotionDdotRevPerDay3(builder, meanMotionDdotRevPerDay3):
    PropagatorSourceDescriptionAddMeanMotionDdotRevPerDay3(builder, meanMotionDdotRevPerDay3)

def PropagatorSourceDescriptionAddPerigeeKm(builder, perigeeKm):
    builder.PrependFloat64Slot(19, perigeeKm, 0.0)

def AddPerigeeKm(builder, perigeeKm):
    PropagatorSourceDescriptionAddPerigeeKm(builder, perigeeKm)

def PropagatorSourceDescriptionAddApogeeKm(builder, apogeeKm):
    builder.PrependFloat64Slot(20, apogeeKm, 0.0)

def AddApogeeKm(builder, apogeeKm):
    PropagatorSourceDescriptionAddApogeeKm(builder, apogeeKm)

def PropagatorSourceDescriptionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatorSourceDescriptionEnd(builder)


class PropagatorSourceDescriptionT(object):

    # PropagatorSourceDescriptionT
    def __init__(
        self,
        sourceHandle = 0,
        sourceKind = 0,
        objectName = None,
        objectId = None,
        noradCatId = 0,
        epochJd = 0.0,
        meanMotionRevPerDay = 0.0,
        eccentricity = 0.0,
        inclinationDeg = 0.0,
        raOfAscNodeDeg = 0.0,
        argOfPericenterDeg = 0.0,
        meanAnomalyDeg = 0.0,
        ephemerisType = 0,
        classificationType = None,
        elementSetNo = 0,
        revAtEpoch = 0,
        bstar = 0.0,
        meanMotionDotRevPerDay2 = 0.0,
        meanMotionDdotRevPerDay3 = 0.0,
        perigeeKm = 0.0,
        apogeeKm = 0.0,
    ):
        self.sourceHandle = sourceHandle  # type: int
        self.sourceKind = sourceKind  # type: int
        self.objectName = objectName  # type: Optional[str]
        self.objectId = objectId  # type: Optional[str]
        self.noradCatId = noradCatId  # type: int
        self.epochJd = epochJd  # type: float
        self.meanMotionRevPerDay = meanMotionRevPerDay  # type: float
        self.eccentricity = eccentricity  # type: float
        self.inclinationDeg = inclinationDeg  # type: float
        self.raOfAscNodeDeg = raOfAscNodeDeg  # type: float
        self.argOfPericenterDeg = argOfPericenterDeg  # type: float
        self.meanAnomalyDeg = meanAnomalyDeg  # type: float
        self.ephemerisType = ephemerisType  # type: int
        self.classificationType = classificationType  # type: Optional[str]
        self.elementSetNo = elementSetNo  # type: int
        self.revAtEpoch = revAtEpoch  # type: int
        self.bstar = bstar  # type: float
        self.meanMotionDotRevPerDay2 = meanMotionDotRevPerDay2  # type: float
        self.meanMotionDdotRevPerDay3 = meanMotionDdotRevPerDay3  # type: float
        self.perigeeKm = perigeeKm  # type: float
        self.apogeeKm = apogeeKm  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatorSourceDescription = PropagatorSourceDescription()
        propagatorSourceDescription.Init(buf, pos)
        return cls.InitFromObj(propagatorSourceDescription)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatorSourceDescription):
        x = PropagatorSourceDescriptionT()
        x._UnPack(propagatorSourceDescription)
        return x

    # PropagatorSourceDescriptionT
    def _UnPack(self, propagatorSourceDescription):
        if propagatorSourceDescription is None:
            return
        self.sourceHandle = propagatorSourceDescription.SourceHandle()
        self.sourceKind = propagatorSourceDescription.SourceKind()
        self.objectName = propagatorSourceDescription.ObjectName()
        self.objectId = propagatorSourceDescription.ObjectId()
        self.noradCatId = propagatorSourceDescription.NoradCatId()
        self.epochJd = propagatorSourceDescription.EpochJd()
        self.meanMotionRevPerDay = propagatorSourceDescription.MeanMotionRevPerDay()
        self.eccentricity = propagatorSourceDescription.Eccentricity()
        self.inclinationDeg = propagatorSourceDescription.InclinationDeg()
        self.raOfAscNodeDeg = propagatorSourceDescription.RaOfAscNodeDeg()
        self.argOfPericenterDeg = propagatorSourceDescription.ArgOfPericenterDeg()
        self.meanAnomalyDeg = propagatorSourceDescription.MeanAnomalyDeg()
        self.ephemerisType = propagatorSourceDescription.EphemerisType()
        self.classificationType = propagatorSourceDescription.ClassificationType()
        self.elementSetNo = propagatorSourceDescription.ElementSetNo()
        self.revAtEpoch = propagatorSourceDescription.RevAtEpoch()
        self.bstar = propagatorSourceDescription.Bstar()
        self.meanMotionDotRevPerDay2 = propagatorSourceDescription.MeanMotionDotRevPerDay2()
        self.meanMotionDdotRevPerDay3 = propagatorSourceDescription.MeanMotionDdotRevPerDay3()
        self.perigeeKm = propagatorSourceDescription.PerigeeKm()
        self.apogeeKm = propagatorSourceDescription.ApogeeKm()

    # PropagatorSourceDescriptionT
    def Pack(self, builder):
        if self.objectName is not None:
            objectName = builder.CreateString(self.objectName)
        if self.objectId is not None:
            objectId = builder.CreateString(self.objectId)
        if self.classificationType is not None:
            classificationType = builder.CreateString(self.classificationType)
        PropagatorSourceDescriptionStart(builder)
        PropagatorSourceDescriptionAddSourceHandle(builder, self.sourceHandle)
        PropagatorSourceDescriptionAddSourceKind(builder, self.sourceKind)
        if self.objectName is not None:
            PropagatorSourceDescriptionAddObjectName(builder, objectName)
        if self.objectId is not None:
            PropagatorSourceDescriptionAddObjectId(builder, objectId)
        PropagatorSourceDescriptionAddNoradCatId(builder, self.noradCatId)
        PropagatorSourceDescriptionAddEpochJd(builder, self.epochJd)
        PropagatorSourceDescriptionAddMeanMotionRevPerDay(builder, self.meanMotionRevPerDay)
        PropagatorSourceDescriptionAddEccentricity(builder, self.eccentricity)
        PropagatorSourceDescriptionAddInclinationDeg(builder, self.inclinationDeg)
        PropagatorSourceDescriptionAddRaOfAscNodeDeg(builder, self.raOfAscNodeDeg)
        PropagatorSourceDescriptionAddArgOfPericenterDeg(builder, self.argOfPericenterDeg)
        PropagatorSourceDescriptionAddMeanAnomalyDeg(builder, self.meanAnomalyDeg)
        PropagatorSourceDescriptionAddEphemerisType(builder, self.ephemerisType)
        if self.classificationType is not None:
            PropagatorSourceDescriptionAddClassificationType(builder, classificationType)
        PropagatorSourceDescriptionAddElementSetNo(builder, self.elementSetNo)
        PropagatorSourceDescriptionAddRevAtEpoch(builder, self.revAtEpoch)
        PropagatorSourceDescriptionAddBstar(builder, self.bstar)
        PropagatorSourceDescriptionAddMeanMotionDotRevPerDay2(builder, self.meanMotionDotRevPerDay2)
        PropagatorSourceDescriptionAddMeanMotionDdotRevPerDay3(builder, self.meanMotionDdotRevPerDay3)
        PropagatorSourceDescriptionAddPerigeeKm(builder, self.perigeeKm)
        PropagatorSourceDescriptionAddApogeeKm(builder, self.apogeeKm)
        propagatorSourceDescription = PropagatorSourceDescriptionEnd(builder)
        return propagatorSourceDescription
