# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropagatorDescribeSourcesBatchRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatorDescribeSourcesBatchRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatorDescribeSourcesBatchRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropagatorDescribeSourcesBatchRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropagatorDescribeSourcesBatchRequest
    def CatalogHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatorDescribeSourcesBatchRequest
    def SourceHandles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PropagatorDescribeSourcesBatchRequest
    def SourceHandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # PropagatorDescribeSourcesBatchRequest
    def SourceHandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatorDescribeSourcesBatchRequest
    def SourceHandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PropagatorDescribeSourcesBatchRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    PropagatorDescribeSourcesBatchRequestStart(builder)

def PropagatorDescribeSourcesBatchRequestAddCatalogHandle(builder, catalogHandle):
    builder.PrependUint32Slot(0, catalogHandle, 0)

def AddCatalogHandle(builder, catalogHandle):
    PropagatorDescribeSourcesBatchRequestAddCatalogHandle(builder, catalogHandle)

def PropagatorDescribeSourcesBatchRequestAddSourceHandles(builder, sourceHandles):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceHandles), 0)

def AddSourceHandles(builder, sourceHandles):
    PropagatorDescribeSourcesBatchRequestAddSourceHandles(builder, sourceHandles)

def PropagatorDescribeSourcesBatchRequestStartSourceHandlesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSourceHandlesVector(builder, numElems):
    return PropagatorDescribeSourcesBatchRequestStartSourceHandlesVector(builder, numElems)

def PropagatorDescribeSourcesBatchRequestCreateSourceHandlesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateSourceHandlesVector(builder, data):
    PropagatorDescribeSourcesBatchRequestCreateSourceHandlesVector(builder, data)

def PropagatorDescribeSourcesBatchRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatorDescribeSourcesBatchRequestEnd(builder)

try:
    from typing import List
except:
    pass

class PropagatorDescribeSourcesBatchRequestT(object):

    # PropagatorDescribeSourcesBatchRequestT
    def __init__(
        self,
        catalogHandle = 0,
        sourceHandles = None,
    ):
        self.catalogHandle = catalogHandle  # type: int
        self.sourceHandles = sourceHandles  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatorDescribeSourcesBatchRequest = PropagatorDescribeSourcesBatchRequest()
        propagatorDescribeSourcesBatchRequest.Init(buf, pos)
        return cls.InitFromObj(propagatorDescribeSourcesBatchRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatorDescribeSourcesBatchRequest):
        x = PropagatorDescribeSourcesBatchRequestT()
        x._UnPack(propagatorDescribeSourcesBatchRequest)
        return x

    # PropagatorDescribeSourcesBatchRequestT
    def _UnPack(self, propagatorDescribeSourcesBatchRequest):
        if propagatorDescribeSourcesBatchRequest is None:
            return
        self.catalogHandle = propagatorDescribeSourcesBatchRequest.CatalogHandle()
        if not propagatorDescribeSourcesBatchRequest.SourceHandlesIsNone():
            if np is None:
                self.sourceHandles = []
                for i in range(propagatorDescribeSourcesBatchRequest.SourceHandlesLength()):
                    self.sourceHandles.append(propagatorDescribeSourcesBatchRequest.SourceHandles(i))
            else:
                self.sourceHandles = propagatorDescribeSourcesBatchRequest.SourceHandlesAsNumpy()

    # PropagatorDescribeSourcesBatchRequestT
    def Pack(self, builder):
        if self.sourceHandles is not None:
            if np is not None and type(self.sourceHandles) is np.ndarray:
                sourceHandles = builder.CreateNumpyVector(self.sourceHandles)
            else:
                PropagatorDescribeSourcesBatchRequestStartSourceHandlesVector(builder, len(self.sourceHandles))
                for i in reversed(range(len(self.sourceHandles))):
                    builder.PrependUint32(self.sourceHandles[i])
                sourceHandles = builder.EndVector()
        PropagatorDescribeSourcesBatchRequestStart(builder)
        PropagatorDescribeSourcesBatchRequestAddCatalogHandle(builder, self.catalogHandle)
        if self.sourceHandles is not None:
            PropagatorDescribeSourcesBatchRequestAddSourceHandles(builder, sourceHandles)
        propagatorDescribeSourcesBatchRequest = PropagatorDescribeSourcesBatchRequestEnd(builder)
        return propagatorDescribeSourcesBatchRequest
