# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

class ReferenceFrame(object):
    TEME = 0
    J2000 = 1
    ICRF = 2
    ECEF = 3
    MCI = 4
    MCMF = 5
    # Mean ecliptic and equinox of J2000. (The mean EQUATOR and equinox of
    # J2000 is J2000 = 1 and is not repeated here.)
    MJ2000EC = 6
    # Mean equator of date.
    MOD = 7
    # True equator of date.
    TOD = 8
    # Mean ecliptic of date.
    MOE = 9
    # True ecliptic of date.
    TOE = 10
    # Axes rotating with a named body, per its published rotation elements.
    BODY_FIXED = 11
    # Non-rotating axes on a named body's equator and prime meridian.
    BODY_INERTIAL = 12
    # Axes built from the relative geometry of two named objects. The three
    # live RTN triads — RIC, RSW and RTN — are THIS member with an axes spec,
    # not three members; so are LVLH and VVLH.
    OBJECT_REFERENCED = 13
    # Axes built by aligning one vector and constraining a second.
    LOCAL_ALIGNED_CONSTRAINED = 14
    # A named body's equatorial plane at the epoch.
    EQUATOR = 15
    # Solar-ecliptic magnetospheric (GSE).
    GSE = 16
    # Solar magnetospheric (GSM).
    GSM = 17
    # Local horizon axes at a surface site.
    TOPOCENTRIC = 18
    # Axes fixed by a body's spin axis and its direction to the Sun.
    BODY_SPIN_SUN = 19
    # Axes declared by a loaded ephemeris/orientation kernel.
    SPICE_DEFINED = 20
    # LEGACY, retained and NAMED rather than left implicit: mean equator of
    # date on the IAU-76/FK5 theory. Differs from MOD at the milliarcsecond
    # level; the two are not interchangeable.
    MOD_FK5 = 21
    # LEGACY, retained and NAMED: true equator of date on IAU-76/FK5.
    TOD_FK5 = 22
