# automatically generated by the FlatBuffers compiler, do not modify

# namespace: propagator

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Orbital state vector — 64 bytes, 8-byte aligned. Mirrors
# `OrbProStateVector` in orbpro-integration/sdk/include/orbpro_propagator.h
# byte for byte:
#
#   0   8   epoch (Julian date, float64)
#   8   24  position (METERS)
#   32  24  velocity (METERS/SECOND)
#   56  1   reference_frame (ubyte)
#   57  3   padding, MUST be zero
#   60  4   flags (uint32)
#
# NORMATIVE UNITS: position METERS, velocity METERS/SECOND. There is no km
# variant and no host-side conversion — the engine hands these straight to
# Cesium Cartesian3, whose unit is metres, and both shipped propagators emit
# meters. The C header used to declare `reference_frame` as a uint32 at
# offset 56, wire-identical to this ubyte+padding only by little-endian
# accident; it now declares ubyte + 3 reserved so the two agree by
# construction.
#
# Ruling: graph/findings/official-harness-shapes.md §4.1 / §4.2
class StateVector(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 64

    # StateVector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Julian date of this state.
    # StateVector
    def Epoch(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Position [x, y, z] in METERS.
    # StateVector
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 8)
        return obj

    # Velocity [vx, vy, vz] in METERS PER SECOND.
    # StateVector
    def Velocity(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 32)
        return obj

    # Reference frame of position/velocity. One byte; the three bytes that
    # follow are alignment padding and MUST be written as zero.
    # StateVector
    def ReferenceFrame(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(56))
    # StateFlags bitfield.
    # StateVector
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(60))

def CreateStateVector(builder, epoch, position_x, position_y, position_z, velocity_x, velocity_y, velocity_z, referenceFrame, flags):
    builder.Prep(8, 64)
    builder.PrependUint32(flags)
    builder.Pad(3)
    builder.PrependUint8(referenceFrame)
    builder.Prep(8, 24)
    builder.PrependFloat64(velocity_z)
    builder.PrependFloat64(velocity_y)
    builder.PrependFloat64(velocity_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(position_z)
    builder.PrependFloat64(position_y)
    builder.PrependFloat64(position_x)
    builder.PrependFloat64(epoch)
    return builder.Offset()

import spacedatanetwork_astro.invoke.orbpro.Vec3
try:
    from typing import Optional
except:
    pass

class StateVectorT(object):

    # StateVectorT
    def __init__(
        self,
        epoch = 0.0,
        position = None,
        velocity = None,
        referenceFrame = 0,
        flags = 0,
    ):
        self.epoch = epoch  # type: float
        self.position = position  # type: Optional[orbpro.Vec3.Vec3T]
        self.velocity = velocity  # type: Optional[orbpro.Vec3.Vec3T]
        self.referenceFrame = referenceFrame  # type: int
        self.flags = flags  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stateVector = StateVector()
        stateVector.Init(buf, pos)
        return cls.InitFromObj(stateVector)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stateVector):
        x = StateVectorT()
        x._UnPack(stateVector)
        return x

    # StateVectorT
    def _UnPack(self, stateVector):
        if stateVector is None:
            return
        self.epoch = stateVector.Epoch()
        if stateVector.Position(spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3()) is not None:
            self.position = spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3T.InitFromObj(stateVector.Position(spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3()))
        if stateVector.Velocity(spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3()) is not None:
            self.velocity = spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3T.InitFromObj(stateVector.Velocity(spacedatanetwork_astro.invoke.orbpro.Vec3.Vec3()))
        self.referenceFrame = stateVector.ReferenceFrame()
        self.flags = stateVector.Flags()

    # StateVectorT
    def Pack(self, builder):
        return CreateStateVector(builder, self.epoch, self.position.x, self.position.y, self.position.z, self.velocity.x, self.velocity.y, self.velocity.z, self.referenceFrame, self.flags)
