import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import {normalizeParityFixture,runParityHarness,formatParityReport} from 'space-data-module-sdk/testing';
import {cases} from './fixtures.mjs';
import {staticDepthCases,nonlinearCases} from './depth-fixtures.mjs';
const allCases=[...cases,...staticDepthCases,...await nonlinearCases()];
const plan=await normalizeParityFixture({name:'TMPL lane05 estimation',threadEnvVar:'SDM_WORKER_COUNT',threadCounts:[1,2,4,8],cases:allCases.map(c=>({...c,request:{...c.request,inputs:c.request.inputs.map(({payload,...p})=>({...p,payloadHex:Buffer.from(payload).toString('hex')}))}}))});
const report=await runParityHarness({wasmPath:fileURLToPath(new URL('../dist/isomorphic/module.wasm',import.meta.url)),plan,timeoutMs:60000,log:console.log});
console.log(formatParityReport(report));
fs.writeFileSync(new URL('../conformance/lane05-parity.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
assert.equal(report.ok,true,JSON.stringify(report.failures));
