#!/usr/bin/env node
// Writes lib/egm96_data.h: EGM96's fully normalized coefficients, degree 2 to
// 70, from a GMAT/STK potential file of NGA's egm96_to360.ascii.
//
//   node scripts/generate-egm96.mjs <EGM96.cof> [check.egm]
//
// Source used: NASA GMAT, application/data/gravity/earth/EGM96.cof
// ("egm96_to360.ascii : [360x360] EGM96 using epoch of 1986", GM
// 3.986004415e14 m^3/s^2, radius 6378136.3 m), from
// https://github.com/nasa/GMAT (Apache-2.0); EGM96 itself is NGA/NASA
// (Lemoine et al. 1998, NASA/TP-1998-206861), tide-free. The optional second
// file, in NGA's own format (n m C S sigmaC sigmaS), is compared coefficient by
// coefficient over the degrees it holds (Orekit's test resource
// potential/egm-format/EGM96-truncated-21x21 was used).
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const [cof, check] = process.argv.slice(2);
if (!cof) throw new Error('usage: generate-egm96.mjs <EGM96.cof> [check.egm]');
const MAX = 70;
const text = fs.readFileSync(cof, 'latin1');
const header = text.match(/^POTFIELD\s*(\d{3})(\d{3})\s+\d+\s+([-+0-9.E]+)\s+([-+0-9.E]+)/m);
if (!header || Number(header[3]) !== 3.986004415e14 || Number(header[4]) !== 6378136.3)
  throw new Error('Expected POTFIELD with GM 3.986004415e14 and radius 6378136.3');
const records = new Map();
for (const line of text.split(/\r?\n/)) {
  if (!line.startsWith('RECOEF')) continue;
  // Fixed columns: RECOEF, n (columns 8-10), m (11-13), then C and S, which
  // may abut ("1.8E-11-3.1E-11"); S is absent for m = 0.
  const n = Number(line.slice(8, 11)), m = Number(line.slice(11, 14));
  const values = line.slice(14).match(/[-+]?\d\.\d+E[-+]\d+/g) ?? [];
  const c = Number(values[0]), s = values.length > 1 ? Number(values[1]) : 0;
  if (values.length < 1 || values.length > 2) throw new Error(`Bad record: ${line}`);
  if (!Number.isFinite(n) || !Number.isFinite(m) || !Number.isFinite(c) || !Number.isFinite(s)) throw new Error(`Bad record: ${line}`);
  records.set(`${n},${m}`, { n, m, c, s });
}
const rows = [];
for (let n = 2; n <= MAX; ++n) for (let m = 0; m <= n; ++m) {
  const r = records.get(`${n},${m}`);
  if (!r) throw new Error(`Missing ${n},${m}`);
  rows.push(r);
}
if (check) {
  let compared = 0;
  for (const line of fs.readFileSync(check, 'utf8').split(/\r?\n/)) {
    const t = line.trim().split(/\s+/);
    if (t.length < 4) continue;
    const n = Number(t[0]), m = Number(t[1]);
    if (n < 2 || n > MAX) continue;
    const r = records.get(`${n},${m}`);
    const c = Number(t[2].replace(/[dD]/, 'e')), s = Number(t[3].replace(/[dD]/, 'e'));
    if (!r || r.c !== c || r.s !== s) throw new Error(`Mismatch at ${n},${m}: ${r?.c} ${r?.s} vs ${c} ${s}`);
    ++compared;
  }
  console.log(`matched ${compared} coefficients of ${path.basename(check)} exactly`);
}
const sha = crypto.createHash('sha256').update(fs.readFileSync(cof)).digest('hex');
const fmt = (x) => x.toExponential(14);
const out = `// egm96_data.h - EGM96 fully normalized Stokes coefficients
// =============================================================================
// Generated by scripts/generate-egm96.mjs - DO NOT EDIT MANUALLY
//
// Model: EGM96 (Lemoine et al. 1998, NASA/TP-1998-206861), NGA/NASA,
// egm96_to360.ascii (coefficients at epoch 1986, tide-free), GM
// 3.986004415e14 m^3/s^2, reference radius 6378136.3 m.
// Read from NASA GMAT application/data/gravity/earth/EGM96.cof
// (https://github.com/nasa/GMAT, sha256 ${sha}).
// Truncation: degree/order ${MAX}
// Total coefficients: ${rows.length}
// =============================================================================

#ifndef ORBPRO2_EGM96_DATA_H
#define ORBPRO2_EGM96_DATA_H

namespace astro {
namespace EGM96Data {

/// Maximum degree available in embedded data
static constexpr int MAX_EMBEDDED_DEGREE = ${MAX};

/// Total number of coefficient records
static constexpr int NUM_COEFFICIENTS = ${rows.length};

/// Coefficient record: {degree, order, Cnm, Snm}
struct CoeffRecord {
    int n;
    int m;
    double Cnm;
    double Snm;
};

/// EGM96 fully normalized Stokes coefficients, degree 2 to ${MAX}
static constexpr CoeffRecord COEFFICIENTS[${rows.length}] = {
${rows.map((r) => `    {${String(r.n).padStart(2)}, ${String(r.m).padStart(2)}, ${fmt(r.c).padStart(22)}, ${fmt(r.s).padStart(22)}},`).join('\n')}
};

} // namespace EGM96Data
} // namespace astro

#endif // ORBPRO2_EGM96_DATA_H
`;
const here = path.dirname(fileURLToPath(import.meta.url));
fs.writeFileSync(path.resolve(here, '../lib/egm96_data.h'), out);
console.log(`wrote ${rows.length} records to lib/egm96_data.h`);
