#!/usr/bin/env node
// Writes lib/fes2004_data.h: the FES2004 ocean tide waves of IERS
// Conventions (2010) section 6.3 as the IERS distributes them
// (fes2004_Cnm-Snm.dat, normalized Stokes coefficient variations, unit
// 1e-11), to degree and order 50, in file order.
//
//   node scripts/generate-fes2004.mjs <fes2004_Cnm-Snm.dat>
// Source: https://iers-conventions.obspm.fr/content/chapter6/additional_info/tidemodels/fes2004_Cnm-Snm.dat
// (SHA-256 620dc48fd4d97baa14f532287b19788bd55dc2056e0b478ab0f928b951c194cf,
// identical to the copy in Orekit's data directory).
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const MAX_DEGREE = 50;
const SHA256 = '620dc48fd4d97baa14f532287b19788bd55dc2056e0b478ab0f928b951c194cf';
const [file] = process.argv.slice(2);
if (!file) throw new Error('usage: generate-fes2004.mjs <fes2004_Cnm-Snm.dat>');
const raw = fs.readFileSync(file);
const sha = crypto.createHash('sha256').update(raw).digest('hex');
if (sha !== SHA256) throw new Error(`fes2004_Cnm-Snm.dat has SHA-256 ${sha}, expected ${SHA256}`);
// "Doodson Darw l m DelC+ DelS+ DelC- DelS-": the same line pattern Orekit's
// FESCnmSnmReader accepts.
const line = /^\s*(\d{2,3}[.,]\d{3})\s+(\S+)\s+([-+]?\d+)\s+([-+]?\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s*$/;
const waves = new Map();
for (const text of raw.toString('latin1').split(/\r?\n/)) {
  const m = line.exec(text);
  if (!m) continue;
  const doodson = Number(m[1].replace(/[.,]/, '')), n = Number(m[3]), order = Number(m[4]);
  if (n > MAX_DEGREE || order > MAX_DEGREE || n < 2) continue;  // Orekit sums from degree 2
  if (!waves.has(doodson)) waves.set(doodson, { doodson, name: m[2], rows: [] });
  const values = m.slice(5, 9);
  if (values.every((v) => Number(v) === 0)) continue;
  waves.get(doodson).rows.push(`{${n}, ${order}, ${values.map((v) => `${v}f`).join(', ')}}`);
}
const out = [
  '// Generated by scripts/generate-fes2004.mjs; do not edit.',
  '// FES2004 ocean tide model, IERS Conventions (2010) section 6.3: variations of the',
  '// fully normalized Stokes coefficients, unit 1e-11, columns DelC+ DelS+ DelC- DelS-',
  `// (eq. 6.15), degrees 2 to ${MAX_DEGREE}. Source: the IERS file fes2004_Cnm-Snm.dat,`,
  `// SHA-256 ${SHA256}.`,
  '#pragma once',
  '',
  'namespace astro { namespace ForceModel { namespace fes2004 {',
  '',
  '// Coefficients as printed (5 decimals, at most 7 significant digits), stored as float:',
  '// the storage rounding is below 6e-8 of a coefficient, under 1e-18 in the field.',
  'struct Row { short n, m; float cPlus, sPlus, cMinus, sMinus; };',
  'struct Wave { int doodson; const char* darwin; const Row* rows; int count; };',
  `constexpr int MAX_DEGREE = ${MAX_DEGREE};`,
  'constexpr double UNIT = 1e-11;',
  '',
];
for (const w of waves.values()) {
  out.push(`constexpr Row W${w.doodson}[] = {`, ...w.rows.map((r) => `  ${r},`), '};');
}
out.push('', 'constexpr Wave WAVES[] = {',
  ...[...waves.values()].map((w) => `  {${w.doodson}, ${JSON.stringify(w.name)}, W${w.doodson}, ${w.rows.length}},`), '};',
  `constexpr int WAVE_COUNT = ${waves.size};`, '', '}}}  // namespace astro::ForceModel::fes2004', '');
const target = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../lib/fes2004_data.h');
fs.writeFileSync(target, out.join('\n'));
console.log(`wrote ${target}: ${waves.size} waves, ${[...waves.values()].reduce((a, w) => a + w.rows.length, 0)} rows`);
