// Auto-generated aligned fixed-layout bindings.
// DO NOT EDIT - Generated by flatc --aligned

#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>

namespace flatbuffers {
namespace aligned_runtime {

template <size_t MaxLength>
struct AlignedString {
  uint8_t length;
  char data[MaxLength];

  void clear() {
    length = 0;
    std::memset(data, 0, MaxLength);
  }

  std::string str() const {
    const size_t size = std::min<size_t>(length, MaxLength);
    return std::string(data, data + size);
  }

  void set(const std::string& value) {
    const size_t size = std::min<size_t>(value.size(), MaxLength);
    length = static_cast<uint8_t>(size);
    if (size) { std::memcpy(data, value.data(), size); }
    if (size < MaxLength) { std::memset(data + size, 0, MaxLength - size); }
  }
};

template <typename T, size_t MaxCount>
struct AlignedVector {
  uint32_t length;
  T values[MaxCount];

  uint32_t size() const {
    return std::min<uint32_t>(length, static_cast<uint32_t>(MaxCount));
  }

  void clear() { length = 0; }
  void set_length(uint32_t value) {
    length = std::min<uint32_t>(value, static_cast<uint32_t>(MaxCount));
  }
  T &at(size_t index) { return values[index]; }
  const T &at(size_t index) const { return values[index]; }
};

}  // namespace aligned_runtime
}  // namespace flatbuffers

namespace Aligned {

struct FTB {
  uint8_t __presence[1];
  ::flatbuffers::aligned_runtime::AlignedString<4> FILE_IDENTIFIER;
  ::flatbuffers::aligned_runtime::AlignedString<128> TABLE_NAME;

  bool has_FILE_IDENTIFIER() const {
    return (__presence[0] & 1) != 0;
  }
  void set_has_FILE_IDENTIFIER(bool value) {
    if (value) __presence[0] |= 1;
    else __presence[0] &= ~1;
  }
  bool has_TABLE_NAME() const {
    return (__presence[0] & 2) != 0;
  }
  void set_has_TABLE_NAME(bool value) {
    if (value) __presence[0] |= 2;
    else __presence[0] &= ~2;
  }

  static FTB* fromBytes(void* data) {
    return reinterpret_cast<FTB*>(data);
  }
  static const FTB* fromBytes(const void* data) {
    return reinterpret_cast<const FTB*>(data);
  }
  void copyTo(void* dest) const { std::memcpy(dest, this, 135); }
  void copyFrom(const FTB& src) { std::memcpy(this, &src, 135); }
};
static_assert(sizeof(FTB) == 135, "FTB size mismatch");
static_assert(alignof(FTB) == 1, "FTB alignment mismatch");
static_assert(offsetof(FTB, FILE_IDENTIFIER) == 1, "FTB.FILE_IDENTIFIER offset mismatch");
static_assert(offsetof(FTB, TABLE_NAME) == 6, "FTB.TABLE_NAME offset mismatch");
constexpr size_t FTB_SIZE = 135;
constexpr size_t FTB_ALIGN = 1;

}  // namespace Aligned

namespace Aligned {

struct FSO {
  uint8_t __presence[2];
  flatSqlNodeOperation OPERATION;
  uint64_t REQUEST_ID;
  ::flatbuffers::aligned_runtime::AlignedString<128> DATABASE_NAME;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 262144> SCHEMA_IDL;
  ::flatbuffers::aligned_runtime::AlignedVector<::Aligned::FTB, 64> TABLE_BINDINGS;
  ::flatbuffers::aligned_runtime::AlignedString<128> TABLE_NAME;
  ::flatbuffers::aligned_runtime::AlignedString<128> INDEX_NAME;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 2048> INDEX_EXPRESSION;
  ::flatbuffers::aligned_runtime::AlignedString<128> VIEW_NAME;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 16384> QUERY;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 65536> PARAMETERS;
  uint32_t PARAMETER_COUNT;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 2048> UPSERT_KEY_EXPRESSION;
  uint64_t RETENTION_MAX_RECORDS;
  uint64_t RETENTION_MAX_AGE_MILLIS;
  uint64_t COMPACTION_TARGET_BYTES;
  flatSqlNodeStatus STATUS;
  uint64_t AFFECTED_RECORDS;
  uint64_t RESULT_BYTES;
  ::flatbuffers::aligned_runtime::AlignedString<128> ERROR_CODE;
  ::flatbuffers::aligned_runtime::AlignedVector<uint8_t, 4096> MESSAGE;

  bool has_DATABASE_NAME() const {
    return (__presence[0] & 1) != 0;
  }
  void set_has_DATABASE_NAME(bool value) {
    if (value) __presence[0] |= 1;
    else __presence[0] &= ~1;
  }
  bool has_SCHEMA_IDL() const {
    return (__presence[0] & 2) != 0;
  }
  void set_has_SCHEMA_IDL(bool value) {
    if (value) __presence[0] |= 2;
    else __presence[0] &= ~2;
  }
  bool has_TABLE_BINDINGS() const {
    return (__presence[0] & 4) != 0;
  }
  void set_has_TABLE_BINDINGS(bool value) {
    if (value) __presence[0] |= 4;
    else __presence[0] &= ~4;
  }
  bool has_TABLE_NAME() const {
    return (__presence[0] & 8) != 0;
  }
  void set_has_TABLE_NAME(bool value) {
    if (value) __presence[0] |= 8;
    else __presence[0] &= ~8;
  }
  bool has_INDEX_NAME() const {
    return (__presence[0] & 16) != 0;
  }
  void set_has_INDEX_NAME(bool value) {
    if (value) __presence[0] |= 16;
    else __presence[0] &= ~16;
  }
  bool has_INDEX_EXPRESSION() const {
    return (__presence[0] & 32) != 0;
  }
  void set_has_INDEX_EXPRESSION(bool value) {
    if (value) __presence[0] |= 32;
    else __presence[0] &= ~32;
  }
  bool has_VIEW_NAME() const {
    return (__presence[0] & 64) != 0;
  }
  void set_has_VIEW_NAME(bool value) {
    if (value) __presence[0] |= 64;
    else __presence[0] &= ~64;
  }
  bool has_QUERY() const {
    return (__presence[0] & 128) != 0;
  }
  void set_has_QUERY(bool value) {
    if (value) __presence[0] |= 128;
    else __presence[0] &= ~128;
  }
  bool has_PARAMETERS() const {
    return (__presence[1] & 1) != 0;
  }
  void set_has_PARAMETERS(bool value) {
    if (value) __presence[1] |= 1;
    else __presence[1] &= ~1;
  }
  bool has_UPSERT_KEY_EXPRESSION() const {
    return (__presence[1] & 2) != 0;
  }
  void set_has_UPSERT_KEY_EXPRESSION(bool value) {
    if (value) __presence[1] |= 2;
    else __presence[1] &= ~2;
  }
  bool has_ERROR_CODE() const {
    return (__presence[1] & 4) != 0;
  }
  void set_has_ERROR_CODE(bool value) {
    if (value) __presence[1] |= 4;
    else __presence[1] &= ~4;
  }
  bool has_MESSAGE() const {
    return (__presence[1] & 8) != 0;
  }
  void set_has_MESSAGE(bool value) {
    if (value) __presence[1] |= 8;
    else __presence[1] &= ~8;
  }

  static FSO* fromBytes(void* data) {
    return reinterpret_cast<FSO*>(data);
  }
  static const FSO* fromBytes(const void* data) {
    return reinterpret_cast<const FSO*>(data);
  }
  void copyTo(void* dest) const { std::memcpy(dest, this, 361648); }
  void copyFrom(const FSO& src) { std::memcpy(this, &src, 361648); }
};
static_assert(sizeof(FSO) == 361648, "FSO size mismatch");
static_assert(alignof(FSO) == 8, "FSO alignment mismatch");
static_assert(offsetof(FSO, OPERATION) == 2, "FSO.OPERATION offset mismatch");
static_assert(offsetof(FSO, REQUEST_ID) == 8, "FSO.REQUEST_ID offset mismatch");
static_assert(offsetof(FSO, DATABASE_NAME) == 16, "FSO.DATABASE_NAME offset mismatch");
static_assert(offsetof(FSO, SCHEMA_IDL) == 148, "FSO.SCHEMA_IDL offset mismatch");
static_assert(offsetof(FSO, TABLE_BINDINGS) == 262296, "FSO.TABLE_BINDINGS offset mismatch");
static_assert(offsetof(FSO, TABLE_NAME) == 270940, "FSO.TABLE_NAME offset mismatch");
static_assert(offsetof(FSO, INDEX_NAME) == 271069, "FSO.INDEX_NAME offset mismatch");
static_assert(offsetof(FSO, INDEX_EXPRESSION) == 271200, "FSO.INDEX_EXPRESSION offset mismatch");
static_assert(offsetof(FSO, VIEW_NAME) == 273252, "FSO.VIEW_NAME offset mismatch");
static_assert(offsetof(FSO, QUERY) == 273384, "FSO.QUERY offset mismatch");
static_assert(offsetof(FSO, PARAMETERS) == 289772, "FSO.PARAMETERS offset mismatch");
static_assert(offsetof(FSO, PARAMETER_COUNT) == 355312, "FSO.PARAMETER_COUNT offset mismatch");
static_assert(offsetof(FSO, UPSERT_KEY_EXPRESSION) == 355316, "FSO.UPSERT_KEY_EXPRESSION offset mismatch");
static_assert(offsetof(FSO, RETENTION_MAX_RECORDS) == 357368, "FSO.RETENTION_MAX_RECORDS offset mismatch");
static_assert(offsetof(FSO, RETENTION_MAX_AGE_MILLIS) == 357376, "FSO.RETENTION_MAX_AGE_MILLIS offset mismatch");
static_assert(offsetof(FSO, COMPACTION_TARGET_BYTES) == 357384, "FSO.COMPACTION_TARGET_BYTES offset mismatch");
static_assert(offsetof(FSO, STATUS) == 357392, "FSO.STATUS offset mismatch");
static_assert(offsetof(FSO, AFFECTED_RECORDS) == 357400, "FSO.AFFECTED_RECORDS offset mismatch");
static_assert(offsetof(FSO, RESULT_BYTES) == 357408, "FSO.RESULT_BYTES offset mismatch");
static_assert(offsetof(FSO, ERROR_CODE) == 357416, "FSO.ERROR_CODE offset mismatch");
static_assert(offsetof(FSO, MESSAGE) == 357548, "FSO.MESSAGE offset mismatch");
constexpr size_t FSO_SIZE = 361648;
constexpr size_t FSO_ALIGN = 8;

}  // namespace Aligned

