// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TESTSCHEMA_TEST_H_
#define FLATBUFFERS_GENERATED_TESTSCHEMA_TEST_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace test {

struct User;
struct UserBuilder;

struct Post;
struct PostBuilder;

struct User FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_EMAIL = 8,
    VT_AGE = 10
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *email() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EMAIL);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_EMAIL) &&
           verifier.VerifyString(email()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           verifier.EndTable();
  }
};

struct UserBuilder {
  typedef User Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(User::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(User::VT_NAME, name);
  }
  void add_email(::flatbuffers::Offset<::flatbuffers::String> email) {
    fbb_.AddOffset(User::VT_EMAIL, email);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(User::VT_AGE, age, 0);
  }
  explicit UserBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<User> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<User>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<User> CreateUser(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> email = 0,
    int32_t age = 0) {
  UserBuilder builder_(_fbb);
  builder_.add_age(age);
  builder_.add_email(email);
  builder_.add_name(name);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<User> CreateUserDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    const char *name = nullptr,
    const char *email = nullptr,
    int32_t age = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto email__ = email ? _fbb.CreateString(email) : 0;
  return test::CreateUser(
      _fbb,
      id,
      name__,
      email__,
      age);
}

struct Post FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PostBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_USER_ID = 6,
    VT_TITLE = 8,
    VT_CONTENT = 10
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t user_id() const {
    return GetField<int32_t>(VT_USER_ID, 0);
  }
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *content() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_USER_ID, 4) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           verifier.EndTable();
  }
};

struct PostBuilder {
  typedef Post Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Post::VT_ID, id, 0);
  }
  void add_user_id(int32_t user_id) {
    fbb_.AddElement<int32_t>(Post::VT_USER_ID, user_id, 0);
  }
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(Post::VT_TITLE, title);
  }
  void add_content(::flatbuffers::Offset<::flatbuffers::String> content) {
    fbb_.AddOffset(Post::VT_CONTENT, content);
  }
  explicit PostBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Post> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Post>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Post> CreatePost(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t user_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content = 0) {
  PostBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_title(title);
  builder_.add_user_id(user_id);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Post> CreatePostDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t user_id = 0,
    const char *title = nullptr,
    const char *content = nullptr) {
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return test::CreatePost(
      _fbb,
      id,
      user_id,
      title__,
      content__);
}

inline const test::User *GetUser(const void *buf) {
  return ::flatbuffers::GetRoot<test::User>(buf);
}

inline const test::User *GetSizePrefixedUser(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<test::User>(buf);
}

template <bool B = false>
inline bool VerifyUserBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<test::User>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedUserBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<test::User>(nullptr);
}

inline void FinishUserBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<test::User> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUserBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<test::User> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace test

#endif  // FLATBUFFERS_GENERATED_TESTSCHEMA_TEST_H_
