# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Boolean packed into single byte (1 byte)
class Bool8(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 1

    # Bool8
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bool8
    def Value(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateBool8(builder, value):
    builder.Prep(1, 1)
    builder.PrependUint8(value)
    return builder.Offset()


class Bool8T(object):

    # Bool8T
    def __init__(
        self,
        value = 0,
    ):
        self.value = value  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bool8 = Bool8()
        bool8.Init(buf, pos)
        return cls.InitFromObj(bool8)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bool8):
        x = Bool8T()
        x._UnPack(bool8)
        return x

    # Bool8T
    def _UnPack(self, bool8):
        if bool8 is None:
            return
        self.value = bool8.Value()

    # Bool8T
    def Pack(self, builder):
        return CreateBool8(builder, self.value)
