# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Boolean with padding for alignment (4 bytes)
# Use for single boolean values in structs
class Bool32(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # Bool32
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bool32
    def Value(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateBool32(builder, value):
    builder.Prep(4, 4)
    builder.PrependUint32(value)
    return builder.Offset()


class Bool32T(object):

    # Bool32T
    def __init__(
        self,
        value = 0,
    ):
        self.value = value  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bool32 = Bool32()
        bool32.Init(buf, pos)
        return cls.InitFromObj(bool32)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bool32):
        x = Bool32T()
        x._UnPack(bool32)
        return x

    # Bool32T
    def _UnPack(self, bool32):
        if bool32 is None:
            return
        self.value = bool32.Value()

    # Bool32T
    def Pack(self, builder):
        return CreateBool32(builder, self.value)
