# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Bounding sphere (32 bytes)
class BoundingSphere(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # BoundingSphere
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoundingSphere
    def Center(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # BoundingSphere
    def Radius(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateBoundingSphere(builder, center_x, center_y, center_z, radius):
    builder.Prep(8, 32)
    builder.PrependFloat64(radius)
    builder.Prep(8, 24)
    builder.PrependFloat64(center_z)
    builder.PrependFloat64(center_y)
    builder.PrependFloat64(center_x)
    return builder.Offset()

import spacedatanetwork_astro.invoke.legacy.orbpro.Vec3
try:
    from typing import Optional
except:
    pass

class BoundingSphereT(object):

    # BoundingSphereT
    def __init__(
        self,
        center = None,
        radius = 0.0,
    ):
        self.center = center  # type: Optional[orbpro.Vec3.Vec3T]
        self.radius = radius  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        boundingSphere = BoundingSphere()
        boundingSphere.Init(buf, pos)
        return cls.InitFromObj(boundingSphere)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, boundingSphere):
        x = BoundingSphereT()
        x._UnPack(boundingSphere)
        return x

    # BoundingSphereT
    def _UnPack(self, boundingSphere):
        if boundingSphere is None:
            return
        if boundingSphere.Center(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()) is not None:
            self.center = spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3T.InitFromObj(boundingSphere.Center(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()))
        self.radius = boundingSphere.Radius()

    # BoundingSphereT
    def Pack(self, builder):
        return CreateBoundingSphere(builder, self.center.x, self.center.y, self.center.z, self.radius)
