# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Cesium Cartesian4 (32 bytes) - alias for Vec4
class Cartesian4(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # Cartesian4
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cartesian4
    def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Cartesian4
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Cartesian4
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Cartesian4
    def W(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateCartesian4(builder, x, y, z, w):
    builder.Prep(8, 32)
    builder.PrependFloat64(w)
    builder.PrependFloat64(z)
    builder.PrependFloat64(y)
    builder.PrependFloat64(x)
    return builder.Offset()


class Cartesian4T(object):

    # Cartesian4T
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        z = 0.0,
        w = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.z = z  # type: float
        self.w = w  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cartesian4 = Cartesian4()
        cartesian4.Init(buf, pos)
        return cls.InitFromObj(cartesian4)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cartesian4):
        x = Cartesian4T()
        x._UnPack(cartesian4)
        return x

    # Cartesian4T
    def _UnPack(self, cartesian4):
        if cartesian4 is None:
            return
        self.x = cartesian4.X()
        self.y = cartesian4.Y()
        self.z = cartesian4.Z()
        self.w = cartesian4.W()

    # Cartesian4T
    def Pack(self, builder):
        return CreateCartesian4(builder, self.x, self.y, self.z, self.w)
