# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Cesium Cartesian3 single precision (12 bytes)
class Cartesian3f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # Cartesian3f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cartesian3f
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Cartesian3f
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Cartesian3f
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateCartesian3f(builder, x, y, z):
    builder.Prep(4, 12)
    builder.PrependFloat32(z)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class Cartesian3fT(object):

    # Cartesian3fT
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.z = z  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cartesian3f = Cartesian3f()
        cartesian3f.Init(buf, pos)
        return cls.InitFromObj(cartesian3f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cartesian3f):
        x = Cartesian3fT()
        x._UnPack(cartesian3f)
        return x

    # Cartesian3fT
    def _UnPack(self, cartesian3f):
        if cartesian3f is None:
            return
        self.x = cartesian3f.X()
        self.y = cartesian3f.Y()
        self.z = cartesian3f.Z()

    # Cartesian3fT
    def Pack(self, builder):
        return CreateCartesian3f(builder, self.x, self.y, self.z)
