# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Cesium Cartesian3 (24 bytes) - alias for Vec3
class Cartesian3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # Cartesian3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cartesian3
    def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Cartesian3
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Cartesian3
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateCartesian3(builder, x, y, z):
    builder.Prep(8, 24)
    builder.PrependFloat64(z)
    builder.PrependFloat64(y)
    builder.PrependFloat64(x)
    return builder.Offset()


class Cartesian3T(object):

    # Cartesian3T
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.z = z  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cartesian3 = Cartesian3()
        cartesian3.Init(buf, pos)
        return cls.InitFromObj(cartesian3)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cartesian3):
        x = Cartesian3T()
        x._UnPack(cartesian3)
        return x

    # Cartesian3T
    def _UnPack(self, cartesian3):
        if cartesian3 is None:
            return
        self.x = cartesian3.X()
        self.y = cartesian3.Y()
        self.z = cartesian3.Z()

    # Cartesian3T
    def Pack(self, builder):
        return CreateCartesian3(builder, self.x, self.y, self.z)
