# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# RGBA color, float per channel (16 bytes)
class Colorf(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Colorf
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Colorf
    def R(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Colorf
    def G(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Colorf
    def B(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Colorf
    def A(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateColorf(builder, r, g, b, a):
    builder.Prep(4, 16)
    builder.PrependFloat32(a)
    builder.PrependFloat32(b)
    builder.PrependFloat32(g)
    builder.PrependFloat32(r)
    return builder.Offset()


class ColorfT(object):

    # ColorfT
    def __init__(
        self,
        r = 0.0,
        g = 0.0,
        b = 0.0,
        a = 0.0,
    ):
        self.r = r  # type: float
        self.g = g  # type: float
        self.b = b  # type: float
        self.a = a  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        colorf = Colorf()
        colorf.Init(buf, pos)
        return cls.InitFromObj(colorf)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, colorf):
        x = ColorfT()
        x._UnPack(colorf)
        return x

    # ColorfT
    def _UnPack(self, colorf):
        if colorf is None:
            return
        self.r = colorf.R()
        self.g = colorf.G()
        self.b = colorf.B()
        self.a = colorf.A()

    # ColorfT
    def Pack(self, builder):
        return CreateColorf(builder, self.r, self.g, self.b, self.a)
