# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Encoded Cartesian3 for GPU (24 bytes)
# High/low precision split for RTE (Relative To Eye) rendering
# Cesium equivalent: EncodedCartesian3
class EncodedVec3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # EncodedVec3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EncodedVec3
    def HighX(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EncodedVec3
    def HighY(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # EncodedVec3
    def HighZ(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EncodedVec3
    def LowX(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # EncodedVec3
    def LowY(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # EncodedVec3
    def LowZ(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateEncodedVec3(builder, highX, highY, highZ, lowX, lowY, lowZ):
    builder.Prep(4, 24)
    builder.PrependFloat32(lowZ)
    builder.PrependFloat32(lowY)
    builder.PrependFloat32(lowX)
    builder.PrependFloat32(highZ)
    builder.PrependFloat32(highY)
    builder.PrependFloat32(highX)
    return builder.Offset()


class EncodedVec3T(object):

    # EncodedVec3T
    def __init__(
        self,
        highX = 0.0,
        highY = 0.0,
        highZ = 0.0,
        lowX = 0.0,
        lowY = 0.0,
        lowZ = 0.0,
    ):
        self.highX = highX  # type: float
        self.highY = highY  # type: float
        self.highZ = highZ  # type: float
        self.lowX = lowX  # type: float
        self.lowY = lowY  # type: float
        self.lowZ = lowZ  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        encodedVec3 = EncodedVec3()
        encodedVec3.Init(buf, pos)
        return cls.InitFromObj(encodedVec3)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, encodedVec3):
        x = EncodedVec3T()
        x._UnPack(encodedVec3)
        return x

    # EncodedVec3T
    def _UnPack(self, encodedVec3):
        if encodedVec3 is None:
            return
        self.highX = encodedVec3.HighX()
        self.highY = encodedVec3.HighY()
        self.highZ = encodedVec3.HighZ()
        self.lowX = encodedVec3.LowX()
        self.lowY = encodedVec3.LowY()
        self.lowZ = encodedVec3.LowZ()

    # EncodedVec3T
    def Pack(self, builder):
        return CreateEncodedVec3(builder, self.highX, self.highY, self.highZ, self.lowX, self.lowY, self.lowZ)
