# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Entity ID with generation counter for ABA problem prevention (8 bytes)
class EntityId(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # EntityId
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntityId
    def Index(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EntityId
    def Generation(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateEntityId(builder, index, generation):
    builder.Prep(4, 8)
    builder.PrependUint32(generation)
    builder.PrependUint32(index)
    return builder.Offset()


class EntityIdT(object):

    # EntityIdT
    def __init__(
        self,
        index = 0,
        generation = 0,
    ):
        self.index = index  # type: int
        self.generation = generation  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        entityId = EntityId()
        entityId.Init(buf, pos)
        return cls.InitFromObj(entityId)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, entityId):
        x = EntityIdT()
        x._UnPack(entityId)
        return x

    # EntityIdT
    def _UnPack(self, entityId):
        if entityId is None:
            return
        self.index = entityId.Index()
        self.generation = entityId.Generation()

    # EntityIdT
    def Pack(self, builder):
        return CreateEntityId(builder, self.index, self.generation)
