# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Entity handle for WASM registry (4 bytes)
class EntityHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # EntityHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EntityHandle
    def Value(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateEntityHandle(builder, value):
    builder.Prep(4, 4)
    builder.PrependUint32(value)
    return builder.Offset()


class EntityHandleT(object):

    # EntityHandleT
    def __init__(
        self,
        value = 0,
    ):
        self.value = value  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        entityHandle = EntityHandle()
        entityHandle.Init(buf, pos)
        return cls.InitFromObj(entityHandle)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, entityHandle):
        x = EntityHandleT()
        x._UnPack(entityHandle)
        return x

    # EntityHandleT
    def _UnPack(self, entityHandle):
        if entityHandle is None:
            return
        self.value = entityHandle.Value()

    # EntityHandleT
    def Pack(self, builder):
        return CreateEntityHandle(builder, self.value)
