# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Heading, Pitch, Roll rotation (24 bytes)
# Cesium equivalent: HeadingPitchRoll
# All values in radians
class HeadingPitchRoll(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # HeadingPitchRoll
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HeadingPitchRoll
    def Heading(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # HeadingPitchRoll
    def Pitch(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # HeadingPitchRoll
    def Roll(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateHeadingPitchRoll(builder, heading, pitch, roll):
    builder.Prep(8, 24)
    builder.PrependFloat64(roll)
    builder.PrependFloat64(pitch)
    builder.PrependFloat64(heading)
    return builder.Offset()


class HeadingPitchRollT(object):

    # HeadingPitchRollT
    def __init__(
        self,
        heading = 0.0,
        pitch = 0.0,
        roll = 0.0,
    ):
        self.heading = heading  # type: float
        self.pitch = pitch  # type: float
        self.roll = roll  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        headingPitchRoll = HeadingPitchRoll()
        headingPitchRoll.Init(buf, pos)
        return cls.InitFromObj(headingPitchRoll)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, headingPitchRoll):
        x = HeadingPitchRollT()
        x._UnPack(headingPitchRoll)
        return x

    # HeadingPitchRollT
    def _UnPack(self, headingPitchRoll):
        if headingPitchRoll is None:
            return
        self.heading = headingPitchRoll.Heading()
        self.pitch = headingPitchRoll.Pitch()
        self.roll = headingPitchRoll.Roll()

    # HeadingPitchRollT
    def Pack(self, builder):
        return CreateHeadingPitchRoll(builder, self.heading, self.pitch, self.roll)
