# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# 3x3 matrix, column-major (72 bytes)
class Matrix3(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 72

    # Matrix3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Matrix3
    def Col0(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Matrix3
    def Col1(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # Matrix3
    def Col2(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 48)
        return obj


def CreateMatrix3(builder, col0_x, col0_y, col0_z, col1_x, col1_y, col1_z, col2_x, col2_y, col2_z):
    builder.Prep(8, 72)
    builder.Prep(8, 24)
    builder.PrependFloat64(col2_z)
    builder.PrependFloat64(col2_y)
    builder.PrependFloat64(col2_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(col1_z)
    builder.PrependFloat64(col1_y)
    builder.PrependFloat64(col1_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(col0_z)
    builder.PrependFloat64(col0_y)
    builder.PrependFloat64(col0_x)
    return builder.Offset()

import spacedatanetwork_astro.invoke.legacy.orbpro.Vec3
try:
    from typing import Optional
except:
    pass

class Matrix3T(object):

    # Matrix3T
    def __init__(
        self,
        col0 = None,
        col1 = None,
        col2 = None,
    ):
        self.col0 = col0  # type: Optional[orbpro.Vec3.Vec3T]
        self.col1 = col1  # type: Optional[orbpro.Vec3.Vec3T]
        self.col2 = col2  # type: Optional[orbpro.Vec3.Vec3T]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        matrix3 = Matrix3()
        matrix3.Init(buf, pos)
        return cls.InitFromObj(matrix3)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, matrix3):
        x = Matrix3T()
        x._UnPack(matrix3)
        return x

    # Matrix3T
    def _UnPack(self, matrix3):
        if matrix3 is None:
            return
        if matrix3.Col0(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()) is not None:
            self.col0 = spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3T.InitFromObj(matrix3.Col0(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()))
        if matrix3.Col1(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()) is not None:
            self.col1 = spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3T.InitFromObj(matrix3.Col1(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()))
        if matrix3.Col2(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()) is not None:
            self.col2 = spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3T.InitFromObj(matrix3.Col2(spacedatanetwork_astro.invoke.legacy.orbpro.Vec3.Vec3()))

    # Matrix3T
    def Pack(self, builder):
        return CreateMatrix3(builder, self.col0.x, self.col0.y, self.col0.z, self.col1.x, self.col1.y, self.col1.z, self.col2.x, self.col2.y, self.col2.z)
