# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Geographic rectangle in radians (32 bytes)
# Cesium equivalent: Rectangle
class Rectangle(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # Rectangle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Rectangle
    def West(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Rectangle
    def South(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Rectangle
    def East(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Rectangle
    def North(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateRectangle(builder, west, south, east, north):
    builder.Prep(8, 32)
    builder.PrependFloat64(north)
    builder.PrependFloat64(east)
    builder.PrependFloat64(south)
    builder.PrependFloat64(west)
    return builder.Offset()


class RectangleT(object):

    # RectangleT
    def __init__(
        self,
        west = 0.0,
        south = 0.0,
        east = 0.0,
        north = 0.0,
    ):
        self.west = west  # type: float
        self.south = south  # type: float
        self.east = east  # type: float
        self.north = north  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rectangle = Rectangle()
        rectangle.Init(buf, pos)
        return cls.InitFromObj(rectangle)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rectangle):
        x = RectangleT()
        x._UnPack(rectangle)
        return x

    # RectangleT
    def _UnPack(self, rectangle):
        if rectangle is None:
            return
        self.west = rectangle.West()
        self.south = rectangle.South()
        self.east = rectangle.East()
        self.north = rectangle.North()

    # RectangleT
    def Pack(self, builder):
        return CreateRectangle(builder, self.west, self.south, self.east, self.north)
