# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Time interval (16 bytes)
class TimeInterval(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # TimeInterval
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeInterval
    def Start(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TimeInterval
    def Stop(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateTimeInterval(builder, start, stop):
    builder.Prep(8, 16)
    builder.PrependFloat64(stop)
    builder.PrependFloat64(start)
    return builder.Offset()


class TimeIntervalT(object):

    # TimeIntervalT
    def __init__(
        self,
        start = 0.0,
        stop = 0.0,
    ):
        self.start = start  # type: float
        self.stop = stop  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        timeInterval = TimeInterval()
        timeInterval.Init(buf, pos)
        return cls.InitFromObj(timeInterval)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, timeInterval):
        x = TimeIntervalT()
        x._UnPack(timeInterval)
        return x

    # TimeIntervalT
    def _UnPack(self, timeInterval):
        if timeInterval is None:
            return
        self.start = timeInterval.Start()
        self.stop = timeInterval.Stop()

    # TimeIntervalT
    def Pack(self, builder):
        return CreateTimeInterval(builder, self.start, self.stop)
