# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# 2D vector single precision (8 bytes)
class Vec2f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # Vec2f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec2f
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vec2f
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateVec2f(builder, x, y):
    builder.Prep(4, 8)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class Vec2fT(object):

    # Vec2fT
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vec2f = Vec2f()
        vec2f.Init(buf, pos)
        return cls.InitFromObj(vec2f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vec2f):
        x = Vec2fT()
        x._UnPack(vec2f)
        return x

    # Vec2fT
    def _UnPack(self, vec2f):
        if vec2f is None:
            return
        self.x = vec2f.X()
        self.y = vec2f.Y()

    # Vec2fT
    def Pack(self, builder):
        return CreateVec2f(builder, self.x, self.y)
