# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# 2D vector (16 bytes, 8-byte aligned)
# Cesium equivalent: Cartesian2
class Vec2(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Vec2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec2
    def X(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vec2
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateVec2(builder, x, y):
    builder.Prep(8, 16)
    builder.PrependFloat64(y)
    builder.PrependFloat64(x)
    return builder.Offset()


class Vec2T(object):

    # Vec2T
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vec2 = Vec2()
        vec2.Init(buf, pos)
        return cls.InitFromObj(vec2)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vec2):
        x = Vec2T()
        x._UnPack(vec2)
        return x

    # Vec2T
    def _UnPack(self, vec2):
        if vec2 is None:
            return
        self.x = vec2.X()
        self.y = vec2.Y()

    # Vec2T
    def Pack(self, builder):
        return CreateVec2(builder, self.x, self.y)
