# automatically generated by the FlatBuffers compiler, do not modify

# namespace: orbpro

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# 4D vector single precision (16 bytes)
class Vec4f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # Vec4f
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec4f
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vec4f
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # Vec4f
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Vec4f
    def W(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateVec4f(builder, x, y, z, w):
    builder.Prep(4, 16)
    builder.PrependFloat32(w)
    builder.PrependFloat32(z)
    builder.PrependFloat32(y)
    builder.PrependFloat32(x)
    return builder.Offset()


class Vec4fT(object):

    # Vec4fT
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        z = 0.0,
        w = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.z = z  # type: float
        self.w = w  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vec4f = Vec4f()
        vec4f.Init(buf, pos)
        return cls.InitFromObj(vec4f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vec4f):
        x = Vec4fT()
        x._UnPack(vec4f)
        return x

    # Vec4fT
    def _UnPack(self, vec4f):
        if vec4f is None:
            return
        self.x = vec4f.X()
        self.y = vec4f.Y()
        self.z = vec4f.Z()
        self.w = vec4f.W()

    # Vec4fT
    def Pack(self, builder):
        return CreateVec4f(builder, self.x, self.y, self.z, self.w)
