"""Existing module authorities, executed through Python + pinned WasmEdge.

Expected values are extracted by scripts/extract_vectors.mjs from the SAME
module JS/C++ tests or JSON fixtures; they are never generated by these wrappers.
Detailed frame/time/tolerance rationale is in docs/authoritative-vectors.md.
"""
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path
import numpy as np
import pytest
import spacedatanetwork_astro as astro
from spacedatanetwork_astro._codec import obj

V = json.loads((Path(__file__).parent / 'fixtures/module-vectors.json').read_text())


def measure(name, error, unit, tolerance):
    print(f'MEASURE {name}: error={error:.16g} {unit}; tolerance={tolerance:.16g} {unit}')
    assert error <= tolerance


def omm_record(source):
    fields = {'noradId':'NORAD_CAT_ID','objectName':'OBJECT_NAME','objectId':'OBJECT_ID',
              'epoch':'EPOCH','meanMotion':'MEAN_MOTION','eccentricity':'ECCENTRICITY',
              'inclination':'INCLINATION','raan':'RA_OF_ASC_NODE','argPericenter':'ARG_OF_PERICENTER',
              'meanAnomaly':'MEAN_ANOMALY','bstar':'BSTAR','meanMotionDot':'MEAN_MOTION_DOT',
              'meanMotionDdot':'MEAN_MOTION_DDOT'}
    return {fields[k]:v for k,v in source.items()}


def test_sgp4_vallado_radius():
    # Vallado TEME radius is invariant under the module's ECEF rotation. UTC JD.
    case = V['sgp4']
    state = astro.sgp4(omm_record(case['VALLADO_OMM']), [case['VALLADO_TARGET_JD']])[0]
    measure('SGP4 Vallado radius', abs(np.linalg.norm(state[:3])-case['VALLADO_TEME_POSITION_MAGNITUDE_METERS']), 'm', .01)


def test_hpop_tudat_six_samples():
    # Tudat inertial two-body fixture, km/km/s, J2000 TDB JD; original RK4 envelope.
    case = V['hpop']; samples = case['twoBody']['samples']; first=samples[0]
    errors=[]
    for sample in samples:
        state=astro.hpop(first['positionKm'], first['velocityKmPerSec'], case['epochJulianDate'],
                         case['epochJulianDate']+sample['timeSeconds']/86400.)
        errors.append((np.linalg.norm(state.position-sample['positionKm']), np.linalg.norm(state.velocity-sample['velocityKmPerSec'])))
    measure('HPOP Tudat six-sample max position', max(e[0] for e in errors), 'km', 5e-4)
    measure('HPOP Tudat six-sample max velocity', max(e[1] for e in errors), 'km/s', 5e-7)


def test_estimation_vallado_gibbs():
    # Vallado ex7-3; inertial Cartesian SI, time-independent Gibbs construction.
    case=V['estimation']; actual=astro.initial_orbit(case['positions'],mu_m3_s2=case['mu'])
    measure('Estimation Vallado Gibbs velocity', np.max(np.abs(actual[3:]-case['expected'][3:])), 'm/s',1e-9)


def test_time_orekit():
    # Orekit TAIScaleTest.testAAS06134, UTC -> TAI, exact SI offset (no frame).
    case=V['time']; actual=astro.convert_time(case['input'])
    assert actual['TARGET']['ISO8601']==case['expected']
    measure('Time Orekit UTC-TAI',abs(actual['DELTA_SECONDS']-case['delta']),'s',1e-12)


def test_frames_basilisk():
    # Basilisk testPCI2PCPF, fixed J2000->planet DCM; unitless, epoch-independent.
    case=V['frames']; actual=astro.transform_position(case['input'],dcm=np.array(case['dcm']).reshape(3,3))
    measure('Frames Basilisk DCM',np.max(np.abs(actual-case['expected'])),'unitless',0.)


def test_lambert_closed_form():
    # Existing JS analytic circular quarter orbit; GCRF km/km/s, UTC label only.
    case=V['lambert']; mu=case['mu']; radius=case['radius']
    tof=np.pi/2*np.sqrt(radius**3/mu); speed=np.sqrt(mu/radius)
    actual=astro.lambert_izzo([radius,0,0],[0,radius,0],tof,mu_km3_s2=mu)
    assert actual['STATUS']==0
    err=max(np.max(np.abs(actual['SINGLE']['V1']-[0,speed,0])),np.max(np.abs(actual['SINGLE']['V2']-[-speed,0,0])))
    measure('Lambert circular quarter orbit',err,'km/s',1e-6)


def test_access_orekit_elevation_vectors():
    # Same Orekit inverse topocentric tuples; ACW PIV reports max elevation.
    # Constant ECEF samples isolate geometry; TT JD is explicit in ACW.
    errors=[]
    for case in V['access']['vectors']:
        az,el,r=case['azimuthRad'],case['elevationRad'],case['rangeM']
        pos=[6378137+r*np.sin(el),r*np.cos(el)*np.sin(az),r*np.cos(el)*np.cos(az)]
        windows=astro.access([2460400.5,2460400.5+1/86400.],[pos,pos],
            [{'STATION_ID':'orekit-origin','LATITUDE_RAD':0.,'LONGITUDE_RAD':0.,'ALTITUDE_M':0.}], min_elevation_rad=-np.pi/2)
        assert len(windows)==1
        errors.append(abs(windows[0]['MAX_ELEVATION_RAD']-el))
    measure('Access Orekit six elevation vectors',max(errors),'rad',1e-10)


def test_events_analytic_nodes():
    # Existing analytic ellipse in OEM km/km/s; Earth inertial equatorial z=0, UTC.
    case=V['events']; start=datetime.fromtimestamp(case['START']/1000,timezone.utc)
    period=case['PERIOD_SECONDS']; t=np.arange(0,2*period+1,10.); omega=2*np.pi/period
    angle=omega*t+case['PHASE']; A,B,C=case['A'],case['B'],case['C']
    states=np.column_stack((A*np.cos(angle),B*np.sin(angle),C*np.sin(angle),
        -A*omega*np.sin(angle),B*omega*np.cos(angle),C*omega*np.cos(angle)))/1000
    epochs=[(start+timedelta(seconds=float(s))).isoformat(timespec='milliseconds').replace('+00:00','') for s in t]
    context=obj('PCE.PCEEvaluationContext',CENTRAL_BODY_ID=399,GRAVITATIONAL_PARAMETER=3.986004418e14,
        EQUATORIAL_RADIUS_M=6378137.,FLATTENING=1/298.257223563)
    request=obj('EVL.EVLEventLocationRequest',LOCATOR_CLASS=5,CONTEXT=context,
        SCAN_START_EPOCH=epochs[0],SCAN_STOP_EPOCH=epochs[-1],EPOCH_TIME_SYSTEM='UTC',
        SCAN_STEP_SECONDS=30.,REFINEMENT_TOLERANCE_SECONDS=1e-9)
    report=astro.events(epochs,states,request)
    assert report['STATUS']==1, report['ERROR_MESSAGE']
    actual=report['EVENTS']; assert len(actual)==4
    errors=[]
    for i,event in enumerate(actual):
        # datetime truncates submicroseconds; parse fraction independently for ns report precision.
        date,fraction=event['START_EPOCH'].rstrip('Z').split('.')
        sec=(datetime.fromisoformat(date).replace(tzinfo=timezone.utc)-start).total_seconds()+float('0.'+fraction)
        expected=(np.pi-case['PHASE'])/omega+i*period/2
        errors.append(abs(sec-expected))
    measure('Events analytic four nodes',max(errors),'s',1e-3)


def test_conjunction_socrates_three_events():
    # CelesTrak SOCRATES fixed GP window; UTC JD, scalar miss km/speed km/s.
    records={r['NORAD_CAT_ID']:r for rows in V['conjunctionGp'].values() for r in rows}
    def jd(iso):return datetime.fromisoformat(iso.rstrip('Z')).replace(tzinfo=timezone.utc).timestamp()/86400+2440587.5
    refs=V['conjunction']['conjunctions']; start=min(jd(r['EPOCH']) for r in records.values())-.05
    result=astro.conjunction_assessment(list(records.values()),start_jd=start,
        duration_days=max(7.,max(jd(r['tca']) for r in refs)-start+.25),threshold_km=5.,threads=1)
    events=result['conjunctions'];assert len(events)==len(refs)
    errors=[]
    for reference in refs:
        event=next(e for e in events if {e['obj1Norad'],e['obj2Norad']}=={reference['obj1_norad'],reference['obj2_norad']})
        errors.append((abs(event['tcaJd']-jd(reference['tca']))*86400,
            abs(event['minRangeKm']-reference['min_range_km'])*1000,
            abs(event['relSpeedKms']-reference['rel_speed_kms'])*1000))
    measure('Conjunction SOCRATES max TCA',max(e[0] for e in errors),'s',.010)
    measure('Conjunction SOCRATES max miss',max(e[1] for e in errors),'m',5.)
    measure('Conjunction SOCRATES max speed',max(e[2] for e in errors),'m/s',5.)
