# automatically generated by the FlatBuffers compiler, do not modify

# namespace: plugins

# Reference frame for position/velocity
class ReferenceFrame(object):
    # Earth-Centered Inertial (J2000)
    ECI = 0
    # Earth-Centered Earth-Fixed
    ECEF = 1
    # True Equator Mean Equinox
    TEME = 2
    # International Celestial Reference Frame
    ICRF = 3
