/*
 * catalog_synthesis.cpp — Supplemental catalog synthesis (App 2, A2.7 / owner goal 3).
 *
 * A scheduler-driven (TIMERS) module that merges two stored OMM inputs into ONE
 * canonical CelesTrak-replacement OMM catalog:
 *
 *   storage.query(schema="OMM")                         [cap: storage_query]
 *      -> our OD-fitted OMMs (JSON, USER_DEFINED_SDN_SOURCE_* lineage; UNTAGGED
 *         today via fit-pipeline storage.write — see README migration note)
 *      -> Space-Track GP OMMs ($OMM FlatBuffer, SourceName=spacetrack-gp)
 *      -> catsyn::read_stored_omm  (encoding-agnostic normalize + classify)
 *      -> deterministic per-NORAD precedence + dedup
 *      -> schema-exact canonical OMM JSON + full provenance
 *      -> publish_record_with_source(OMM)               [common/provider_source.hpp]
 *           storage.ingest_with_source -> keyslot.sign(CID) -> PNM -> pubsub.publish
 *      -> synthesis summary (returned + published)
 *
 * PRECEDENCE (deterministic, DATA-driven gate status): a provider's fitted OMM
 * OUTRANKS the Space-Track GP record for the same NORAD ONLY when the provider is
 * at A2.4 gate level `hard-pass` AND the fit is STRICTLY fresher (epoch). Every
 * other case falls back to Space-Track GP. An object present in EITHER input is
 * NEVER dropped. An object with no NORAD is QUARANTINED (never keyed as NORAD 0).
 *
 * DETERMINISM: two runs over the same stored inputs produce byte-identical
 * outputs. No wall-clock anywhere — record/PNM timestamps are the winning
 * record's own EPOCH (a sourced timestamp), and batch_id is a hash of the input
 * set's content ids. NORAD iteration, provider aggregation, and quarantine lists
 * are emitted in sorted order.
 *
 * Cron contract (SDN plugins/manager.go): a timer method receives NO input
 * (Input:"none", invoked with nil) and returns JSON — this module needs ZERO Go
 * changes; declaring a `timers` block in the manifest is sufficient. A manual
 * invoke MAY pass a JSON config payload to override gate status / source names /
 * output identity / query limit.
 */
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <algorithm>
#include <map>
#include <string>
#include <vector>

#include "provider_source.hpp"   // ps:: hostcall/publish_record_with_source/json/sha256/base64
#include "omm_reader.hpp"         // catsyn:: encoding-agnostic OMM reader + classification

namespace ps = provider_source;

// Embedded compiled default for config/provider-gate-status.json (generated by
// build.mjs into dist/gate-status-embed.cpp). Runtime config can override it.
extern "C" const char* catalog_gate_status_default_json();

extern "C" {
__attribute__((visibility("default")))
uint8_t* plugin_alloc(uint32_t size) { return static_cast<uint8_t*>(malloc(size)); }
__attribute__((visibility("default")))
void plugin_free(uint8_t* ptr, uint32_t /*size*/) { free(ptr); }
}  // extern "C"

namespace {

// ── minimal JSON slicing (config + storage.query response) ───────────────────

std::string block_slice(const std::string& json, const std::string& key, char open, char close) {
    std::string needle = "\"" + key + "\"";
    size_t k = json.find(needle);
    if (k == std::string::npos) return std::string();
    size_t o = json.find(open, k + needle.size());
    if (o == std::string::npos) return std::string();
    int depth = 0;
    bool instr = false, esc = false;
    for (size_t i = o; i < json.size(); ++i) {
        char c = json[i];
        if (instr) { if (esc) esc = false; else if (c == '\\') esc = true; else if (c == '"') instr = false; continue; }
        if (c == '"') { instr = true; continue; }
        if (c == open) depth++;
        else if (c == close) { depth--; if (depth == 0) return json.substr(o + 1, i - o - 1); }
    }
    return std::string();
}

// Split the top-level {...} objects out of a JSON array body (string/nesting aware).
std::vector<std::string> split_objects(const std::string& arr) {
    std::vector<std::string> out;
    int depth = 0;
    bool instr = false, esc = false;
    size_t start = std::string::npos;
    for (size_t i = 0; i < arr.size(); ++i) {
        char c = arr[i];
        if (instr) { if (esc) esc = false; else if (c == '\\') esc = true; else if (c == '"') instr = false; continue; }
        if (c == '"') { instr = true; continue; }
        if (c == '{') { if (depth == 0) start = i; depth++; }
        else if (c == '}') { depth--; if (depth == 0 && start != std::string::npos) { out.push_back(arr.substr(start, i - start + 1)); start = std::string::npos; } }
    }
    return out;
}

// Parse a flat {"k":"v",...} object body into ordered key/value string pairs.
std::vector<std::pair<std::string, std::string>> parse_string_map(const std::string& body) {
    std::vector<std::pair<std::string, std::string>> out;
    size_t i = 0;
    while (i < body.size()) {
        size_t q1 = body.find('"', i); if (q1 == std::string::npos) break;
        size_t q2 = body.find('"', q1 + 1); if (q2 == std::string::npos) break;
        std::string key = body.substr(q1 + 1, q2 - q1 - 1);
        size_t colon = body.find(':', q2 + 1); if (colon == std::string::npos) break;
        size_t v1 = body.find('"', colon + 1); if (v1 == std::string::npos) break;
        size_t v2 = body.find('"', v1 + 1); if (v2 == std::string::npos) break;
        std::string val = body.substr(v1 + 1, v2 - v1 - 1);
        out.emplace_back(key, val);
        i = v2 + 1;
    }
    return out;
}

std::vector<std::string> parse_string_array(const std::string& body) {
    std::vector<std::string> out;
    size_t i = 0;
    while (i < body.size()) {
        size_t q1 = body.find('"', i); if (q1 == std::string::npos) break;
        size_t q2 = body.find('"', q1 + 1); if (q2 == std::string::npos) break;
        out.push_back(body.substr(q1 + 1, q2 - q1 - 1));
        i = q2 + 1;
    }
    return out;
}

// ── configuration (compiled gate default > plugin.getConfig > request payload) ─

struct SynthConfig {
    std::string query_schema = "OMM";
    long query_limit = 20000;

    // output identity — the synthesis provider
    std::string source_name = "catalog-synthesis";
    std::string output_topic = "sdn/data-source/catalog-synthesis";
    std::string signing_slot = "node-signing";
    std::string signature_type = "ed25519";
    std::string file_id_prefix = "sdn-catalog";
    std::string data_source = "SDN-CATALOG";

    std::vector<std::string> spacetrack_source_names = {"spacetrack-gp", "celestrak-gp"};
    std::map<std::string, std::string> gate;            // provider -> hard-pass|interim|blocked
    std::string default_gate_level = "interim";
};

void apply_gate_json(const std::string& json, SynthConfig* cfg) {
    std::string providers = block_slice(json, "providers", '{', '}');
    if (!providers.empty()) {
        for (auto& kv : parse_string_map(providers)) cfg->gate[kv.first] = kv.second;
    }
    std::string st = block_slice(json, "spacetrackSourceNames", '[', ']');
    if (!st.empty()) {
        std::vector<std::string> names = parse_string_array(st);
        if (!names.empty()) cfg->spacetrack_source_names = names;
    }
    std::string dflt;
    if (ps::json_string_field(json, "defaultLevelForUnlistedProvider", &dflt) && !dflt.empty())
        cfg->default_gate_level = dflt;
}

// A runtime config object may override output identity + query + gate. A nested
// `gateStatus` (same shape as the gate file) merges over the compiled default.
void apply_config_json(const std::string& json, SynthConfig* cfg) {
    if (json.empty()) return;
    std::string s;
    if (ps::json_string_field(json, "querySchema", &s) && !s.empty()) cfg->query_schema = s;
    long lim = ps::json_number_field(json, "queryLimit", 0);
    if (lim > 0) cfg->query_limit = lim;
    if (ps::json_string_field(json, "sourceName", &s) && !s.empty()) cfg->source_name = s;
    if (ps::json_string_field(json, "outputTopic", &s) && !s.empty()) cfg->output_topic = s;
    if (ps::json_string_field(json, "signingSlot", &s) && !s.empty()) cfg->signing_slot = s;
    if (ps::json_string_field(json, "signatureType", &s) && !s.empty()) cfg->signature_type = s;
    if (ps::json_string_field(json, "fileIdPrefix", &s) && !s.empty()) cfg->file_id_prefix = s;
    if (ps::json_string_field(json, "dataSource", &s) && !s.empty()) cfg->data_source = s;
    std::string gate = block_slice(json, "gateStatus", '{', '}');
    if (!gate.empty()) apply_gate_json(gate, cfg);
    // top-level spacetrackSourceNames override (outside a gateStatus block)
    std::string st = block_slice(json, "spacetrackSourceNames", '[', ']');
    if (!st.empty()) {
        std::vector<std::string> names = parse_string_array(st);
        if (!names.empty()) cfg->spacetrack_source_names = names;
    }
}

SynthConfig resolve_config(const uint8_t* req, uint32_t len) {
    SynthConfig cfg;
    // 1. compiled default gate map (embedded config/provider-gate-status.json)
    const char* embed = catalog_gate_status_default_json();
    if (embed != nullptr) apply_gate_json(std::string(embed), &cfg);

    // 2. plugin.getConfig — the node's per-instance module config (result object)
    std::vector<uint8_t> env = ps::hostcall("plugin.getConfig", "{}");
    if (ps::cap_ok(env)) {
        std::string meta = ps::envelope_meta_json(env);
        std::string result = block_slice(meta, "result", '{', '}');
        if (!result.empty()) apply_config_json(result, &cfg);
    }

    // 3. request payload (manual invoke) wins last; a cron tick passes nil/empty.
    if (req != nullptr && len > 0) {
        size_t i = 0;
        while (i < len && (req[i] == ' ' || req[i] == '\n' || req[i] == '\t' || req[i] == '\r')) i++;
        if (i < len && req[i] == '{') apply_config_json(std::string(reinterpret_cast<const char*>(req), len), &cfg);
    }
    return cfg;
}

std::string gate_level(const SynthConfig& cfg, const std::string& provider) {
    auto it = cfg.gate.find(provider);
    if (it != cfg.gate.end()) return it->second;
    return cfg.default_gate_level;
}

// ── consumption: storage.query(schema="OMM") -> raw stored records ───────────

struct RawRecord {
    std::string cid;
    std::string source_name;      // SourceTags.SourceName (may be empty)
    std::vector<uint8_t> data;    // decoded record bytes (JSON or $OMM FlatBuffer)
};

bool storage_query(const SynthConfig& cfg, std::vector<RawRecord>* out, std::string* err) {
    std::string payload = "{\"schema\":\"" + ps::json_escape(cfg.query_schema) +
                          "\",\"limit\":" + std::to_string(cfg.query_limit) + "}";
    std::vector<uint8_t> env = ps::hostcall("storage.query", payload);
    if (!ps::cap_ok(env)) {
        std::string msg;
        ps::json_string_field(ps::envelope_meta_json(env), "message", &msg);
        *err = msg.empty() ? "storage.query failed or storage_query capability not granted" : msg;
        return false;
    }
    std::string meta = ps::envelope_meta_json(env);
    std::string arr = block_slice(meta, "result", '[', ']');
    for (const std::string& rec : split_objects(arr)) {
        RawRecord r;
        ps::json_string_field(rec, "CID", &r.cid);
        std::string data_b64;
        if (!ps::json_string_field(rec, "Data", &data_b64) || data_b64.empty()) continue;
        r.data = ps::base64_decode(data_b64);
        if (r.data.empty()) continue;
        std::string tags = block_slice(rec, "SourceTags", '{', '}');
        if (!tags.empty()) ps::json_string_field(tags, "SourceName", &r.source_name);
        out->push_back(std::move(r));
    }
    return true;
}

// ── precedence ───────────────────────────────────────────────────────────────

// Newest-epoch-wins within a source; tie-break = lexicographically-smallest CID
// (deterministic, no wall-clock). Returns the index of the winner in `idxs`.
size_t pick_newest(const std::vector<catsyn::CanonOmm>& recs, const std::vector<size_t>& idxs) {
    size_t best = idxs[0];
    for (size_t j = 1; j < idxs.size(); ++j) {
        const catsyn::CanonOmm& a = recs[idxs[j]];
        const catsyn::CanonOmm& b = recs[best];
        if (a.epoch_key > b.epoch_key || (a.epoch_key == b.epoch_key && a.cid < b.cid)) best = idxs[j];
    }
    return best;
}

struct Decision {
    size_t winner_idx;
    catsyn::SourceKind kind;
    std::string provider;
    std::string rule;
    std::string gate_status;   // ours: provider gate; ST winner: "n/a"
};

Decision decide(const SynthConfig& cfg,
                const std::vector<catsyn::CanonOmm>& recs,
                bool has_ours, size_t ours_idx,
                bool has_st, size_t st_idx) {
    Decision d;
    std::string ours_gate = has_ours ? gate_level(cfg, recs[ours_idx].provider) : std::string();
    if (has_ours && has_st) {
        bool fresher = recs[ours_idx].epoch_key > recs[st_idx].epoch_key;  // STRICTLY fresher
        if (ours_gate == "hard-pass" && fresher) {
            d.winner_idx = ours_idx; d.kind = catsyn::SourceKind::OursFit;
            d.rule = "ours-hardpass-fresher"; d.gate_status = ours_gate;
        } else if (ours_gate != "hard-pass") {
            d.winner_idx = st_idx; d.kind = catsyn::SourceKind::SpacetrackGp;
            d.rule = "spacetrack-ours-gate-" + ours_gate; d.gate_status = "n/a";
        } else {  // hard-pass but not strictly fresher
            d.winner_idx = st_idx; d.kind = catsyn::SourceKind::SpacetrackGp;
            d.rule = "spacetrack-ours-not-fresher"; d.gate_status = "n/a";
        }
    } else if (has_ours) {
        d.winner_idx = ours_idx; d.kind = catsyn::SourceKind::OursFit;
        d.rule = "ours-sole-source-gate-" + ours_gate; d.gate_status = ours_gate;
    } else {
        d.winner_idx = st_idx; d.kind = catsyn::SourceKind::SpacetrackGp;
        d.rule = "spacetrack-sole-source"; d.gate_status = "n/a";
    }
    d.provider = recs[d.winner_idx].provider;
    return d;
}

// ── canonical catalog OMM record = winner OMM JSON + synthesis provenance ─────

std::string build_catalog_record(const catsyn::CanonOmm& w, const Decision& d, const std::string& batch_id) {
    std::string kind = (d.kind == catsyn::SourceKind::OursFit) ? "ours-fit" : "spacetrack-gp";
    std::string j = w.omm_json;                 // ends with '}' (guaranteed by the reader)
    if (!j.empty() && j.back() == '}') j.pop_back();
    j += ",\"USER_DEFINED_SDN_CATALOG_SOURCE_KIND\":\"" + kind + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_SOURCE_NAME\":\"" + ps::json_escape(d.provider) + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_SOURCE_CID\":\"" + ps::json_escape(w.cid) + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_PRECEDENCE\":\"" + ps::json_escape(d.rule) + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_GATE_STATUS\":\"" + ps::json_escape(d.gate_status) + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_BATCH\":\"" + ps::json_escape(batch_id) + "\"";
    j += ",\"USER_DEFINED_SDN_CATALOG_COMMENT\":\"SDN CelesTrak-replacement catalog (App 2 A2.7): winning source " +
         ps::json_escape(d.provider) + " (" + kind + "); precedence " + ps::json_escape(d.rule) + "\"";
    j += "}";
    return j;
}

std::string catalog_provenance_json(const catsyn::CanonOmm& w, const Decision& d,
                                    long norad, const std::string& batch_id) {
    std::string kind = (d.kind == catsyn::SourceKind::OursFit) ? "ours-fit" : "spacetrack-gp";
    std::string p = "{";
    p += "\"SOURCE_NAME\":\"catalog-synthesis\",";
    p += "\"RECORD_SCHEMA\":\"OMM\",";
    p += "\"CATALOG\":\"celestrak-replacement\",";
    p += "\"WINNING_SOURCE_KIND\":\"" + kind + "\",";
    p += "\"WINNING_SOURCE_NAME\":\"" + ps::json_escape(d.provider) + "\",";
    p += "\"WINNING_SOURCE_CID\":\"" + ps::json_escape(w.cid) + "\",";
    p += "\"PRECEDENCE_RULE\":\"" + ps::json_escape(d.rule) + "\",";
    p += "\"GATE_STATUS\":\"" + ps::json_escape(d.gate_status) + "\",";
    p += "\"NORAD_CAT_ID\":" + std::to_string(norad) + ",";
    p += "\"EPOCH\":\"" + ps::json_escape(w.epoch_iso) + "\",";
    p += "\"BATCH_ID\":\"" + ps::json_escape(batch_id) + "\"";
    if (d.kind == catsyn::SourceKind::OursFit) {
        p += ",\"FIT_SOURCE_CID\":\"" + ps::json_escape(w.fit_source_cid) + "\"";
        p += ",\"FIT_SOURCE_SHA256\":\"" + ps::json_escape(w.fit_source_sha256) + "\"";
        p += ",\"FIT_RMS_KM\":\"" + ps::json_escape(w.fit_rms) + "\"";
        p += ",\"FIT_CONVERGED\":" + std::string(w.fit_converged ? "true" : "false");
        p += ",\"FIT_ID_STATUS\":\"" + ps::json_escape(w.id_status) + "\"";
    }
    p += "}";
    return p;
}

// ── the synthesis pass ───────────────────────────────────────────────────────

struct ProviderStat { catsyn::SourceKind kind; long candidates = 0; long won = 0; long quarantined = 0; };

std::string run_synthesis(const uint8_t* req, uint32_t req_len) {
    SynthConfig cfg = resolve_config(req, req_len);

    std::vector<RawRecord> raw;
    std::string query_err;
    bool query_ok = storage_query(cfg, &raw, &query_err);

    // Deterministic batch id: hash of the SORTED set of input record content ids
    // (identical stored inputs -> identical CIDs -> identical batch). No wall-clock.
    std::vector<std::string> input_cids;
    input_cids.reserve(raw.size());
    for (const RawRecord& r : raw) input_cids.push_back(r.cid);
    std::sort(input_cids.begin(), input_cids.end());
    std::string batch_material = "catalog-synthesis:v1";
    for (const std::string& c : input_cids) { batch_material.push_back('\n'); batch_material += c; }
    std::string batch_id = ps::sha256_hex(reinterpret_cast<const uint8_t*>(batch_material.data()), batch_material.size());

    // Read + classify every record.
    std::vector<catsyn::CanonOmm> recs;
    recs.reserve(raw.size());
    long unreadable = 0;
    std::vector<std::string> skip_reasons;   // "<reason>:<cid>"
    for (const RawRecord& r : raw) {
        catsyn::CanonOmm c;
        if (!catsyn::read_stored_omm(r.cid, r.source_name, r.data, cfg.spacetrack_source_names, &c)) {
            unreadable++;
            skip_reasons.push_back(c.skip_reason + ":" + r.cid);
            continue;
        }
        recs.push_back(std::move(c));
    }

    // Group by NORAD (>0). Quarantine NORAD<=0 (unmapped fits — never keyed as 0).
    std::map<long, std::vector<size_t>> by_norad;
    std::vector<size_t> quarantine;   // indices into recs
    std::map<std::string, ProviderStat> pstats;
    for (size_t i = 0; i < recs.size(); ++i) {
        const catsyn::CanonOmm& c = recs[i];
        ProviderStat& ps_ = pstats[c.provider];
        ps_.kind = c.kind;
        ps_.candidates++;
        if (c.norad <= 0) { quarantine.push_back(i); ps_.quarantined++; continue; }
        by_norad[c.norad].push_back(i);
    }

    // Per-NORAD precedence -> one canonical catalog record.
    long catalog_records = 0, ours_won = 0, spacetrack_won = 0, stored = 0, signed_ = 0, published = 0;
    std::vector<std::string> catalog_lines;   // "<norad>:<kind>:<rule>" (deterministic order = ascending NORAD)

    for (auto& kv : by_norad) {
        long norad = kv.first;
        const std::vector<size_t>& idxs = kv.second;
        std::vector<size_t> ours, st;
        for (size_t idx : idxs) {
            if (recs[idx].kind == catsyn::SourceKind::OursFit) ours.push_back(idx);
            else st.push_back(idx);
        }
        bool has_ours = !ours.empty(), has_st = !st.empty();
        size_t ours_idx = has_ours ? pick_newest(recs, ours) : 0;
        size_t st_idx = has_st ? pick_newest(recs, st) : 0;

        Decision d = decide(cfg, recs, has_ours, ours_idx, has_st, st_idx);
        const catsyn::CanonOmm& w = recs[d.winner_idx];

        std::string record = build_catalog_record(w, d, batch_id);
        std::string prov = catalog_provenance_json(w, d, norad, batch_id);

        ps::ProviderConfig pcfg;
        pcfg.signing_slot = cfg.signing_slot;
        pcfg.publish_topic = cfg.output_topic;
        pcfg.signature_type = cfg.signature_type;
        pcfg.source_name = cfg.source_name;
        pcfg.data_source = cfg.data_source;
        pcfg.record_schema = "OMM";

        std::string file_id = cfg.file_id_prefix + ":OMM:" + std::to_string(norad) + ":" + w.epoch_iso;
        std::string file_name = std::to_string(norad) + "_" + w.epoch_iso + ".omm.json";
        std::string source_url = "sdn://catalog-synthesis";

        ps::PublishResult pr = ps::publish_record_with_source(
            pcfg, reinterpret_cast<const uint8_t*>(record.data()), record.size(),
            file_name, file_id, /*publish_timestamp=*/w.epoch_iso, prov, source_url, batch_id);
        if (pr.stored) stored++;
        if (pr.signed_) signed_++;
        if (pr.published) published++;

        catalog_records++;
        pstats[d.provider].won++;
        if (d.kind == catsyn::SourceKind::OursFit) ours_won++; else spacetrack_won++;

        catalog_lines.push_back(std::to_string(norad) + ":" +
                                (d.kind == catsyn::SourceKind::OursFit ? "ours-fit" : "spacetrack-gp") + ":" + d.rule);
    }

    // Quarantine summary (sorted by CID for determinism).
    std::sort(quarantine.begin(), quarantine.end(),
              [&](size_t a, size_t b) { return recs[a].cid < recs[b].cid; });
    std::sort(skip_reasons.begin(), skip_reasons.end());

    // ── summary JSON (returned + published) ──
    std::string out = "{\"ok\":true,\"pipeline\":\"catalog-synthesis\",";
    out += "\"query_ok\":" + std::string(query_ok ? "true" : "false") + ",";
    if (!query_ok) out += "\"query_error\":\"" + ps::json_escape(query_err) + "\",";
    out += "\"batch_id\":\"" + batch_id + "\",";
    out += "\"records_seen\":" + std::to_string(raw.size()) + ",";
    out += "\"records_readable\":" + std::to_string(recs.size()) + ",";
    out += "\"records_unreadable\":" + std::to_string(unreadable) + ",";
    out += "\"catalog_records\":" + std::to_string(catalog_records) + ",";
    out += "\"ours_won\":" + std::to_string(ours_won) + ",";
    out += "\"spacetrack_won\":" + std::to_string(spacetrack_won) + ",";
    out += "\"quarantined\":" + std::to_string(quarantine.size()) + ",";
    out += "\"stored\":" + std::to_string(stored) + ",";
    out += "\"signed\":" + std::to_string(signed_) + ",";
    out += "\"published\":" + std::to_string(published) + ",";

    // quarantine detail: honest identity, never a fabricated NORAD.
    out += "\"quarantine\":[";
    for (size_t k = 0; k < quarantine.size(); ++k) {
        const catsyn::CanonOmm& c = recs[quarantine[k]];
        if (k) out += ",";
        out += "{\"cid\":\"" + ps::json_escape(c.cid) + "\",";
        out += "\"provider\":\"" + ps::json_escape(c.provider) + "\",";
        out += "\"object_name\":\"" + ps::json_escape(c.object_name) + "\",";
        out += "\"id_status\":\"" + ps::json_escape(c.id_status) + "\",";
        out += "\"reason\":\"no-norad-unmapped-object-id\"}";
    }
    out += "],";

    // per-provider counts (ascending provider name).
    out += "\"providers\":[";
    bool first = true;
    for (auto& kv : pstats) {
        if (!first) out += ",";
        first = false;
        out += "{\"provider\":\"" + ps::json_escape(kv.first) + "\",";
        out += "\"kind\":\"" + std::string(kv.second.kind == catsyn::SourceKind::OursFit ? "ours-fit" : "spacetrack-gp") + "\",";
        out += "\"candidates\":" + std::to_string(kv.second.candidates) + ",";
        out += "\"won\":" + std::to_string(kv.second.won) + ",";
        out += "\"quarantined\":" + std::to_string(kv.second.quarantined) + "}";
    }
    out += "],";

    // skipped/unreadable detail (sorted).
    out += "\"skipped\":[";
    for (size_t k = 0; k < skip_reasons.size(); ++k) { if (k) out += ","; out += "\"" + ps::json_escape(skip_reasons[k]) + "\""; }
    out += "]}";

    // Publish the summary on the synthesis channel so subscribers see run stats.
    ps::pubsub_publish(cfg.output_topic, "{\"CATALOG_SYNTHESIS_SUMMARY\":" + out + "}");
    return out;
}

}  // namespace

extern "C" {

// Canonical streaming invoke entrypoint. The TIMERS method (cron: nil input) or a
// manual invoke (optional JSON config payload) triggers one read+merge+publish pass.
__attribute__((visibility("default")))
uint8_t* plugin_invoke_stream(const uint8_t* req_ptr, uint32_t req_len, uint32_t* out_len_ptr) {
    std::string result = run_synthesis(req_ptr, req_len);
    uint8_t* out = static_cast<uint8_t*>(malloc(result.size()));
    if (out != nullptr) {
        for (size_t i = 0; i < result.size(); i++) out[i] = static_cast<uint8_t>(result[i]);
    }
    if (out_len_ptr != nullptr) *out_len_ptr = static_cast<uint32_t>(result.size());
    return out;
}

}  // extern "C"
