# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConjunctionPcRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConjunctionPcRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConjunctionPcRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConjunctionPcRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConjunctionPcRequest
    def Bplane(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.BPlaneGeometry import BPlaneGeometry
            obj = BPlaneGeometry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionPcRequest
    def Method(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ConjunctionPcRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    ConjunctionPcRequestStart(builder)

def ConjunctionPcRequestAddBplane(builder, bplane):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bplane), 0)

def AddBplane(builder, bplane):
    ConjunctionPcRequestAddBplane(builder, bplane)

def ConjunctionPcRequestAddMethod(builder, method):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(method), 0)

def AddMethod(builder, method):
    ConjunctionPcRequestAddMethod(builder, method)

def ConjunctionPcRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConjunctionPcRequestEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.conjunction.BPlaneGeometry
try:
    from typing import Optional
except:
    pass

class ConjunctionPcRequestT(object):

    # ConjunctionPcRequestT
    def __init__(
        self,
        bplane = None,
        method = None,
    ):
        self.bplane = bplane  # type: Optional[orbpro.conjunction.BPlaneGeometry.BPlaneGeometryT]
        self.method = method  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        conjunctionPcRequest = ConjunctionPcRequest()
        conjunctionPcRequest.Init(buf, pos)
        return cls.InitFromObj(conjunctionPcRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, conjunctionPcRequest):
        x = ConjunctionPcRequestT()
        x._UnPack(conjunctionPcRequest)
        return x

    # ConjunctionPcRequestT
    def _UnPack(self, conjunctionPcRequest):
        if conjunctionPcRequest is None:
            return
        if conjunctionPcRequest.Bplane() is not None:
            self.bplane = spacedatanetwork_astro.invoke.orbpro.conjunction.BPlaneGeometry.BPlaneGeometryT.InitFromObj(conjunctionPcRequest.Bplane())
        self.method = conjunctionPcRequest.Method()

    # ConjunctionPcRequestT
    def Pack(self, builder):
        if self.bplane is not None:
            bplane = self.bplane.Pack(builder)
        if self.method is not None:
            method = builder.CreateString(self.method)
        ConjunctionPcRequestStart(builder)
        if self.bplane is not None:
            ConjunctionPcRequestAddBplane(builder, bplane)
        if self.method is not None:
            ConjunctionPcRequestAddMethod(builder, method)
        conjunctionPcRequest = ConjunctionPcRequestEnd(builder)
        return conjunctionPcRequest
