# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConjunctionSelectedSource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConjunctionSelectedSource()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConjunctionSelectedSource(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConjunctionSelectedSource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConjunctionSelectedSource
    def SourceKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ConjunctionSelectedSource
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def ProviderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def SchemaName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def FileIdentifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def QueryHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def PnmCid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def ManifestCid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConjunctionSelectedSource
    def Topic(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ConjunctionSelectedSourceStart(builder):
    builder.StartObject(10)

def Start(builder):
    ConjunctionSelectedSourceStart(builder)

def ConjunctionSelectedSourceAddSourceKind(builder, sourceKind):
    builder.PrependUint8Slot(0, sourceKind, 0)

def AddSourceKind(builder, sourceKind):
    ConjunctionSelectedSourceAddSourceKind(builder, sourceKind)

def ConjunctionSelectedSourceAddSourceId(builder, sourceId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder, sourceId):
    ConjunctionSelectedSourceAddSourceId(builder, sourceId)

def ConjunctionSelectedSourceAddProviderId(builder, providerId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(providerId), 0)

def AddProviderId(builder, providerId):
    ConjunctionSelectedSourceAddProviderId(builder, providerId)

def ConjunctionSelectedSourceAddSchemaName(builder, schemaName):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(schemaName), 0)

def AddSchemaName(builder, schemaName):
    ConjunctionSelectedSourceAddSchemaName(builder, schemaName)

def ConjunctionSelectedSourceAddFileIdentifier(builder, fileIdentifier):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(fileIdentifier), 0)

def AddFileIdentifier(builder, fileIdentifier):
    ConjunctionSelectedSourceAddFileIdentifier(builder, fileIdentifier)

def ConjunctionSelectedSourceAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    ConjunctionSelectedSourceAddQuery(builder, query)

def ConjunctionSelectedSourceAddQueryHash(builder, queryHash):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(queryHash), 0)

def AddQueryHash(builder, queryHash):
    ConjunctionSelectedSourceAddQueryHash(builder, queryHash)

def ConjunctionSelectedSourceAddPnmCid(builder, pnmCid):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(pnmCid), 0)

def AddPnmCid(builder, pnmCid):
    ConjunctionSelectedSourceAddPnmCid(builder, pnmCid)

def ConjunctionSelectedSourceAddManifestCid(builder, manifestCid):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(manifestCid), 0)

def AddManifestCid(builder, manifestCid):
    ConjunctionSelectedSourceAddManifestCid(builder, manifestCid)

def ConjunctionSelectedSourceAddTopic(builder, topic):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(topic), 0)

def AddTopic(builder, topic):
    ConjunctionSelectedSourceAddTopic(builder, topic)

def ConjunctionSelectedSourceEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConjunctionSelectedSourceEnd(builder)


class ConjunctionSelectedSourceT(object):

    # ConjunctionSelectedSourceT
    def __init__(
        self,
        sourceKind = 0,
        sourceId = None,
        providerId = None,
        schemaName = None,
        fileIdentifier = None,
        query = None,
        queryHash = None,
        pnmCid = None,
        manifestCid = None,
        topic = None,
    ):
        self.sourceKind = sourceKind  # type: int
        self.sourceId = sourceId  # type: Optional[str]
        self.providerId = providerId  # type: Optional[str]
        self.schemaName = schemaName  # type: Optional[str]
        self.fileIdentifier = fileIdentifier  # type: Optional[str]
        self.query = query  # type: Optional[str]
        self.queryHash = queryHash  # type: Optional[str]
        self.pnmCid = pnmCid  # type: Optional[str]
        self.manifestCid = manifestCid  # type: Optional[str]
        self.topic = topic  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        conjunctionSelectedSource = ConjunctionSelectedSource()
        conjunctionSelectedSource.Init(buf, pos)
        return cls.InitFromObj(conjunctionSelectedSource)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, conjunctionSelectedSource):
        x = ConjunctionSelectedSourceT()
        x._UnPack(conjunctionSelectedSource)
        return x

    # ConjunctionSelectedSourceT
    def _UnPack(self, conjunctionSelectedSource):
        if conjunctionSelectedSource is None:
            return
        self.sourceKind = conjunctionSelectedSource.SourceKind()
        self.sourceId = conjunctionSelectedSource.SourceId()
        self.providerId = conjunctionSelectedSource.ProviderId()
        self.schemaName = conjunctionSelectedSource.SchemaName()
        self.fileIdentifier = conjunctionSelectedSource.FileIdentifier()
        self.query = conjunctionSelectedSource.Query()
        self.queryHash = conjunctionSelectedSource.QueryHash()
        self.pnmCid = conjunctionSelectedSource.PnmCid()
        self.manifestCid = conjunctionSelectedSource.ManifestCid()
        self.topic = conjunctionSelectedSource.Topic()

    # ConjunctionSelectedSourceT
    def Pack(self, builder):
        if self.sourceId is not None:
            sourceId = builder.CreateString(self.sourceId)
        if self.providerId is not None:
            providerId = builder.CreateString(self.providerId)
        if self.schemaName is not None:
            schemaName = builder.CreateString(self.schemaName)
        if self.fileIdentifier is not None:
            fileIdentifier = builder.CreateString(self.fileIdentifier)
        if self.query is not None:
            query = builder.CreateString(self.query)
        if self.queryHash is not None:
            queryHash = builder.CreateString(self.queryHash)
        if self.pnmCid is not None:
            pnmCid = builder.CreateString(self.pnmCid)
        if self.manifestCid is not None:
            manifestCid = builder.CreateString(self.manifestCid)
        if self.topic is not None:
            topic = builder.CreateString(self.topic)
        ConjunctionSelectedSourceStart(builder)
        ConjunctionSelectedSourceAddSourceKind(builder, self.sourceKind)
        if self.sourceId is not None:
            ConjunctionSelectedSourceAddSourceId(builder, sourceId)
        if self.providerId is not None:
            ConjunctionSelectedSourceAddProviderId(builder, providerId)
        if self.schemaName is not None:
            ConjunctionSelectedSourceAddSchemaName(builder, schemaName)
        if self.fileIdentifier is not None:
            ConjunctionSelectedSourceAddFileIdentifier(builder, fileIdentifier)
        if self.query is not None:
            ConjunctionSelectedSourceAddQuery(builder, query)
        if self.queryHash is not None:
            ConjunctionSelectedSourceAddQueryHash(builder, queryHash)
        if self.pnmCid is not None:
            ConjunctionSelectedSourceAddPnmCid(builder, pnmCid)
        if self.manifestCid is not None:
            ConjunctionSelectedSourceAddManifestCid(builder, manifestCid)
        if self.topic is not None:
            ConjunctionSelectedSourceAddTopic(builder, topic)
        conjunctionSelectedSource = ConjunctionSelectedSourceEnd(builder)
        return conjunctionSelectedSource
