# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConjunctionPairRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConjunctionPairRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConjunctionPairRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConjunctionPairRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConjunctionPairRequest
    def Tle1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.TleRecord import TleRecord
            obj = TleRecord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionPairRequest
    def Tle2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.TleRecord import TleRecord
            obj = TleRecord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionPairRequest
    def PrimaryTrack(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedTrack import PropagatedTrack
            obj = PropagatedTrack()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionPairRequest
    def SecondaryTrack(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedTrack import PropagatedTrack
            obj = PropagatedTrack()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionPairRequest
    def StartJd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ConjunctionPairRequest
    def DurationDays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 7.0

    # ConjunctionPairRequest
    def Radius1M(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 5.0

    # ConjunctionPairRequest
    def Radius2M(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 5.0

    # ConjunctionPairRequest
    def CoarseStepSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 60.0

    # ConjunctionPairRequest
    def FineTolSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.001

def ConjunctionPairRequestStart(builder):
    builder.StartObject(10)

def Start(builder):
    ConjunctionPairRequestStart(builder)

def ConjunctionPairRequestAddTle1(builder, tle1):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tle1), 0)

def AddTle1(builder, tle1):
    ConjunctionPairRequestAddTle1(builder, tle1)

def ConjunctionPairRequestAddTle2(builder, tle2):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tle2), 0)

def AddTle2(builder, tle2):
    ConjunctionPairRequestAddTle2(builder, tle2)

def ConjunctionPairRequestAddPrimaryTrack(builder, primaryTrack):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(primaryTrack), 0)

def AddPrimaryTrack(builder, primaryTrack):
    ConjunctionPairRequestAddPrimaryTrack(builder, primaryTrack)

def ConjunctionPairRequestAddSecondaryTrack(builder, secondaryTrack):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(secondaryTrack), 0)

def AddSecondaryTrack(builder, secondaryTrack):
    ConjunctionPairRequestAddSecondaryTrack(builder, secondaryTrack)

def ConjunctionPairRequestAddStartJd(builder, startJd):
    builder.PrependFloat64Slot(4, startJd, 0.0)

def AddStartJd(builder, startJd):
    ConjunctionPairRequestAddStartJd(builder, startJd)

def ConjunctionPairRequestAddDurationDays(builder, durationDays):
    builder.PrependFloat64Slot(5, durationDays, 7.0)

def AddDurationDays(builder, durationDays):
    ConjunctionPairRequestAddDurationDays(builder, durationDays)

def ConjunctionPairRequestAddRadius1M(builder, radius1M):
    builder.PrependFloat64Slot(6, radius1M, 5.0)

def AddRadius1M(builder, radius1M):
    ConjunctionPairRequestAddRadius1M(builder, radius1M)

def ConjunctionPairRequestAddRadius2M(builder, radius2M):
    builder.PrependFloat64Slot(7, radius2M, 5.0)

def AddRadius2M(builder, radius2M):
    ConjunctionPairRequestAddRadius2M(builder, radius2M)

def ConjunctionPairRequestAddCoarseStepSec(builder, coarseStepSec):
    builder.PrependFloat64Slot(8, coarseStepSec, 60.0)

def AddCoarseStepSec(builder, coarseStepSec):
    ConjunctionPairRequestAddCoarseStepSec(builder, coarseStepSec)

def ConjunctionPairRequestAddFineTolSec(builder, fineTolSec):
    builder.PrependFloat64Slot(9, fineTolSec, 0.001)

def AddFineTolSec(builder, fineTolSec):
    ConjunctionPairRequestAddFineTolSec(builder, fineTolSec)

def ConjunctionPairRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConjunctionPairRequestEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedTrack
import spacedatanetwork_astro.invoke.orbpro.conjunction.TleRecord
try:
    from typing import Optional
except:
    pass

class ConjunctionPairRequestT(object):

    # ConjunctionPairRequestT
    def __init__(
        self,
        tle1 = None,
        tle2 = None,
        primaryTrack = None,
        secondaryTrack = None,
        startJd = 0.0,
        durationDays = 7.0,
        radius1M = 5.0,
        radius2M = 5.0,
        coarseStepSec = 60.0,
        fineTolSec = 0.001,
    ):
        self.tle1 = tle1  # type: Optional[orbpro.conjunction.TleRecord.TleRecordT]
        self.tle2 = tle2  # type: Optional[orbpro.conjunction.TleRecord.TleRecordT]
        self.primaryTrack = primaryTrack  # type: Optional[orbpro.conjunction.PropagatedTrack.PropagatedTrackT]
        self.secondaryTrack = secondaryTrack  # type: Optional[orbpro.conjunction.PropagatedTrack.PropagatedTrackT]
        self.startJd = startJd  # type: float
        self.durationDays = durationDays  # type: float
        self.radius1M = radius1M  # type: float
        self.radius2M = radius2M  # type: float
        self.coarseStepSec = coarseStepSec  # type: float
        self.fineTolSec = fineTolSec  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        conjunctionPairRequest = ConjunctionPairRequest()
        conjunctionPairRequest.Init(buf, pos)
        return cls.InitFromObj(conjunctionPairRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, conjunctionPairRequest):
        x = ConjunctionPairRequestT()
        x._UnPack(conjunctionPairRequest)
        return x

    # ConjunctionPairRequestT
    def _UnPack(self, conjunctionPairRequest):
        if conjunctionPairRequest is None:
            return
        if conjunctionPairRequest.Tle1() is not None:
            self.tle1 = spacedatanetwork_astro.invoke.orbpro.conjunction.TleRecord.TleRecordT.InitFromObj(conjunctionPairRequest.Tle1())
        if conjunctionPairRequest.Tle2() is not None:
            self.tle2 = spacedatanetwork_astro.invoke.orbpro.conjunction.TleRecord.TleRecordT.InitFromObj(conjunctionPairRequest.Tle2())
        if conjunctionPairRequest.PrimaryTrack() is not None:
            self.primaryTrack = spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedTrack.PropagatedTrackT.InitFromObj(conjunctionPairRequest.PrimaryTrack())
        if conjunctionPairRequest.SecondaryTrack() is not None:
            self.secondaryTrack = spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedTrack.PropagatedTrackT.InitFromObj(conjunctionPairRequest.SecondaryTrack())
        self.startJd = conjunctionPairRequest.StartJd()
        self.durationDays = conjunctionPairRequest.DurationDays()
        self.radius1M = conjunctionPairRequest.Radius1M()
        self.radius2M = conjunctionPairRequest.Radius2M()
        self.coarseStepSec = conjunctionPairRequest.CoarseStepSec()
        self.fineTolSec = conjunctionPairRequest.FineTolSec()

    # ConjunctionPairRequestT
    def Pack(self, builder):
        if self.tle1 is not None:
            tle1 = self.tle1.Pack(builder)
        if self.tle2 is not None:
            tle2 = self.tle2.Pack(builder)
        if self.primaryTrack is not None:
            primaryTrack = self.primaryTrack.Pack(builder)
        if self.secondaryTrack is not None:
            secondaryTrack = self.secondaryTrack.Pack(builder)
        ConjunctionPairRequestStart(builder)
        if self.tle1 is not None:
            ConjunctionPairRequestAddTle1(builder, tle1)
        if self.tle2 is not None:
            ConjunctionPairRequestAddTle2(builder, tle2)
        if self.primaryTrack is not None:
            ConjunctionPairRequestAddPrimaryTrack(builder, primaryTrack)
        if self.secondaryTrack is not None:
            ConjunctionPairRequestAddSecondaryTrack(builder, secondaryTrack)
        ConjunctionPairRequestAddStartJd(builder, self.startJd)
        ConjunctionPairRequestAddDurationDays(builder, self.durationDays)
        ConjunctionPairRequestAddRadius1M(builder, self.radius1M)
        ConjunctionPairRequestAddRadius2M(builder, self.radius2M)
        ConjunctionPairRequestAddCoarseStepSec(builder, self.coarseStepSec)
        ConjunctionPairRequestAddFineTolSec(builder, self.fineTolSec)
        conjunctionPairRequest = ConjunctionPairRequestEnd(builder)
        return conjunctionPairRequest
