# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

class ConjunctionSourceKind(object):
    UNKNOWN = 0
    OMM = 1
    OCM = 2
    OEM = 3
    CDM = 4
    FLATSQL_QUERY = 5
    PNM = 6
    PUBSUB = 7
