# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConjunctionScreenCatalogResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConjunctionScreenCatalogResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConjunctionScreenCatalogResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConjunctionScreenCatalogResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConjunctionScreenCatalogResult
    def ObjectsParsed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ConjunctionScreenCatalogResult
    def ConjunctionsFound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ConjunctionScreenCatalogResult
    def Conjunctions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.ConjunctionEvent import ConjunctionEvent
            obj = ConjunctionEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ConjunctionScreenCatalogResult
    def ConjunctionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ConjunctionScreenCatalogResult
    def ConjunctionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ConjunctionScreenCatalogResult
    def Stats(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.ScreeningStats import ScreeningStats
            obj = ScreeningStats()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ConjunctionScreenCatalogResultStart(builder):
    builder.StartObject(4)

def Start(builder):
    ConjunctionScreenCatalogResultStart(builder)

def ConjunctionScreenCatalogResultAddObjectsParsed(builder, objectsParsed):
    builder.PrependUint32Slot(0, objectsParsed, 0)

def AddObjectsParsed(builder, objectsParsed):
    ConjunctionScreenCatalogResultAddObjectsParsed(builder, objectsParsed)

def ConjunctionScreenCatalogResultAddConjunctionsFound(builder, conjunctionsFound):
    builder.PrependUint32Slot(1, conjunctionsFound, 0)

def AddConjunctionsFound(builder, conjunctionsFound):
    ConjunctionScreenCatalogResultAddConjunctionsFound(builder, conjunctionsFound)

def ConjunctionScreenCatalogResultAddConjunctions(builder, conjunctions):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(conjunctions), 0)

def AddConjunctions(builder, conjunctions):
    ConjunctionScreenCatalogResultAddConjunctions(builder, conjunctions)

def ConjunctionScreenCatalogResultStartConjunctionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartConjunctionsVector(builder, numElems):
    return ConjunctionScreenCatalogResultStartConjunctionsVector(builder, numElems)

def ConjunctionScreenCatalogResultCreateConjunctionsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateConjunctionsVector(builder, data):
    ConjunctionScreenCatalogResultCreateConjunctionsVector(builder, data)

def ConjunctionScreenCatalogResultAddStats(builder, stats):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(stats), 0)

def AddStats(builder, stats):
    ConjunctionScreenCatalogResultAddStats(builder, stats)

def ConjunctionScreenCatalogResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConjunctionScreenCatalogResultEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.conjunction.ConjunctionEvent
import spacedatanetwork_astro.invoke.orbpro.conjunction.ScreeningStats
try:
    from typing import List, Optional
except:
    pass

class ConjunctionScreenCatalogResultT(object):

    # ConjunctionScreenCatalogResultT
    def __init__(
        self,
        objectsParsed = 0,
        conjunctionsFound = 0,
        conjunctions = None,
        stats = None,
    ):
        self.objectsParsed = objectsParsed  # type: int
        self.conjunctionsFound = conjunctionsFound  # type: int
        self.conjunctions = conjunctions  # type: Optional[List[orbpro.conjunction.ConjunctionEvent.ConjunctionEventT]]
        self.stats = stats  # type: Optional[orbpro.conjunction.ScreeningStats.ScreeningStatsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        conjunctionScreenCatalogResult = ConjunctionScreenCatalogResult()
        conjunctionScreenCatalogResult.Init(buf, pos)
        return cls.InitFromObj(conjunctionScreenCatalogResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, conjunctionScreenCatalogResult):
        x = ConjunctionScreenCatalogResultT()
        x._UnPack(conjunctionScreenCatalogResult)
        return x

    # ConjunctionScreenCatalogResultT
    def _UnPack(self, conjunctionScreenCatalogResult):
        if conjunctionScreenCatalogResult is None:
            return
        self.objectsParsed = conjunctionScreenCatalogResult.ObjectsParsed()
        self.conjunctionsFound = conjunctionScreenCatalogResult.ConjunctionsFound()
        if not conjunctionScreenCatalogResult.ConjunctionsIsNone():
            self.conjunctions = []
            for i in range(conjunctionScreenCatalogResult.ConjunctionsLength()):
                if conjunctionScreenCatalogResult.Conjunctions(i) is None:
                    self.conjunctions.append(None)
                else:
                    conjunctionEvent_ = spacedatanetwork_astro.invoke.orbpro.conjunction.ConjunctionEvent.ConjunctionEventT.InitFromObj(conjunctionScreenCatalogResult.Conjunctions(i))
                    self.conjunctions.append(conjunctionEvent_)
        if conjunctionScreenCatalogResult.Stats() is not None:
            self.stats = spacedatanetwork_astro.invoke.orbpro.conjunction.ScreeningStats.ScreeningStatsT.InitFromObj(conjunctionScreenCatalogResult.Stats())

    # ConjunctionScreenCatalogResultT
    def Pack(self, builder):
        if self.conjunctions is not None:
            conjunctionslist = []
            for i in range(len(self.conjunctions)):
                conjunctionslist.append(self.conjunctions[i].Pack(builder))
            ConjunctionScreenCatalogResultStartConjunctionsVector(builder, len(self.conjunctions))
            for i in reversed(range(len(self.conjunctions))):
                builder.PrependUOffsetTRelative(conjunctionslist[i])
            conjunctions = builder.EndVector()
        if self.stats is not None:
            stats = self.stats.Pack(builder)
        ConjunctionScreenCatalogResultStart(builder)
        ConjunctionScreenCatalogResultAddObjectsParsed(builder, self.objectsParsed)
        ConjunctionScreenCatalogResultAddConjunctionsFound(builder, self.conjunctionsFound)
        if self.conjunctions is not None:
            ConjunctionScreenCatalogResultAddConjunctions(builder, conjunctions)
        if self.stats is not None:
            ConjunctionScreenCatalogResultAddStats(builder, stats)
        conjunctionScreenCatalogResult = ConjunctionScreenCatalogResultEnd(builder)
        return conjunctionScreenCatalogResult
