# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GpRecord(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GpRecord()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGpRecord(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GpRecord
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GpRecord
    def ObjectName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GpRecord
    def ObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GpRecord
    def Epoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GpRecord
    def MeanMotion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def Eccentricity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def Inclination(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def RaOfAscNode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def ArgOfPericenter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def MeanAnomaly(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def EphemerisType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GpRecord
    def ClassificationType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GpRecord
    def NoradCatId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GpRecord
    def ElementSetNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GpRecord
    def RevAtEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GpRecord
    def Bstar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def MeanMotionDot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GpRecord
    def MeanMotionDdot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def GpRecordStart(builder):
    builder.StartObject(17)

def Start(builder):
    GpRecordStart(builder)

def GpRecordAddObjectName(builder, objectName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectName), 0)

def AddObjectName(builder, objectName):
    GpRecordAddObjectName(builder, objectName)

def GpRecordAddObjectId(builder, objectId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(objectId), 0)

def AddObjectId(builder, objectId):
    GpRecordAddObjectId(builder, objectId)

def GpRecordAddEpoch(builder, epoch):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(epoch), 0)

def AddEpoch(builder, epoch):
    GpRecordAddEpoch(builder, epoch)

def GpRecordAddMeanMotion(builder, meanMotion):
    builder.PrependFloat64Slot(3, meanMotion, 0.0)

def AddMeanMotion(builder, meanMotion):
    GpRecordAddMeanMotion(builder, meanMotion)

def GpRecordAddEccentricity(builder, eccentricity):
    builder.PrependFloat64Slot(4, eccentricity, 0.0)

def AddEccentricity(builder, eccentricity):
    GpRecordAddEccentricity(builder, eccentricity)

def GpRecordAddInclination(builder, inclination):
    builder.PrependFloat64Slot(5, inclination, 0.0)

def AddInclination(builder, inclination):
    GpRecordAddInclination(builder, inclination)

def GpRecordAddRaOfAscNode(builder, raOfAscNode):
    builder.PrependFloat64Slot(6, raOfAscNode, 0.0)

def AddRaOfAscNode(builder, raOfAscNode):
    GpRecordAddRaOfAscNode(builder, raOfAscNode)

def GpRecordAddArgOfPericenter(builder, argOfPericenter):
    builder.PrependFloat64Slot(7, argOfPericenter, 0.0)

def AddArgOfPericenter(builder, argOfPericenter):
    GpRecordAddArgOfPericenter(builder, argOfPericenter)

def GpRecordAddMeanAnomaly(builder, meanAnomaly):
    builder.PrependFloat64Slot(8, meanAnomaly, 0.0)

def AddMeanAnomaly(builder, meanAnomaly):
    GpRecordAddMeanAnomaly(builder, meanAnomaly)

def GpRecordAddEphemerisType(builder, ephemerisType):
    builder.PrependInt32Slot(9, ephemerisType, 0)

def AddEphemerisType(builder, ephemerisType):
    GpRecordAddEphemerisType(builder, ephemerisType)

def GpRecordAddClassificationType(builder, classificationType):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(classificationType), 0)

def AddClassificationType(builder, classificationType):
    GpRecordAddClassificationType(builder, classificationType)

def GpRecordAddNoradCatId(builder, noradCatId):
    builder.PrependInt32Slot(11, noradCatId, 0)

def AddNoradCatId(builder, noradCatId):
    GpRecordAddNoradCatId(builder, noradCatId)

def GpRecordAddElementSetNo(builder, elementSetNo):
    builder.PrependInt32Slot(12, elementSetNo, 0)

def AddElementSetNo(builder, elementSetNo):
    GpRecordAddElementSetNo(builder, elementSetNo)

def GpRecordAddRevAtEpoch(builder, revAtEpoch):
    builder.PrependInt32Slot(13, revAtEpoch, 0)

def AddRevAtEpoch(builder, revAtEpoch):
    GpRecordAddRevAtEpoch(builder, revAtEpoch)

def GpRecordAddBstar(builder, bstar):
    builder.PrependFloat64Slot(14, bstar, 0.0)

def AddBstar(builder, bstar):
    GpRecordAddBstar(builder, bstar)

def GpRecordAddMeanMotionDot(builder, meanMotionDot):
    builder.PrependFloat64Slot(15, meanMotionDot, 0.0)

def AddMeanMotionDot(builder, meanMotionDot):
    GpRecordAddMeanMotionDot(builder, meanMotionDot)

def GpRecordAddMeanMotionDdot(builder, meanMotionDdot):
    builder.PrependFloat64Slot(16, meanMotionDdot, 0.0)

def AddMeanMotionDdot(builder, meanMotionDdot):
    GpRecordAddMeanMotionDdot(builder, meanMotionDdot)

def GpRecordEnd(builder):
    return builder.EndObject()

def End(builder):
    return GpRecordEnd(builder)


class GpRecordT(object):

    # GpRecordT
    def __init__(
        self,
        objectName = None,
        objectId = None,
        epoch = None,
        meanMotion = 0.0,
        eccentricity = 0.0,
        inclination = 0.0,
        raOfAscNode = 0.0,
        argOfPericenter = 0.0,
        meanAnomaly = 0.0,
        ephemerisType = 0,
        classificationType = None,
        noradCatId = 0,
        elementSetNo = 0,
        revAtEpoch = 0,
        bstar = 0.0,
        meanMotionDot = 0.0,
        meanMotionDdot = 0.0,
    ):
        self.objectName = objectName  # type: Optional[str]
        self.objectId = objectId  # type: Optional[str]
        self.epoch = epoch  # type: Optional[str]
        self.meanMotion = meanMotion  # type: float
        self.eccentricity = eccentricity  # type: float
        self.inclination = inclination  # type: float
        self.raOfAscNode = raOfAscNode  # type: float
        self.argOfPericenter = argOfPericenter  # type: float
        self.meanAnomaly = meanAnomaly  # type: float
        self.ephemerisType = ephemerisType  # type: int
        self.classificationType = classificationType  # type: Optional[str]
        self.noradCatId = noradCatId  # type: int
        self.elementSetNo = elementSetNo  # type: int
        self.revAtEpoch = revAtEpoch  # type: int
        self.bstar = bstar  # type: float
        self.meanMotionDot = meanMotionDot  # type: float
        self.meanMotionDdot = meanMotionDdot  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gpRecord = GpRecord()
        gpRecord.Init(buf, pos)
        return cls.InitFromObj(gpRecord)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, gpRecord):
        x = GpRecordT()
        x._UnPack(gpRecord)
        return x

    # GpRecordT
    def _UnPack(self, gpRecord):
        if gpRecord is None:
            return
        self.objectName = gpRecord.ObjectName()
        self.objectId = gpRecord.ObjectId()
        self.epoch = gpRecord.Epoch()
        self.meanMotion = gpRecord.MeanMotion()
        self.eccentricity = gpRecord.Eccentricity()
        self.inclination = gpRecord.Inclination()
        self.raOfAscNode = gpRecord.RaOfAscNode()
        self.argOfPericenter = gpRecord.ArgOfPericenter()
        self.meanAnomaly = gpRecord.MeanAnomaly()
        self.ephemerisType = gpRecord.EphemerisType()
        self.classificationType = gpRecord.ClassificationType()
        self.noradCatId = gpRecord.NoradCatId()
        self.elementSetNo = gpRecord.ElementSetNo()
        self.revAtEpoch = gpRecord.RevAtEpoch()
        self.bstar = gpRecord.Bstar()
        self.meanMotionDot = gpRecord.MeanMotionDot()
        self.meanMotionDdot = gpRecord.MeanMotionDdot()

    # GpRecordT
    def Pack(self, builder):
        if self.objectName is not None:
            objectName = builder.CreateString(self.objectName)
        if self.objectId is not None:
            objectId = builder.CreateString(self.objectId)
        if self.epoch is not None:
            epoch = builder.CreateString(self.epoch)
        if self.classificationType is not None:
            classificationType = builder.CreateString(self.classificationType)
        GpRecordStart(builder)
        if self.objectName is not None:
            GpRecordAddObjectName(builder, objectName)
        if self.objectId is not None:
            GpRecordAddObjectId(builder, objectId)
        if self.epoch is not None:
            GpRecordAddEpoch(builder, epoch)
        GpRecordAddMeanMotion(builder, self.meanMotion)
        GpRecordAddEccentricity(builder, self.eccentricity)
        GpRecordAddInclination(builder, self.inclination)
        GpRecordAddRaOfAscNode(builder, self.raOfAscNode)
        GpRecordAddArgOfPericenter(builder, self.argOfPericenter)
        GpRecordAddMeanAnomaly(builder, self.meanAnomaly)
        GpRecordAddEphemerisType(builder, self.ephemerisType)
        if self.classificationType is not None:
            GpRecordAddClassificationType(builder, classificationType)
        GpRecordAddNoradCatId(builder, self.noradCatId)
        GpRecordAddElementSetNo(builder, self.elementSetNo)
        GpRecordAddRevAtEpoch(builder, self.revAtEpoch)
        GpRecordAddBstar(builder, self.bstar)
        GpRecordAddMeanMotionDot(builder, self.meanMotionDot)
        GpRecordAddMeanMotionDdot(builder, self.meanMotionDdot)
        gpRecord = GpRecordEnd(builder)
        return gpRecord
