# automatically generated by the FlatBuffers compiler, do not modify

# namespace: conjunction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropagatedTrack(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropagatedTrack()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropagatedTrack(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropagatedTrack
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropagatedTrack
    def SourcePluginId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatedTrack
    def SourceHandle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PropagatedTrack
    def ObjectName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatedTrack
    def ObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PropagatedTrack
    def NoradCatId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PropagatedTrack
    def ReferenceFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PropagatedTrack
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedSample import PropagatedSample
            obj = PropagatedSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropagatedTrack
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropagatedTrack
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def PropagatedTrackStart(builder):
    builder.StartObject(7)

def Start(builder):
    PropagatedTrackStart(builder)

def PropagatedTrackAddSourcePluginId(builder, sourcePluginId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourcePluginId), 0)

def AddSourcePluginId(builder, sourcePluginId):
    PropagatedTrackAddSourcePluginId(builder, sourcePluginId)

def PropagatedTrackAddSourceHandle(builder, sourceHandle):
    builder.PrependUint32Slot(1, sourceHandle, 0)

def AddSourceHandle(builder, sourceHandle):
    PropagatedTrackAddSourceHandle(builder, sourceHandle)

def PropagatedTrackAddObjectName(builder, objectName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(objectName), 0)

def AddObjectName(builder, objectName):
    PropagatedTrackAddObjectName(builder, objectName)

def PropagatedTrackAddObjectId(builder, objectId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(objectId), 0)

def AddObjectId(builder, objectId):
    PropagatedTrackAddObjectId(builder, objectId)

def PropagatedTrackAddNoradCatId(builder, noradCatId):
    builder.PrependInt32Slot(4, noradCatId, 0)

def AddNoradCatId(builder, noradCatId):
    PropagatedTrackAddNoradCatId(builder, noradCatId)

def PropagatedTrackAddReferenceFrame(builder, referenceFrame):
    builder.PrependUint8Slot(5, referenceFrame, 0)

def AddReferenceFrame(builder, referenceFrame):
    PropagatedTrackAddReferenceFrame(builder, referenceFrame)

def PropagatedTrackAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    PropagatedTrackAddSamples(builder, samples)

def PropagatedTrackStartSamplesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSamplesVector(builder, numElems):
    return PropagatedTrackStartSamplesVector(builder, numElems)

def PropagatedTrackCreateSamplesVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateSamplesVector(builder, data):
    PropagatedTrackCreateSamplesVector(builder, data)

def PropagatedTrackEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropagatedTrackEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedSample
try:
    from typing import List
except:
    pass

class PropagatedTrackT(object):

    # PropagatedTrackT
    def __init__(
        self,
        sourcePluginId = None,
        sourceHandle = 0,
        objectName = None,
        objectId = None,
        noradCatId = 0,
        referenceFrame = 0,
        samples = None,
    ):
        self.sourcePluginId = sourcePluginId  # type: Optional[str]
        self.sourceHandle = sourceHandle  # type: int
        self.objectName = objectName  # type: Optional[str]
        self.objectId = objectId  # type: Optional[str]
        self.noradCatId = noradCatId  # type: int
        self.referenceFrame = referenceFrame  # type: int
        self.samples = samples  # type: Optional[List[orbpro.conjunction.PropagatedSample.PropagatedSampleT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        propagatedTrack = PropagatedTrack()
        propagatedTrack.Init(buf, pos)
        return cls.InitFromObj(propagatedTrack)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, propagatedTrack):
        x = PropagatedTrackT()
        x._UnPack(propagatedTrack)
        return x

    # PropagatedTrackT
    def _UnPack(self, propagatedTrack):
        if propagatedTrack is None:
            return
        self.sourcePluginId = propagatedTrack.SourcePluginId()
        self.sourceHandle = propagatedTrack.SourceHandle()
        self.objectName = propagatedTrack.ObjectName()
        self.objectId = propagatedTrack.ObjectId()
        self.noradCatId = propagatedTrack.NoradCatId()
        self.referenceFrame = propagatedTrack.ReferenceFrame()
        if not propagatedTrack.SamplesIsNone():
            self.samples = []
            for i in range(propagatedTrack.SamplesLength()):
                if propagatedTrack.Samples(i) is None:
                    self.samples.append(None)
                else:
                    propagatedSample_ = spacedatanetwork_astro.invoke.orbpro.conjunction.PropagatedSample.PropagatedSampleT.InitFromObj(propagatedTrack.Samples(i))
                    self.samples.append(propagatedSample_)

    # PropagatedTrackT
    def Pack(self, builder):
        if self.sourcePluginId is not None:
            sourcePluginId = builder.CreateString(self.sourcePluginId)
        if self.objectName is not None:
            objectName = builder.CreateString(self.objectName)
        if self.objectId is not None:
            objectId = builder.CreateString(self.objectId)
        if self.samples is not None:
            sampleslist = []
            for i in range(len(self.samples)):
                sampleslist.append(self.samples[i].Pack(builder))
            PropagatedTrackStartSamplesVector(builder, len(self.samples))
            for i in reversed(range(len(self.samples))):
                builder.PrependUOffsetTRelative(sampleslist[i])
            samples = builder.EndVector()
        PropagatedTrackStart(builder)
        if self.sourcePluginId is not None:
            PropagatedTrackAddSourcePluginId(builder, sourcePluginId)
        PropagatedTrackAddSourceHandle(builder, self.sourceHandle)
        if self.objectName is not None:
            PropagatedTrackAddObjectName(builder, objectName)
        if self.objectId is not None:
            PropagatedTrackAddObjectId(builder, objectId)
        PropagatedTrackAddNoradCatId(builder, self.noradCatId)
        PropagatedTrackAddReferenceFrame(builder, self.referenceFrame)
        if self.samples is not None:
            PropagatedTrackAddSamples(builder, samples)
        propagatedTrack = PropagatedTrackEnd(builder)
        return propagatedTrack
