"""Small WasmEdge 0.16.4 C-API host for the SDK's binary invoke ABI.

No orbital computation runs in this file.  The host mirrors SDK
src/testing/native/wasmedge_emscripten_pthread_runner.c and src/invoke/codec.js.
Each instance owns its store and shared memory; concurrent invokes are serialized.
"""
from __future__ import annotations

import ctypes as C
from ctypes.util import find_library
from dataclasses import dataclass
import os
from pathlib import Path
import struct
import threading
from collections.abc import Mapping, Sequence

from .artifacts import Artifact, get_artifact, list_artifacts

WASMEDGE_VERSION = "0.16.4"
_INSTALL = "Install WasmEdge 0.16.4 using space-data-network/scripts/install-wasmedge.sh, or set WASMEDGE_LIB to its libwasmedge shared library."


class RuntimeUnavailableError(RuntimeError):
    """The pinned native WasmEdge shared library could not be loaded."""


class WasmEdgeError(RuntimeError):
    """A guest operation or host ABI validation failed."""


class InvokeError(WasmEdgeError):
    """A module returned a failed PIV response."""


@dataclass(frozen=True)
class Frame:
    """A typed SDK TAB payload; payload is the complete schema FlatBuffer.

    Size prefixes belong to stream transports, not the PIV envelope. Preserve
    any payload prefix expected by the particular module's declared input port.
    """
    port_id: str
    payload: bytes
    schema_name: str = ""
    file_identifier: str = ""
    root_type: str = ""
    alignment: int = 8
    wire_format: str = "flatbuffer"


def _frame(value):
    if isinstance(value, Frame):
        return value
    if not isinstance(value, Mapping):
        raise TypeError("inputs must contain Frame or mapping values")
    typ = value.get("typeRef", {})
    return Frame(value.get("port_id", value.get("portId", "")), bytes(value["payload"]),
                 value.get("schema_name", typ.get("schemaName", "")),
                 value.get("file_identifier", typ.get("fileIdentifier", "")),
                 value.get("root_type", typ.get("rootType", typ.get("rootTypeName", ""))),
                 value.get("alignment", 8), value.get("wire_format", value.get("wireFormat", "flatbuffer")))


def encode_request(method_id: str, inputs: Sequence[Frame | Mapping]) -> bytes:
    """Encode ratified PIV/TAB through vendored generated schema bindings."""
    import flatbuffers
    from .sds.PIV.FlatBufferTypeRef import FlatBufferTypeRefT
    from .sds.PIV.TAB import TABT
    from .sds.PIV import PIV, PIVRequest
    if not isinstance(method_id, str) or not method_id:
        raise ValueError("method_id must be a non-empty string")
    b = flatbuffers.Builder(1024)
    arena = bytearray()
    tabs = []
    max_alignment = 8
    for item in inputs:
        f = _frame(item)
        if not f.port_id:
            raise ValueError("each input needs a port_id")
        if f.alignment < 8 or f.alignment > 32768 or f.alignment & (f.alignment - 1):
            raise ValueError("frame alignment must be a power of two from 8 to 32768")
        if f.wire_format not in ("flatbuffer", "aligned-binary"):
            raise ValueError(f"Unsupported wire_format {f.wire_format!r}")
        wire = ("flatbuffer", "aligned-binary").index(f.wire_format)
        max_alignment = max(max_alignment, f.alignment)
        arena.extend(b"\0" * ((-len(arena)) % f.alignment))
        offset = len(arena)
        arena.extend(f.payload)
        typ = FlatBufferTypeRefT(SCHEMA_NAME=f.schema_name or None,
                                 FILE_IDENTIFIER=f.file_identifier or None,
                                 ROOT_TYPE=f.root_type or None, WIRE_FORMAT=wire)
        tabs.append(TABT(OFFSET=offset, SIZE=len(f.payload), ALIGNMENT=f.alignment,
                         WIRE_FORMAT=wire, TYPE_REF=typ, PORT_ID=f.port_id).Pack(b))
    method = b.CreateString(method_id)
    PIVRequest.StartINPUTSVector(b, len(tabs))
    for tab in reversed(tabs):
        b.PrependUOffsetTRelative(tab)
    vector = b.EndVector()
    # Generated byte-vector helpers use alignment 1; SDK mandates absolute
    # alignment 8 (or the TAB's larger requirement) for the payload arena.
    b.StartVector(1, len(arena), max_alignment)
    for byte in reversed(arena):
        b.PrependUint8(byte)
    payload = b.EndVector()
    PIVRequest.Start(b)
    PIVRequest.AddMETHOD_ID(b, method)
    PIVRequest.AddINPUTS(b, vector)
    PIVRequest.AddPAYLOAD_ARENA(b, payload)
    request = PIVRequest.End(b)
    PIV.Start(b)
    PIV.AddREQUEST(b, request)
    root = PIV.End(b)
    b.Finish(root, file_identifier=b"$PIV")
    return bytes(b.Output())


class _Table:
    """Bounds-checked reader for PIV transport fields; schema payloads stay opaque."""
    def __init__(self, data, pos):
        self.data, self.pos = data, pos
        self.vtable = pos - self.number("i", pos)
        self.vsize = self.number("H", self.vtable)
        if self.vsize < 4 or self.vtable + self.vsize > len(data):
            raise WasmEdgeError("Malformed PIV vtable")

    def number(self, fmt, pos):
        if pos < 0 or pos + struct.calcsize(fmt) > len(self.data):
            raise WasmEdgeError("PIV offset is outside the envelope")
        return struct.unpack_from("<" + fmt, self.data, pos)[0]

    def field(self, slot):
        address = self.vtable + 4 + slot * 2
        if address + 2 > self.vtable + self.vsize:
            return 0
        offset = self.number("H", address)
        return self.pos + offset if offset else 0

    def scalar(self, slot, fmt="I", default=0):
        offset = self.field(slot)
        return self.number(fmt, offset) if offset else default

    def indirect(self, slot):
        offset = self.field(slot)
        return offset + self.number("I", offset) if offset else 0

    def table(self, slot):
        pos = self.indirect(slot)
        return _Table(self.data, pos) if pos else None

    def vector(self, slot):
        pos = self.indirect(slot)
        return (pos + 4, self.number("I", pos)) if pos else (0, 0)

    def string(self, slot):
        pos, size = self.vector(slot)
        if pos + size > len(self.data):
            raise WasmEdgeError("PIV string is outside the envelope")
        return bytes(self.data[pos:pos + size]).decode("utf-8")


def decode_response(data: bytes) -> list[Frame]:
    if len(data) < 8 or data[4:8] != b"$PIV":
        raise WasmEdgeError("Expected an SDS $PIV response envelope")
    root = _Table(data, struct.unpack_from("<I", data)[0])
    response = root.table(1)
    if response is None:
        raise WasmEdgeError("PIV envelope does not contain a response")
    status = response.scalar(0, "i")
    # PIVResponse: STATUS_CODE, STATUS, YIELDED, BACKLOG_REMAINING,
    # OUTPUTS, PAYLOAD_ARENA, ERROR_CODE, ERROR_MESSAGE, TRACE_ID.
    envelope_status = response.scalar(1, "i")
    if status or envelope_status not in (0, 2) or response.string(6):
        raise InvokeError(f"{response.string(6) or status}: {response.string(7)}")
    if envelope_status == 2 or response.scalar(2, "B") or response.scalar(3):
        raise InvokeError("Module yielded queued work; use invoke_bytes and the PIV response to resume explicitly")
    arena_start, arena_length = response.vector(5)
    if arena_start + arena_length > len(data):
        raise WasmEdgeError("PIV payload arena is outside the envelope")
    start, count = response.vector(4)
    if count > len(data) // 4 or start + count * 4 > len(data):
        raise WasmEdgeError("PIV output vector is outside the envelope")
    frames = []
    for index in range(count):
        pos = start + 4 * index
        tab = _Table(data, pos + struct.unpack_from("<I", data, pos)[0])
        offset, size = tab.scalar(0), tab.scalar(1)
        alignment = tab.scalar(2, "I", 8)
        if alignment < 1 or alignment & (alignment - 1):
            raise WasmEdgeError("PIV TAB alignment is not a power of two")
        if offset + size > arena_length or (size and (arena_start + offset) % alignment):
            raise WasmEdgeError("PIV TAB payload range/alignment is invalid")
        wire = tab.scalar(3, "B")
        if wire not in (0, 1):
            raise WasmEdgeError(f"Unknown TAB wire format {wire}")
        typ = tab.table(4)
        frames.append(Frame(tab.string(8), bytes(data[arena_start + offset:arena_start + offset + size]),
                            typ.string(0) if typ else "", typ.string(1) if typ else "",
                            typ.string(3) if typ else "", alignment,
                            ("flatbuffer", "aligned-binary")[wire]))
    return frames


class _String(C.Structure):
    _fields_ = [("Length", C.c_uint32), ("Buf", C.c_void_p)]


class _Bytes(C.Structure):
    _fields_ = [("Length", C.c_uint32), ("Buf", C.c_void_p)]


class _Result(C.Structure):
    _fields_ = [("Code", C.c_uint32)]


class _ValType(C.Structure):
    _fields_ = [("Data", C.c_ubyte * 8)]


class _Value(C.Structure):
    # uint128_t Value followed by the 8-byte ValType, rounded to 32 bytes by
    # the C ABI. Values travel as pointers except ValueGen/Get return helpers.
    _fields_ = [("Value", C.c_uint64 * 2), ("Type", _ValType), ("_pad", C.c_ubyte * 8)]


# WasmEdge_Result is a single uint32_t, returned in the integer result register
# on arm64/x86_64 (ctypes callbacks cannot return a structure directly).
_CALLBACK = C.CFUNCTYPE(C.c_uint32, C.c_void_p, C.c_void_p, C.POINTER(_Value), C.POINTER(_Value))


def library_candidates():
    explicit = os.environ.get("WASMEDGE_LIB")
    if explicit:
        yield os.path.expanduser(explicit)
    for name in ("libwasmedge.dylib", "libwasmedge.so", "wasmedge.dll"):
        yield str(Path.home() / ".wasmedge" / "lib" / name)
    found = find_library("wasmedge")
    if found:
        yield found
    yield from ("libwasmedge.dylib", "libwasmedge.so", "wasmedge.dll")


class _API:
    def __init__(self):
        errors = []
        for path in library_candidates():
            try:
                self.lib = C.CDLL(path)
                self.path = path
                break
            except OSError as error:
                errors.append(str(error))
        else:
            raise RuntimeUnavailableError(_INSTALL + "\n" + "\n".join(errors))
        ptr, u32, val = C.c_void_p, C.c_uint32, C.POINTER(_Value)
        signatures = {
            "VersionGet": (C.c_char_p, []), "ResultOK": (C.c_bool, [_Result]),
            "ResultGetMessage": (C.c_char_p, [_Result]),
            "ConfigureCreate": (ptr, []), "ConfigureAddProposal": (None, [ptr, C.c_int]),
            "ConfigureDelete": (None, [ptr]), "StoreCreate": (ptr, []), "StoreDelete": (None, [ptr]),
            "LoaderCreate": (ptr, [ptr]), "LoaderDelete": (None, [ptr]),
            "ValidatorCreate": (ptr, [ptr]), "ValidatorDelete": (None, [ptr]),
            "ValidatorValidate": (_Result, [ptr, ptr]),
            "LoaderParseFromBytes": (_Result, [ptr, C.POINTER(ptr), _Bytes]),
            "ASTModuleDelete": (None, [ptr]), "ASTModuleListImportsLength": (u32, [ptr]),
            "ASTModuleListImports": (u32, [ptr, C.POINTER(ptr), u32]),
            "ImportTypeGetExternalType": (C.c_int, [ptr]),
            "ImportTypeGetModuleName": (_String, [ptr]), "ImportTypeGetExternalName": (_String, [ptr]),
            "ImportTypeGetFunctionType": (ptr, [ptr, ptr]), "ImportTypeGetMemoryType": (ptr, [ptr, ptr]),
            "VMCreate": (ptr, [ptr, ptr]), "VMDelete": (None, [ptr]),
            "VMRegisterModuleFromImport": (_Result, [ptr, ptr]),
            "VMLoadWasmFromASTModule": (_Result, [ptr, ptr]), "VMValidate": (_Result, [ptr]),
            "VMInstantiate": (_Result, [ptr]), "VMGetActiveModule": (ptr, [ptr]),
            "VMGetExecutorContext": (ptr, [ptr]),
            "ModuleInstanceCreateWASI": (ptr, [C.POINTER(C.c_char_p), u32, C.POINTER(C.c_char_p), u32, C.POINTER(C.c_char_p), u32]),
            "ModuleInstanceCreate": (ptr, [_String]), "ModuleInstanceDelete": (None, [ptr]),
            "ModuleInstanceAddFunction": (None, [ptr, _String, ptr]),
            "ModuleInstanceAddMemory": (None, [ptr, _String, ptr]),
            "ModuleInstanceFindFunction": (ptr, [ptr, _String]),
            "ModuleInstanceFindMemory": (ptr, [ptr, _String]),
            "ModuleInstanceFindTable": (ptr, [ptr, _String]),
            "FunctionInstanceCreate": (ptr, [ptr, _CALLBACK, ptr, C.c_uint64]),
            "FunctionInstanceGetFunctionType": (ptr, [ptr]),
            "FunctionTypeGetParametersLength": (u32, [ptr]),
            "FunctionTypeGetReturnsLength": (u32, [ptr]),
            "FunctionTypeGetReturns": (u32, [ptr, C.POINTER(_ValType), u32]),
            "MemoryInstanceCreate": (ptr, [ptr]),
            "MemoryInstanceGetData": (_Result, [ptr, ptr, u32, u32]),
            "MemoryInstanceSetData": (_Result, [ptr, ptr, u32, u32]),
            "MemoryInstanceGetPageSize": (u32, [ptr]),
            "MemoryInstanceGrowPage": (_Result, [ptr, u32]),
            "CallingFrameGetMemoryInstance": (ptr, [ptr, u32]),
            "ExecutorCreate": (ptr, [ptr, ptr]), "ExecutorDelete": (None, [ptr]),
            "ExecutorInstantiate": (_Result, [ptr, C.POINTER(ptr), ptr, ptr]),
            "ExecutorInvoke": (_Result, [ptr, ptr, val, u32, val, u32]),
            "ValueGenI32": (_Value, [C.c_int32]), "ValueGetI32": (C.c_int32, [_Value]),
            "ValueGenF64": (_Value, [C.c_double]), "ValueGetFuncRef": (ptr, [_Value]),
            "TableInstanceGetData": (_Result, [ptr, val, u32]),
        }
        for name, (result, args) in signatures.items():
            function = getattr(self.lib, "WasmEdge_" + name)
            function.restype, function.argtypes = result, args
            setattr(self, name, function)
        self.version = self.VersionGet().decode()
        if self.version != WASMEDGE_VERSION:
            raise RuntimeUnavailableError(f"WasmEdge version {self.version} at {self.path}; required {WASMEDGE_VERSION}. {_INSTALL}")

    def check(self, result, operation):
        if not self.ResultOK(result):
            raise WasmEdgeError(f"{operation}: {self.ResultGetMessage(result).decode()} (0x{result.Code:x})")


def _name(text):
    encoded = text.encode()
    # ctypes keeps the buffer alive through the Structure's _objects references.
    return _String(len(encoded), C.cast(C.c_char_p(encoded), C.c_void_p))


def _string(value):
    return C.string_at(value.Buf, value.Length).decode()


def _loadable_bytes(data):
    if data[-4:] == b"$REC" and len(data) >= 8:
        size = struct.unpack_from("<I", data, len(data) - 8)[0]
        end = len(data) - 8 - size
        if end < 8 or data[end + 4:end + 8] != b"$REC":
            raise WasmEdgeError("Malformed SDK publication record trailer")
        data = data[:end]
    if data[:8] != b"\0asm\1\0\0\0":
        raise WasmEdgeError("Artifact is not an unencrypted WebAssembly module")
    return data


class Module:
    """Resident WasmEdge instance of a byte-verified packaged SDK artifact.

    ``Module('sgp4')`` and ``Module('propagator/sgp4')`` select packaged bytes.
    A Path or a bytes object loads an explicitly supplied artifact. No network
    access or host filesystem preopens are granted to the guest.
    """
    def __init__(self, artifact: str | Path | Artifact | bytes):
        self._resources = []
        self._callbacks = []
        self._threads = []
        self._thread_errors = []
        self._store_lock = threading.Lock()
        self._invoke_lock = threading.RLock()
        self._closed = False
        self._next_tid = 1
        self.spawned_threads = 0
        self.memory = None
        self._api = _API()
        if isinstance(artifact, str) and not Path(artifact).is_file():
            ids = [name for name in list_artifacts() if name == artifact or name.rsplit("/", 1)[-1] == artifact]
            if len(ids) != 1:
                raise KeyError(f"Unknown module {artifact!r}; choose from {list_artifacts()}")
            artifact = get_artifact(ids[0])
        data = artifact.read_bytes() if isinstance(artifact, (Artifact, Path)) else artifact
        if isinstance(data, str):
            data = Path(data).read_bytes()
        self.artifact_bytes = bytes(data)
        data = _loadable_bytes(self.artifact_bytes)
        self.wasm_bytes = data
        api = self._api
        try:
            self.conf = self._own(api.ConfigureCreate(), api.ConfigureDelete)
            api.ConfigureAddProposal(self.conf, 16)  # WasmEdge_Proposal_Threads in 0.16.4
            api.ConfigureAddProposal(self.conf, 14)  # ExceptionHandling
            self.store = self._own(api.StoreCreate(), api.StoreDelete)
            loader = self._own(api.LoaderCreate(self.conf), api.LoaderDelete)
            self.ast = C.c_void_p()
            source = C.create_string_buffer(data)
            api.check(api.LoaderParseFromBytes(loader, C.byref(self.ast), _Bytes(len(data), C.addressof(source))), "parse artifact")
            self._own(self.ast, api.ASTModuleDelete)
            validator = self._own(api.ValidatorCreate(self.conf), api.ValidatorDelete)
            api.check(api.ValidatorValidate(validator, self.ast), "validate reusable artifact AST")
            self.vm = self._own(api.VMCreate(self.conf, self.store), api.VMDelete)
            self.executor = api.VMGetExecutorContext(self.vm)
            args = (C.c_char_p * 2)(b"spacedatanetwork-astro", b"--serve-plugin-invoke")
            wasi = self._own(api.ModuleInstanceCreateWASI(args, 2, None, 0, None, 0), api.ModuleInstanceDelete)
            self.wasi = wasi
            api.check(api.VMRegisterModuleFromImport(self.vm, wasi), "register WASI preview1")
            self._register_imports()
            api.check(api.VMLoadWasmFromASTModule(self.vm, self.ast), "load artifact")
            api.check(api.VMValidate(self.vm), "validate artifact")
            api.check(api.VMInstantiate(self.vm), "instantiate artifact")
            self.instance = api.VMGetActiveModule(self.vm)
            self.memory = api.ModuleInstanceFindMemory(self.instance, _name("memory")) or self.memory
            if not self.memory:
                raise WasmEdgeError("Module has no imported/exported memory")
            # Mirror SDK browserModuleHarness init: prefer _initialize even
            # when _start is exported (HPOP exports both); otherwise ctors.
            # Calling command _start could consume stdin / exit the process.
            init = "_initialize" if self._find("_initialize") else "__wasm_call_ctors"
            if self._find(init):
                self._call(init)
            for export in ("plugin_alloc", "plugin_free", "plugin_invoke_stream"):
                if not self._find(export):
                    raise WasmEdgeError(f"Module must export {export}")
        except BaseException:
            self.close()
            raise

    def _own(self, context, delete):
        if not context:
            raise WasmEdgeError("WasmEdge could not allocate a context")
        self._resources.append((context, delete))
        return context

    def _register_imports(self):
        api = self._api
        count = api.ASTModuleListImportsLength(self.ast)
        imports = (C.c_void_p * count)()
        api.ASTModuleListImports(self.ast, imports, count)
        modules = {}
        for imp in imports:
            module, name = _string(api.ImportTypeGetModuleName(imp)), _string(api.ImportTypeGetExternalName(imp))
            if module == "wasi_snapshot_preview1":
                typ = api.ImportTypeGetFunctionType(self.ast, imp)
                if name == "fd_seek" and api.FunctionTypeGetParametersLength(typ) == 5:
                    # Legacy Emscripten legalizes i64 as two i32 arguments.
                    # With no preopens, mirror SDK wasiShim's stdio ESPIPE / BADF.
                    @_CALLBACK
                    def seek(_data, _frame, params, outputs):
                        fd = api.ValueGetI32(params[0]) & 0xffffffff
                        outputs[0] = api.ValueGenI32(70 if fd <= 2 else 8)
                        return 0
                    self._callbacks.append(seek)
                    fn = api.FunctionInstanceCreate(typ, seek, None, 0)
                    api.ModuleInstanceAddFunction(self.wasi, _name(name), fn)
                continue
            if module not in ("env", "wasi"):
                raise WasmEdgeError(f"Unsupported host import {module}.{name}; no implicit host capabilities are granted")
            if module not in modules:
                modules[module] = self._own(api.ModuleInstanceCreate(_name(module)), api.ModuleInstanceDelete)
            host = modules[module]
            kind = api.ImportTypeGetExternalType(imp)
            if kind == 2 and module == "env" and name == "memory":
                self.memory = api.MemoryInstanceCreate(api.ImportTypeGetMemoryType(self.ast, imp))
                if not self.memory:
                    raise WasmEdgeError("Could not allocate imported shared memory")
                api.ModuleInstanceAddMemory(host, _name(name), self.memory)
            elif kind == 0:
                typ = api.ImportTypeGetFunctionType(self.ast, imp)
                callback = self._host_callback(module, name, typ)
                self._callbacks.append(callback)
                function = api.FunctionInstanceCreate(typ, callback, None, 0)
                if not function:
                    raise WasmEdgeError(f"Could not bind {module}.{name}")
                api.ModuleInstanceAddFunction(host, _name(name), function)
            else:
                raise WasmEdgeError(f"Unsupported import {module}.{name} (kind {kind})")
        for module, host in modules.items():
            api.check(api.VMRegisterModuleFromImport(self.vm, host), "register " + module)

    def _host_callback(self, module, name, typ):
        api = self._api
        known_void = {"_emscripten_thread_set_strongref", "emscripten_exit_with_live_runtime",
                      "_emscripten_init_main_thread_js", "__emscripten_init_main_thread_js",
                      "_emscripten_thread_mailbox_await", "emscripten_check_blocking_allowed",
                      "_emscripten_thread_cleanup", "__emscripten_thread_cleanup",
                      "_emscripten_notify_mailbox_postmessage"}
        known = known_void | {"_emscripten_receive_on_main_thread_js", "__pthread_create_js",
                              "emscripten_memcpy_js", "emscripten_resize_heap", "__assert_fail", "__cxa_throw", "abort"}
        if not ((module == "env" and name in known) or (module == "wasi" and name == "thread-spawn")):
            raise WasmEdgeError(f"Unsupported host import {module}.{name}")

        @_CALLBACK
        def callback(_data, frame, params, outputs):
            try:
                get = lambda i: api.ValueGetI32(params[i]) & 0xffffffff
                if name in known_void:
                    return 0
                if name == "_emscripten_receive_on_main_thread_js":
                    outputs[0] = api.ValueGenF64(0)
                elif name in ("__assert_fail", "__cxa_throw", "abort"):
                    raise WasmEdgeError(f"Guest called env.{name}")
                elif name == "emscripten_memcpy_js":
                    memory = api.CallingFrameGetMemoryInstance(frame, 0)
                    self._write(get(0), self._read(get(1), get(2), memory), memory)
                    if api.FunctionTypeGetReturnsLength(typ):
                        outputs[0] = api.ValueGenI32(get(0))
                elif name == "emscripten_resize_heap":
                    memory = api.CallingFrameGetMemoryInstance(frame, 0)
                    pages = (get(0) + 65535) // 65536
                    old = api.MemoryInstanceGetPageSize(memory)
                    success = pages <= old or api.ResultOK(api.MemoryInstanceGrowPage(memory, pages - old))
                    outputs[0] = api.ValueGenI32(int(success))
                elif name == "thread-spawn":
                    outputs[0] = api.ValueGenI32(self._spawn("wasi", (get(0),)))
                elif name == "__pthread_create_js":
                    outputs[0] = api.ValueGenI32(self._spawn("emscripten", (get(0), get(2), get(3))))
                return 0
            except BaseException as error:
                self._thread_errors.append(error)
                return 2
        return callback

    def _spawn(self, model, args):
        api = self._api
        executor = api.ExecutorCreate(self.conf, None)
        instance = C.c_void_p()
        try:
            with self._store_lock:
                api.check(api.ExecutorInstantiate(executor, C.byref(instance), self.store, self.ast), "instantiate guest thread")
                tid = self._next_tid
                self._next_tid += 1
            def run():
                try:
                    if model == "wasi":
                        self._call("wasi_thread_start", (tid, args[0]), instance, executor)
                    else:
                        pthread, routine, arg = args
                        # This pinned conjunction artifact's browser adapter
                        # establishStackSpace uses +48/+52. The SDK legacy C
                        # runner's +52/+56 constants describe an older ABI.
                        high = struct.unpack("<I", self._read(pthread + 48, 4))[0]
                        size = struct.unpack("<I", self._read(pthread + 52, 4))[0]
                        if not size or size > high or high > api.MemoryInstanceGetPageSize(self.memory) * 65536:
                            raise WasmEdgeError("Unsupported Emscripten pthread stack layout; rebuild through the pinned SDK")
                        self._call("emscripten_stack_set_limits", (high, high - size), instance, executor)
                        restore = "_emscripten_stack_restore" if self._find("_emscripten_stack_restore", instance) else "stackRestore"
                        self._call(restore, (high,), instance, executor)
                        init = "_emscripten_thread_init" if self._find("_emscripten_thread_init", instance) else "__emscripten_thread_init"
                        self._call(init, (pthread, 0, 0, 1, 0, 0), instance, executor)
                        self._call("_emscripten_tls_init", (), instance, executor)
                        table = api.ModuleInstanceFindTable(instance, _name("__indirect_function_table"))
                        ref = _Value()
                        api.check(api.TableInstanceGetData(table, C.byref(ref), routine), "thread entry lookup")
                        result = self._call_function(api.ValueGetFuncRef(ref), (arg,), executor)
                        exit_name = "_emscripten_thread_exit" if self._find("_emscripten_thread_exit", instance) else "__emscripten_thread_exit"
                        self._call(exit_name, (result or 0,), instance, executor)
                except BaseException as error:
                    self._thread_errors.append(error)
                    crashed = self._find("_emscripten_thread_crashed", instance)
                    if crashed:
                        self._call_function(crashed, (), executor)
                finally:
                    with self._store_lock:
                        api.ModuleInstanceDelete(instance)
                    api.ExecutorDelete(executor)
            thread = threading.Thread(target=run, name=f"wasmedge-guest-{tid}", daemon=True)
            self._threads.append(thread)
            thread.start()
            self.spawned_threads += 1
            return tid if model == "wasi" else 0
        except BaseException:
            if instance:
                api.ModuleInstanceDelete(instance)
            if executor:
                api.ExecutorDelete(executor)
            raise

    def _find(self, name, instance=None):
        return self._api.ModuleInstanceFindFunction(instance or self.instance, _name(name))

    def _call_function(self, function, args, executor=None):
        api = self._api
        if not function:
            raise WasmEdgeError("Missing guest export")
        typ = api.FunctionInstanceGetFunctionType(function)
        arity = api.FunctionTypeGetParametersLength(typ)
        if len(args) != arity:
            raise WasmEdgeError(f"Guest export expects {arity} arguments, got {len(args)}")
        nreturns = api.FunctionTypeGetReturnsLength(typ)
        params = (_Value * len(args))(*(api.ValueGenI32(x) for x in args))
        returns = (_Value * nreturns)()
        api.check(api.ExecutorInvoke(executor or self.executor, function, params, len(args), returns, nreturns), "invoke guest export")
        return (api.ValueGetI32(returns[0]) & 0xffffffff) if nreturns else None

    def _call(self, name, args=(), instance=None, executor=None):
        return self._call_function(self._find(name, instance), args, executor)

    def _read(self, offset, size, memory=None):
        memory = memory or self.memory
        if offset < 0 or size < 0 or offset + size > self._api.MemoryInstanceGetPageSize(memory) * 65536:
            raise WasmEdgeError("Guest memory range is out of bounds")
        buffer = C.create_string_buffer(size)
        self._api.check(self._api.MemoryInstanceGetData(memory, buffer, offset, size), "read guest memory")
        return buffer.raw

    def _write(self, offset, data, memory=None):
        buffer = C.create_string_buffer(data)
        self._api.check(self._api.MemoryInstanceSetData(memory or self.memory, buffer, offset, len(data)), "write guest memory")

    def invoke_bytes(self, request: bytes, *, alignment: int = 8) -> bytes:
        """Execute an already encoded PIV envelope (or module legacy ABI)."""
        if alignment < 8 or alignment > 32768 or alignment & (alignment - 1):
            raise ValueError('Invoke alignment must be a power of two from 8 to 32768')
        with self._invoke_lock:
            if self._closed:
                raise WasmEdgeError("Module is closed")
            allocations = []
            try:
                for size in (len(request) + alignment - 1, 4):
                    ptr = self._call("plugin_alloc", (size,))
                    if not ptr or ptr % 8:
                        raise WasmEdgeError("plugin_alloc returned null or unaligned memory")
                    allocations.append((ptr, size))
                req = (allocations[0][0] + alignment - 1) & -alignment
                out_size = allocations[1][0]
                self._write(req, request)
                self._write(out_size, b"\0" * 4)
                output = self._call("plugin_invoke_stream", (req, len(request), out_size))
                size = struct.unpack("<I", self._read(out_size, 4))[0]
                if output:
                    allocations.append((output, size))
                if not output or output % 8 or not size:
                    raise WasmEdgeError("plugin_invoke_stream returned null, empty, or unaligned response")
                if self._thread_errors:
                    raise WasmEdgeError(f"Guest hostcall/thread failed: {self._thread_errors[-1]}")
                return self._read(output, size)
            finally:
                for ptr, size in reversed(allocations):
                    self._call("plugin_free", (ptr, size))

    def invoke(self, method_id: str, inputs: Sequence[Frame | Mapping] = ()) -> list[Frame]:
        frames = [_frame(value) for value in inputs]
        alignment = max((frame.alignment for frame in frames), default=8)
        return decode_response(self.invoke_bytes(encode_request(method_id, frames), alignment=alignment))

    def close(self):
        # Serialize destruction with invokes and other closers; CDLL releases the GIL.
        with self._invoke_lock:
            if self._closed:
                return
            for thread in self._threads:
                thread.join(timeout=30)
                if thread.is_alive():
                    raise WasmEdgeError("Guest thread did not stop; retain the Module until guest work completes")
            self._closed = True
            # VM must go before imported instances; registration does not transfer
            # ownership. Other contexts are released in reverse creation order.
            vm = getattr(self, "vm", None)
            if vm:
                self._api.VMDelete(vm)
            for context, delete in reversed(self._resources):
                if context != vm:
                    delete(context)
            self._resources.clear()
            self._callbacks.clear()

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self.close()


def frame_stream(frames: Sequence[bytes]) -> bytes:
    """Encode SDK little-endian uint32 size-prefixed FlatBuffer stream frames."""
    chunks = []
    for payload in frames:
        data = bytes(payload)
        if len(data) > 0xffffffff:
            raise ValueError('Frame exceeds uint32 size prefix')
        chunks.extend((struct.pack('<I', len(data)), data))
    return b''.join(chunks)


def unframe_stream(stream: bytes) -> list[bytes]:
    """Decode complete stream frames; reject truncated prefixes and payloads."""
    data = bytes(stream)
    offset, frames = 0, []
    while offset < len(data):
        if len(data) - offset < 4:
            raise ValueError('Truncated FlatBuffer frame size prefix')
        size = struct.unpack_from('<I', data, offset)[0]
        offset += 4
        if size > len(data) - offset:
            raise ValueError('Truncated FlatBuffer frame payload')
        frames.append(data[offset:offset + size])
        offset += size
    return frames
