// The closure gate's cases (owner 2026-10-10: "The fitter (OD) should be
// able to start with the first half of any data and reproduce the second half
// within 1 cm", "using all the different perturbations", "if no maneuvers").
//
// Every case is an ephemeris generated by propagator/hpop with every force it
// carries switched on (EGM2008 70x70, Sun, Moon, Venus, Mars, Jupiter from
// DE440, NRLMSISE-00 or JB2008 drag, cannonball radiation pressure, ECOM2
// above the drag regime, Knocke albedo and infrared, IERS 2010 solid tides,
// FES2004 30x30 ocean tides, IERS 2010 relativity), at RK7(8) 1e-14 with half
// the fitter's step, maneuver free. The parameters are those the fitter
// estimates for the half span: B, AGOM and an in-track term in the drag regime
// (perigee below 2500 km), AGOM and ECOM2 Y0, B0 (and the eight periodic terms
// when the half span is a day or more) above it.
import { RE, stateOf } from './lib/harness.mjs';

// A small deterministic generator (mulberry32), so a seed names a case.
export function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const REGIMES = {
  // perigee below 600 km, drag dominant
  'leo-drag': (u) => ({ a: RE + 380e3 + 200e3 * u(), e: 0.0002 + 0.002 * u(), i: 0.2 + 1.5 * u() }),
  'leo-upper': (u) => ({ a: RE + 900e3 + 900e3 * u(), e: 0.0001 + 0.002 * u(), i: 0.9 + 0.8 * u() }),
  meo: (u) => ({ a: 26560e3 + 2e6 * (u() - 0.5), e: 0.002 + 0.015 * u(), i: 0.9 + 0.2 * u() }),
  geo: (u) => ({ a: 42164e3 + 2e4 * (u() - 0.5), e: 0.0001 + 0.0005 * u(), i: 0.001 + 0.03 * u() }),
  heo: (u) => ({ a: 26560e3, e: 0.70 + 0.04 * u(), i: 1.107 }),
};
const STEPS = [10, 30, 60, 120, 300, 600, 900];

export function makeCase(seed, regime) {
  const u = rng(seed);
  const el = REGIMES[regime](u);
  const state = stateOf({ ...el, raan: 6.28 * u(), argp: 6.28 * u(), nu: 6.28 * u() });
  const period = 2 * Math.PI * Math.sqrt(el.a ** 3 / 3.986004415e14);
  const perigeeKm = (el.a * (1 - el.e) - RE) / 1e3;
  const drag = perigeeKm < 2500;
  // One orbit to 7 days; long LEO spans cost the most, so they are capped
  // where the WASM run would pass an hour (the native sweep covers them).
  const maxSpan = Math.min(7 * 86400, drag ? 2 * 86400 : 7 * 86400);
  const span = Math.round(Math.min(maxSpan, period * (1 + u() * (maxSpan / period - 1))));
  let step = STEPS[Math.floor(u() * STEPS.length)];
  while (span / step < 40) step = STEPS[STEPS.indexOf(step) - 1] ?? 10;
  const half = span / 2;
  const p = drag
    ? { B: 0.005 + 0.03 * u(), AGOM: 0.005 + 0.02 * u(), inTrack: (u() - 0.5) * 2e-8 }
    : { AGOM: 0.005 + 0.02 * u(), ecom2: [0, (u() - 0.5) * 2e-9, (u() - 0.5) * 4e-9, ...Array.from({ length: 8 }, () => (half >= 86400 ? (u() - 0.5) * 2e-9 : 0))] };
  const start = Date.UTC(2026, 6, 5, Math.floor(u() * 24), 0, 0);  // JB2008 lags reach 5 days back
  return { seed, regime, state, drag, jb2008: drag && u() < 0.5, p, span, step, startMs: start, epochIso: new Date(start).toISOString().replace('Z', '') };
}

export const CASES = Object.keys(REGIMES).map((regime, k) => makeCase(1000 + k, regime));
