// Authoritative sources:
// [R] NASA Glenn ideal rocket equation, dv = Isp*g0*ln(m0/mf), and its
// differential momentum law m*dv = -Isp*g0*dm:
// https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/ideal-rocket-equation/
// [F] Orekit LOFType QSW/RTN and VNC axis definitions:
// https://www.orekit.org/site-orekit-12.0.1/apidocs/org/orekit/frames/LOFType.html
// https://raw.githubusercontent.com/CS-SI/Orekit/12.0.1/src/main/java/org/orekit/frames/LOFType.java
// [O] Orekit 13.0.1 ConstantThrustManeuverTest.testRoughBehaviour:
// https://raw.githubusercontent.com/CS-SI/Orekit/13.0.1/src/test/java/org/orekit/forces/maneuvers/ConstantThrustManeuverTest.java
// Except the explicitly described Orekit case: inertial GCRF, epoch
// JD2451545 TDB, elapsed dynamical seconds;
// position km, velocity km/s, mass kg, thrust N, Isp s, g0=9.80665m/s^2.
// Gravity/drag/SRP are disabled to isolate exactly integrable propulsion.
// Derivative and covariance checks independently differentiate [R]; they are
// not numerical goldens generated by the implementation under test.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { createBrowserModuleHarness } from 'space-data-module-sdk/testing';
import { epochJD, base, burn, request, scheduled, orekit, throttled, steered, massCutoff,
  nodeStart, highFlowCutoff, crossingEvents, frames, frameParams, covarianceCase, invalidCases } from './finite-burn-fixture.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../plugin-manifest.json',import.meta.url)));
const wasm=fs.readFileSync(new URL('../dist/isomorphic/module.wasm',import.meta.url));
const g0=9.80665;
const decode=response=>JSON.parse(Buffer.from(response.outputs.find(o=>o.portId==='response').payload).toString());
async function harness(t) {
  const h=await createBrowserModuleHarness({wasmSource:wasm,manifest,surface:'command'});
  t.after(()=>h.destroy());return h;
}
async function raw(h,params) {
  const req=request(params);
  for(const input of req.inputs) input.payload=Buffer.from(input.payloadHex,'hex');
  return h.invoke(req);
}
async function invoke(h,params) {
  const result=await raw(h,params);assert.equal(result.statusCode,0,result.errorMessage);
  return decode(result);
}
function close(name,actual,expected,tolerance) {
  const error=Math.abs(actual-expected);
  assert.ok(Number.isFinite(error)&&error<=tolerance,`${name}: error=${error}, tolerance=${tolerance}, actual=${actual}, expected=${expected}`);
  return error;
}
const norm=a=>Math.hypot(...a);
const unit=a=>a.map(v=>v/norm(a));
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];

test('WASM finite orbit agrees with Orekit published ConstantThrustManeuver example',async t=>{
  const h=await harness(t),out=await invoke(h,orekit);
  // [O] uses EME2000 and 2004-01-01T23:30:00 UTC. This autonomous
  // point-mass problem preserves that numerical inertial basis with JD2451545
  // as a computational origin and identical elapsed seconds. No EME2000/GCRF
  // or UTC/TDB conversion is being tested or inferred from this case.
  const inclination=Math.acos(unit(cross(out.position,out.velocity))[2])*180/Math.PI;
  const semimajor=1/(2/norm(out.position)-norm(out.velocity)**2/398600.47);
  const massError=close('Orekit mass kg',out.massKg,2007.8824544261233,1e-8);
  const inclinationError=close('Orekit inclination deg',inclination,2.6872,1e-4);
  const semimajorError=close('Orekit semimajor km',semimajor,28970,1);
  // Inclination/a tolerances are exactly Orekit's published rounded-value
  // bounds. Mass is exact linear flow; 1e-8kg permits RK summation roundoff.
  console.log(`PASS WASM Orekit mass_error_kg=${massError} inclination_error_deg=${inclinationError} semimajor_error_km=${semimajorError}`);
});

test('WASM finite thrust and throttle agree with exact NASA mass and rocket equations',async t=>{
  const h=await harness(t);let massError=0,dvError=0;
  for(const [name,params,area] of [['constant',scheduled,100],['throttled',throttled,60]]) {
    // Throttle area: 20*1 + 40*.5 + 20*0 + 20*1 = 60 s. All edges
    // deliberately miss the 17-second nominal step grid.
    const out=await invoke(h,params),mf=1000-12*area/(300*g0),dv=300*g0*Math.log(1000/mf)/1000;
    massError=Math.max(massError,close(`${name} mass kg`,out.massKg,mf,1e-8));
    dvError=Math.max(dvError,close(`${name} delta-V km/s`,out.burnSummary[0].deltaVKmS,dv,1e-11));
    close(`${name} propellant kg`,out.burnSummary[0].propellantKg,1000-mf,1e-8);
    close(`${name} inertial vx km/s`,out.velocity[0]-base.velocity[0],dv,1e-11);
    close(`${name} inertial vy km/s`,out.velocity[1],base.velocity[1],1e-12);
    assert.equal(out.burnSummary[0].startSeconds,10);assert.equal(out.burnSummary[0].stopSeconds,110);
    assert.equal(out.burnSummary[0].started,true);assert.equal(out.burnSummary[0].stopped,true);
    assert.equal(out.frame,'GCRF');assert.equal(out.epochTimeScale,'TDB');assert.equal(out.massUnits,'kg');
  }
  // 1e-8kg / 1e-11km/s allow double-precision RK accumulation and are
  // far below the .4kg / 1.2m/s effects. They are numerical, not model bounds.
  console.log(`PASS WASM NASA rocket throttle mass_max_error_kg=${massError} deltaV_max_error_km_s=${dvError}`);
});

test('WASM acceleration mode and original-epoch linear steering match elementary integrals',async t=>{
  const h=await harness(t),out=await invoke(h,steered);
  const a=1e-5,k=.003,start=10,stop=110;
  // Integrate a*normalize([1,k*t,0]) between start and stop. This checks
  // that steering uses seconds from the original epoch, not burn-relative time.
  const dx=a*(Math.asinh(k*stop)-Math.asinh(k*start))/k;
  const dy=a*(Math.sqrt(1+(k*stop)**2)-Math.sqrt(1+(k*start)**2))/k;
  const error=Math.max(close('steered dvx km/s',out.velocity[0]-base.velocity[0],dx,1e-11),
    close('steered dvy km/s',out.velocity[1]-base.velocity[1],dy,1e-11));
  const fraction=Math.exp(-1000*a*(stop-start)/(300*g0));
  const massError=close('constant acceleration mass kg',out.massKg,1000*fraction,1e-8);
  close('constant acceleration Phi_mm',out.stm7[48],fraction,1e-11);
  close('constant acceleration Phi_vx,m',out.stm7[27],0,1e-12);
  close('constant acceleration integrated scalar dv',out.burnSummary[0].deltaVKmS,a*(stop-start),1e-12);
  console.log(`PASS WASM elementary steering velocity_max_error_km_s=${error} exponential_mass_error_kg=${massError}`);
});

test('WASM all finite-burn frames match independent Orekit axis definitions',async t=>{
  const h=await harness(t),R=unit(base.position),N=unit(cross(base.position,base.velocity)),T=cross(N,R);
  const V=unit(base.velocity),C=cross(V,N),d=unit([.4,.8,-.2]);let maximum=0;
  const basis=(x,y,z)=>x.map((_,i)=>x[i]*d[0]+y[i]*d[1]+z[i]*d[2]);
  const expected={INERTIAL:d,RTN:basis(R,T,N),LVLH:basis(R,T,N),VNC:basis(V,N,C),VELOCITY:V,ANTI_VELOCITY:V.map(x=>-x)};
  let rtn;
  for(const frame of frames) {
    const out=await invoke(h,frameParams(frame));
    const direction=out.velocity.map((v,i)=>(v-base.velocity[i])/1e-6);
    const error=norm(direction.map((v,i)=>v-expected[frame][i]));maximum=Math.max(maximum,error);
    // The frame moves during this .01s pulse: 2e-5 relative direction allows
    // O(duration) basis rotation, while still detecting axis swaps/sign errors.
    assert.ok(error<2e-5,`${frame}: direction error=${error}`);
    if(frame==='RTN')rtn=out;
    if(frame==='LVLH')assert.deepEqual(out,rtn);
  }
  console.log(`PASS WASM all six frame names direction_max_error=${maximum} tolerance=2e-5`);
});

test('WASM seven-state mass partials and covariance preserve the rocket-equation derivative',async t=>{
  const h=await harness(t),out=await invoke(h,covarianceCase),mf=1000-12*100/(300*g0);
  const derivative=300*g0/1000*(1/1000-1/mf);
  // Direct derivative of [R] at fixed burn duration. For a mass-only initial
  // variance of 4kg², velocity variance is 4*(dv/dm0)², independently of Phi.
  const partialError=close('Phi_vx,m km/s/kg',out.stm7[27],derivative,1e-12);
  close('Phi_mm',out.stm7[48],1,1e-12);
  close('P_vx,vx km²/s²',out.covariance7[24],4*derivative**2,1e-20);
  assert.equal(out.stm7.length,49);assert.equal(out.stm.length,36);
  for(let i=0;i<7;i++)for(let j=0;j<7;j++) {
    close(`covariance7[${i},${j}]`,out.covariance7[i*7+j],4*out.stm7[i*7+6]*out.stm7[j*7+6],1e-20+Math.abs(out.covariance7[i*7+j])*1e-13);
    assert.equal(out.samples[0].stm7[i*7+j],i===j?1:0);
    if(i<6&&j<6)assert.equal(out.stm[i*6+j],out.stm7[i*7+j]);
  }
  assert.deepEqual(out.samples.at(-1).stm7,out.stm7);
  assert.deepEqual(out.samples.at(-1).burnSummary,out.burnSummary);
  console.log(`PASS WASM STM7 mass-column covariance samples partial_error_km_s_kg=${partialError} tolerance=1e-12`);
});

test('WASM event cutoff and event start preserve exact elapsed-time and mass sensitivities',async t=>{
  const h=await harness(t),out=await invoke(h,massCutoff),stop=(1000-997)*300*g0/100;
  const dv=300*g0*Math.log(1000/997)/1000;
  const stopError=close('mass event stop seconds',out.burnSummary[0].stopSeconds,stop,1e-7);
  close('mass event final kg',out.massKg,997,1e-8);
  close('mass event scalar dv km/s',out.burnSummary[0].deltaVKmS,dv,1e-11);
  // Fixed final-mass cutoff: dmf/dm0=0 and d(dv)/dm0=Isp*g0/m0,
  // which differs in sign from the scheduled-burn derivative above. This
  // independently detects omission of the event-time (saltation) correction.
  const error=close('event Phi_vx,m km/s/kg',out.stm7[27],300*g0/1e6,1e-11);
  close('event Phi_mm',out.stm7[48],0,1e-10);
  const started=await invoke(h,nodeStart);
  close('node event start seconds',started.burnSummary[0].startSeconds,100,1e-7);
  close('node event final mass kg',started.massKg,1000-12*100/(300*g0),1e-8);
  assert.equal(started.burnSummary[0].startByEvent,true);
  assert.equal(out.burnSummary[0].stopByEvent,true);
  // A trial RK stage beyond t=1s would have negative mass; event clipping
  // must find the physically valid .5s cutoff before that stage is attempted.
  const high=await invoke(h,highFlowCutoff);
  close('high-flow cutoff seconds',high.burnSummary[0].stopSeconds,.5,1e-8);
  close('high-flow mass kg',high.massKg,.5,1e-9);
  close('high-flow dv km/s',high.burnSummary[0].deltaVKmS,100*g0*Math.log(2)/1000,1e-10);
  for(const {kind,params} of crossingEvents) {
    const event=await invoke(h,params);
    assert.equal(event.burnSummary[0].stopByEvent,true,kind);
    assert.ok(event.burnSummary[0].stopSeconds<200,`${kind}: must cross before scheduled stop`);
  }
  console.log(`PASS WASM events stop_time_error_s=${stopError} saltation_mass_partial_error=${error}`);
});

test('WASM epoch burn edges and omitted includeSTM retain full finite-burn state',async t=>{
  const h=await harness(t),startJD=epochJD+10/86400,stopJD=epochJD+110/86400;
  const out=await invoke(h,{...scheduled,includeSTM:false,finiteBurns:[{...burn,
    startSeconds:undefined,stopSeconds:undefined,startJD,stopJD}]});
  // Use represented binary-JD duration, so this is not a false ~20us timing
  // discrepancy with the seconds-based fixture.
  const duration=(stopJD-startJD)*86400;
  close('JD-defined mass kg',out.massKg,1000-12*duration/(300*g0),1e-8);
  assert.equal(out.stm7.length,49);assert.equal(out.STM_METHOD,'ANALYTIC');
  console.log('PASS WASM JD-defined burn edges and automatic finite STM');
});

test('WASM invalid finite-burn controls return named errors and recover',async t=>{
  const h=await harness(t);
  for(const [name,params] of invalidCases) {
    const response=await raw(h,params);
    assert.notEqual(response.statusCode,0,name);assert.equal(response.errorCode,'invoke-failed',name);
    assert.ok(response.errorMessage?.length>0,`${name}: missing diagnostic`);
  }
  const success=await invoke(h,{...scheduled,targetJD:epochJD});
  assert.equal(success.massKg,1000);assert.equal(success.burnSummary[0].started,false);
  console.log(`PASS WASM negative controls=${invalidCases.length} same-instance recovery`);
});
