import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { createRequire } from 'node:module';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { createBrowserModuleHarness } from 'space-data-module-sdk/host/browser-module';
import { validateArtifactWithStandards } from 'space-data-module-sdk/compliance';

// Fixture: a slice of the real Launch Library 2 response to
// GET /2.3.0/launches/upcoming/?mode=normal&limit=100 recorded 2026-09-28,
// one launch per NET precision class (second, minute, day, month, quarter,
// half year, year). Expected windows are calendar arithmetic on the recorded
// NETs, computed by hand below; nothing is generated by the module under test.
const root = process.env.SPACE_DATA_STANDARDS_ROOT ?? path.dirname(createRequire(import.meta.url).resolve('spacedatastandards.org/package.json'));
const require = createRequire(path.join(root, 'package.json'));
const { ByteBuffer } = require('flatbuffers');
const { LDM } = await import(pathToFileURL(path.join(root, 'lib/js/LDM/main.js')));
const wasmPath = fileURLToPath(new URL('../dist/isomorphic/module.wasm', import.meta.url));
const manifest = JSON.parse(fs.readFileSync(new URL('../plugin-manifest.json', import.meta.url)));
const wasm = fs.readFileSync(wasmPath);
const recorded = JSON.parse(fs.readFileSync(new URL('./fixtures/ll2-upcoming-2026-09-28.json', import.meta.url)));
const receipt = { retrieved_at_ms: 1790600400000, producer_peer_id: '16Uiu2HAm1apfD3rAJJjgx4AC5Ms3PejRBwoqEsKpRx36uYwXuW9h' };
const config = { access: 'anonymous', limit: 100 };

function http(value, status = 200) {
  const bytes = Buffer.from(typeof value === 'string' ? value : JSON.stringify(value));
  const header = Buffer.alloc(8); header.write('$HRB'); header.writeInt32LE(status, 4);
  return Buffer.concat([header, bytes]);
}
function input(portId, value) {
  const payload = value instanceof Uint8Array ? value : Buffer.from(JSON.stringify(value));
  return { portId, payload, typeRef: { wireFormat: 'aligned-binary', requiredAlignment: 1, byteLength: payload.length } };
}
const decode = (result, port) => JSON.parse(Buffer.from(result.outputs.find((f) => f.portId === port).payload).toString());
async function harness(t) {
  const h = await createBrowserModuleHarness({ wasmSource: wasm, manifest, surface: 'direct' });
  t.after(() => h.destroy());
  return h;
}
async function planned(h, value = config) {
  return h.invoke({ methodId: 'plan_launches', inputs: [input('config', value)] });
}
async function parse(h, job, body = recorded, status = 200, receiptValue = receipt) {
  return h.invoke({ methodId: 'parse_launches', inputs: [input('job', job), input('response', http(body, status)), input('receipt', receiptValue)] });
}
function records(result) {
  const bytes = result.outputs.find((f) => f.portId === 'records').payload, rows = [];
  for (let offset = 0; offset < bytes.length;) {
    const size = new DataView(bytes.buffer, bytes.byteOffset + offset, 4).getUint32(0, true) + 4;
    const frame = bytes.slice(offset, offset + size);
    assert.equal(Buffer.from(frame.slice(8, 12)).toString(), '$LDM');
    rows.push(LDM.getSizePrefixedRootAsLDM(new ByteBuffer(frame)).unpack());
    offset += size;
  }
  return rows;
}

test('the artifact satisfies the SDK contract', async () => {
  const report = await validateArtifactWithStandards({ wasmPath, manifest, standardsRoot: root });
  assert.equal(report.ok, true, JSON.stringify(report.issues));
});

test('plans one bounded anonymous GET and refuses other access tiers', async (t) => {
  const h = await harness(t);
  const result = await planned(h);
  assert.equal(result.statusCode, 0, result.errorMessage);
  const url = new URL(decode(result, 'request').url);
  assert.equal(url.hostname, 'll.thespacedevs.com');
  assert.equal(url.pathname, '/2.3.0/launches/upcoming/');
  assert.equal(url.searchParams.get('mode'), 'normal');
  assert.equal(url.searchParams.get('limit'), '100');
  assert.equal(decode(result, 'request').responseWire, 'raw-body-v1');
  for (const bad of [{}, { access: 'supporter' }, { ...config, limit: 0 }, { ...config, limit: 101 }, { ...config, limit: 2.5 }]) {
    const refused = await planned(h, bad);
    assert.notEqual(refused.statusCode, 0);
    assert.equal(refused.outputs.length, 0);
  }
});

test('turns each NET precision into the window it states', async (t) => {
  const h = await harness(t);
  const job = decode(await planned(h), 'job');
  const result = await parse(h, job);
  assert.equal(result.statusCode, 0, result.errorMessage);
  const rows = records(result);
  assert.equal(rows.length, 7);
  const byId = Object.fromEntries(rows.map((r) => [r.ID, r]));
  // [id, NET, earliest, latest]. Second/minute precision keeps the published
  // window; calendar precisions span the whole stated period (Gregorian
  // month lengths; Q4 = Oct-Dec; H2 = Jul-Dec).
  const expected = [
    ['7d1afb26-6f9c-429b-9ccf-29012fd1e519', '2026-09-28T12:48:59Z', '2026-09-28T12:15:00Z', '2026-09-28T13:30:00Z'],
    ['67213393-7983-4c06-8b44-b8c785a5ed79', '2026-10-01T18:18:00Z', '2026-10-01T18:18:00Z', '2026-10-01T19:16:00Z'],
    ['6b89cfc8-8880-4b5b-856c-0e547d45b639', '2026-10-05T00:00:00Z', '2026-10-05T00:00:00Z', '2026-10-05T23:59:59Z'],
    ['7bdc412b-c965-4517-a131-f57a01189803', '2026-10-01T00:00:00Z', '2026-10-01T00:00:00Z', '2026-10-31T23:59:59Z'],
    ['0b85fcca-5252-48d7-9ccb-c10b1da9d183', '2026-10-01T00:00:00Z', '2026-10-01T00:00:00Z', '2026-12-31T23:59:59Z'],
    ['e61d353c-db55-4a57-8184-0fab187231e6', '2026-07-01T00:00:00Z', '2026-07-01T00:00:00Z', '2026-12-31T23:59:59Z'],
    ['b78857c4-3b8d-4462-929e-bc76f39c0e6d', '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z', '2026-12-31T23:59:59Z'],
  ];
  for (const [id, net, earliest, latest] of expected) {
    const row = byId[id];
    assert.ok(row, id);
    assert.equal(row.NET, net, id);
    assert.deepEqual(row.EARLIEST_LAUNCH_TIMES, [earliest], id);
    assert.deepEqual(row.LATEST_LAUNCH_TIMES, [latest], id);
  }
  const starship = byId['7d1afb26-6f9c-429b-9ccf-29012fd1e519'];
  // float32 site coordinates: 1e-5 deg (about 1 m) covers the rounding.
  assert.ok(Math.abs(starship.SITE.LATITUDE - 25.99677) < 1e-5);
  assert.ok(Math.abs(starship.SITE.LONGITUDE - -97.15799) < 1e-5);
  assert.equal(starship.AGENCY_NAME, 'SpaceX');
  assert.equal(starship.ROCKET_CONFIGURATION.NAME, 'Starship V3');
  assert.equal(starship.ORBIT_TYPE, 'LEO');
  assert.equal(starship.REFERENCES, recorded.results[0].url);
  const report = decode(result, 'report');
  assert.deepEqual([report.records, report.skipped_imprecise, report.registry_count], [7, 0, 367]);
  assert.equal(decode(result, 'meta').reconcile, 'current');
});

test('skips a launch whose precision it cannot turn into a window', async (t) => {
  const h = await harness(t);
  const job = decode(await planned(h), 'job');
  const body = structuredClone(recorded);
  body.results[6].net_precision = { id: 13, name: 'Decade', abbrev: 'DEC' };
  const result = await parse(h, job, body);
  assert.equal(result.statusCode, 0, result.errorMessage);
  assert.equal(records(result).length, 6);
  assert.equal(decode(result, 'report').skipped_imprecise, 1);
});

test('rejects failed or malformed responses atomically', async (t) => {
  const h = await harness(t);
  const job = decode(await planned(h), 'job');
  for (const status of [304, 429, 500]) assert.notEqual((await parse(h, job, recorded, status)).statusCode, 0);
  const broken = [
    (b) => { b.results[0].id = 'not-a-uuid'; },
    (b) => { b.results[1].window_end = '2026-10-01T18:00:00Z'; },
    (b) => { b.results[2].pad.latitude = 91; },
    (b) => { b.results[3].net = '2026-10-31'; },
    (b) => { delete b.results; },
  ];
  for (const mutate of broken) {
    const body = structuredClone(recorded);
    mutate(body);
    const result = await parse(h, job, body);
    assert.notEqual(result.statusCode, 0);
    assert.equal(result.outputs.length, 0);
  }
  assert.notEqual((await parse(h, { ...job, source_url: 'https://other.example/' })).statusCode, 0);
  assert.notEqual((await parse(h, job, recorded, 200, { ...receipt, producer_peer_id: '' })).statusCode, 0);
  assert.equal((await parse(h, job)).statusCode, 0);
});
