# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

# Whether a component's g is safe to refine, and with which method. A locator
# that lies here produces roots that look converged and are not, which is why
# it is declared per component rather than assumed for the family.
class ComponentContinuity(object):
    # g is C1 in epoch. Brent is valid.
    SMOOTH = 0
    # g is continuous but its derivative jumps (a piecewise mask, a
    # multi-body minimum). Bracketing methods are valid; interpolation is not
    # guaranteed to help, and the runner falls back to bisection.
    PIECEWISE = 1
    # g steps between levels and has no root in the analytic sense (a discrete
    # count, an enumerated state). The runner reports the STEP epoch to within
    # the scan step and marks it DISCONTINUOUS; it never refines it.
    DISCRETE = 2
