# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The interval to scan, and the filter applied to what is found. 56 bytes,
# 8-byte aligned.
#
# EPOCHS ARE SPLIT PAIRS: `*_jd_day` is an exactly-representable Julian day
# (an integer, or an integer + 0.5) and `*_seconds` is the offset from it in
# seconds. Do not collapse them into one double before comparing — that is
# the forty-microsecond quantization this pair exists to avoid.
#
# BACKWARD PROPAGATION IS NOT A MODE. It is `stop` earlier than `start`. The
# runner steps negatively, the consumer's propagator is asked for earlier
# epochs, and every hit carries `BACKWARD`. There is no second code path to
# keep in agreement with the first.
class EventInterval(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 56

    # EventInterval
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Scan start: exactly-representable Julian day.
    # EventInterval
    def StartJdDay(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Scan start: seconds from `start_jd_day`.
    # EventInterval
    def StartSeconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Scan end: exactly-representable Julian day. May be EARLIER than the
    # start — that is backward propagation.
    # EventInterval
    def StopJdDay(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Scan end: seconds from `stop_jd_day`.
    # EventInterval
    def StopSeconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # Stop after this many qualifying hits. 0 = unbounded (bounded only by the
    # caller's hit buffer and by `max_evaluations`).
    # EventInterval
    def MaxEvents(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # Hard cap on g evaluations for the whole scan, so a pathological
    # configuration terminates with `TRUNCATED` instead of running forever.
    # 0 = unbounded.
    # EventInterval
    def MaxEvaluations(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(36))
    # Report only the Nth qualifying crossing, 1-based. 0 = report all. This is
    # GMAT's "which occurrence" on a stopping condition, and it counts
    # crossings that pass the direction filter, not raw sign changes.
    # EventInterval
    def Occurrence(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))
    # Restrict the scan to one component index. 0xFFFFFFFF = every component.
    # EventInterval
    def Component(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(44))
    # EventFlags bitfield. Input flags are advisory; the runner ORs its own
    # findings into each hit's flags.
    # EventInterval
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))
    # Crossing-direction filter applied to every component.
    # EventInterval
    def Direction(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(52))

def CreateEventInterval(builder, startJdDay, startSeconds, stopJdDay, stopSeconds, maxEvents, maxEvaluations, occurrence, component, flags, direction):
    builder.Prep(8, 56)
    builder.Pad(3)
    builder.PrependInt8(direction)
    builder.PrependUint32(flags)
    builder.PrependUint32(component)
    builder.PrependUint32(occurrence)
    builder.PrependUint32(maxEvaluations)
    builder.PrependUint32(maxEvents)
    builder.PrependFloat64(stopSeconds)
    builder.PrependFloat64(stopJdDay)
    builder.PrependFloat64(startSeconds)
    builder.PrependFloat64(startJdDay)
    return builder.Offset()


class EventIntervalT(object):

    # EventIntervalT
    def __init__(
        self,
        startJdDay = 0.0,
        startSeconds = 0.0,
        stopJdDay = 0.0,
        stopSeconds = 0.0,
        maxEvents = 0,
        maxEvaluations = 0,
        occurrence = 0,
        component = 0,
        flags = 0,
        direction = 0,
    ):
        self.startJdDay = startJdDay  # type: float
        self.startSeconds = startSeconds  # type: float
        self.stopJdDay = stopJdDay  # type: float
        self.stopSeconds = stopSeconds  # type: float
        self.maxEvents = maxEvents  # type: int
        self.maxEvaluations = maxEvaluations  # type: int
        self.occurrence = occurrence  # type: int
        self.component = component  # type: int
        self.flags = flags  # type: int
        self.direction = direction  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        eventInterval = EventInterval()
        eventInterval.Init(buf, pos)
        return cls.InitFromObj(eventInterval)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, eventInterval):
        x = EventIntervalT()
        x._UnPack(eventInterval)
        return x

    # EventIntervalT
    def _UnPack(self, eventInterval):
        if eventInterval is None:
            return
        self.startJdDay = eventInterval.StartJdDay()
        self.startSeconds = eventInterval.StartSeconds()
        self.stopJdDay = eventInterval.StopJdDay()
        self.stopSeconds = eventInterval.StopSeconds()
        self.maxEvents = eventInterval.MaxEvents()
        self.maxEvaluations = eventInterval.MaxEvaluations()
        self.occurrence = eventInterval.Occurrence()
        self.component = eventInterval.Component()
        self.flags = eventInterval.Flags()
        self.direction = eventInterval.Direction()

    # EventIntervalT
    def Pack(self, builder):
        return CreateEventInterval(builder, self.startJdDay, self.startSeconds, self.stopJdDay, self.stopSeconds, self.maxEvents, self.maxEvaluations, self.occurrence, self.component, self.flags, self.direction)
