# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# What `plugin_event_describe` returns. A consumer reads this BEFORE
# configuring, so a generic runner can present any locator's controls without
# knowing the locator.
class EventLocatorDescription(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventLocatorDescription()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventLocatorDescription(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventLocatorDescription
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Capability class of the locator (shadow-crossing, station-access,
    # field-of-view-intrusion, orbit-apsis, node-crossing, parameter-stop).
    # Capability classes only; never a vendor or organization name.
    # EventLocatorDescription
    def LocatorClass(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The locator module's own version string.
    # EventLocatorDescription
    def LocatorVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Objects this locator needs states for, in the order
    # `plugin_event_supply` expects them.
    # EventLocatorDescription
    def ObjectCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Every component this locator can offer, before configuration narrows it.
    # EventLocatorDescription
    def Components(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.orbpro.events.EventComponent import EventComponent
            obj = EventComponent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventLocatorDescription
    def ComponentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventLocatorDescription
    def ComponentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # The parameter keys this locator accepts, with their defaults.
    # EventLocatorDescription
    def AcceptedParameters(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spacedatanetwork_astro.invoke.orbpro.events.EventParameter import EventParameter
            obj = EventParameter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EventLocatorDescription
    def AcceptedParametersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventLocatorDescription
    def AcceptedParametersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # The policy the locator recommends for its own geometry. A consumer may
    # override it; a consumer that does NOT set one gets this.
    # EventLocatorDescription
    def DefaultPolicy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            from spacedatanetwork_astro.invoke.orbpro.events.RootPolicy import RootPolicy
            obj = RootPolicy()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # The largest scan step, SECONDS, at which this locator claims not to miss
    # an event. 0 means the locator declines to bound it, which a conformance
    # kit records as a named gap.
    # EventLocatorDescription
    def MaxSafeScanStepSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def EventLocatorDescriptionStart(builder):
    builder.StartObject(7)

def Start(builder):
    EventLocatorDescriptionStart(builder)

def EventLocatorDescriptionAddLocatorClass(builder, locatorClass):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(locatorClass), 0)

def AddLocatorClass(builder, locatorClass):
    EventLocatorDescriptionAddLocatorClass(builder, locatorClass)

def EventLocatorDescriptionAddLocatorVersion(builder, locatorVersion):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(locatorVersion), 0)

def AddLocatorVersion(builder, locatorVersion):
    EventLocatorDescriptionAddLocatorVersion(builder, locatorVersion)

def EventLocatorDescriptionAddObjectCount(builder, objectCount):
    builder.PrependUint32Slot(2, objectCount, 0)

def AddObjectCount(builder, objectCount):
    EventLocatorDescriptionAddObjectCount(builder, objectCount)

def EventLocatorDescriptionAddComponents(builder, components):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(components), 0)

def AddComponents(builder, components):
    EventLocatorDescriptionAddComponents(builder, components)

def EventLocatorDescriptionStartComponentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartComponentsVector(builder, numElems):
    return EventLocatorDescriptionStartComponentsVector(builder, numElems)

def EventLocatorDescriptionCreateComponentsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateComponentsVector(builder, data):
    EventLocatorDescriptionCreateComponentsVector(builder, data)

def EventLocatorDescriptionAddAcceptedParameters(builder, acceptedParameters):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(acceptedParameters), 0)

def AddAcceptedParameters(builder, acceptedParameters):
    EventLocatorDescriptionAddAcceptedParameters(builder, acceptedParameters)

def EventLocatorDescriptionStartAcceptedParametersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAcceptedParametersVector(builder, numElems):
    return EventLocatorDescriptionStartAcceptedParametersVector(builder, numElems)

def EventLocatorDescriptionCreateAcceptedParametersVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateAcceptedParametersVector(builder, data):
    EventLocatorDescriptionCreateAcceptedParametersVector(builder, data)

def EventLocatorDescriptionAddDefaultPolicy(builder, defaultPolicy):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(defaultPolicy), 0)

def AddDefaultPolicy(builder, defaultPolicy):
    EventLocatorDescriptionAddDefaultPolicy(builder, defaultPolicy)

def EventLocatorDescriptionAddMaxSafeScanStepSeconds(builder, maxSafeScanStepSeconds):
    builder.PrependFloat64Slot(6, maxSafeScanStepSeconds, 0.0)

def AddMaxSafeScanStepSeconds(builder, maxSafeScanStepSeconds):
    EventLocatorDescriptionAddMaxSafeScanStepSeconds(builder, maxSafeScanStepSeconds)

def EventLocatorDescriptionEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventLocatorDescriptionEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.events.EventComponent
import spacedatanetwork_astro.invoke.orbpro.events.EventParameter
import spacedatanetwork_astro.invoke.orbpro.events.RootPolicy
try:
    from typing import List, Optional
except:
    pass

class EventLocatorDescriptionT(object):

    # EventLocatorDescriptionT
    def __init__(
        self,
        locatorClass = None,
        locatorVersion = None,
        objectCount = 0,
        components = None,
        acceptedParameters = None,
        defaultPolicy = None,
        maxSafeScanStepSeconds = 0.0,
    ):
        self.locatorClass = locatorClass  # type: Optional[str]
        self.locatorVersion = locatorVersion  # type: Optional[str]
        self.objectCount = objectCount  # type: int
        self.components = components  # type: Optional[List[orbpro.events.EventComponent.EventComponentT]]
        self.acceptedParameters = acceptedParameters  # type: Optional[List[orbpro.events.EventParameter.EventParameterT]]
        self.defaultPolicy = defaultPolicy  # type: Optional[orbpro.events.RootPolicy.RootPolicyT]
        self.maxSafeScanStepSeconds = maxSafeScanStepSeconds  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        eventLocatorDescription = EventLocatorDescription()
        eventLocatorDescription.Init(buf, pos)
        return cls.InitFromObj(eventLocatorDescription)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, eventLocatorDescription):
        x = EventLocatorDescriptionT()
        x._UnPack(eventLocatorDescription)
        return x

    # EventLocatorDescriptionT
    def _UnPack(self, eventLocatorDescription):
        if eventLocatorDescription is None:
            return
        self.locatorClass = eventLocatorDescription.LocatorClass()
        self.locatorVersion = eventLocatorDescription.LocatorVersion()
        self.objectCount = eventLocatorDescription.ObjectCount()
        if not eventLocatorDescription.ComponentsIsNone():
            self.components = []
            for i in range(eventLocatorDescription.ComponentsLength()):
                if eventLocatorDescription.Components(i) is None:
                    self.components.append(None)
                else:
                    eventComponent_ = spacedatanetwork_astro.invoke.orbpro.events.EventComponent.EventComponentT.InitFromObj(eventLocatorDescription.Components(i))
                    self.components.append(eventComponent_)
        if not eventLocatorDescription.AcceptedParametersIsNone():
            self.acceptedParameters = []
            for i in range(eventLocatorDescription.AcceptedParametersLength()):
                if eventLocatorDescription.AcceptedParameters(i) is None:
                    self.acceptedParameters.append(None)
                else:
                    eventParameter_ = spacedatanetwork_astro.invoke.orbpro.events.EventParameter.EventParameterT.InitFromObj(eventLocatorDescription.AcceptedParameters(i))
                    self.acceptedParameters.append(eventParameter_)
        if eventLocatorDescription.DefaultPolicy() is not None:
            self.defaultPolicy = spacedatanetwork_astro.invoke.orbpro.events.RootPolicy.RootPolicyT.InitFromObj(eventLocatorDescription.DefaultPolicy())
        self.maxSafeScanStepSeconds = eventLocatorDescription.MaxSafeScanStepSeconds()

    # EventLocatorDescriptionT
    def Pack(self, builder):
        if self.locatorClass is not None:
            locatorClass = builder.CreateString(self.locatorClass)
        if self.locatorVersion is not None:
            locatorVersion = builder.CreateString(self.locatorVersion)
        if self.components is not None:
            componentslist = []
            for i in range(len(self.components)):
                componentslist.append(self.components[i].Pack(builder))
            EventLocatorDescriptionStartComponentsVector(builder, len(self.components))
            for i in reversed(range(len(self.components))):
                builder.PrependUOffsetTRelative(componentslist[i])
            components = builder.EndVector()
        if self.acceptedParameters is not None:
            acceptedParameterslist = []
            for i in range(len(self.acceptedParameters)):
                acceptedParameterslist.append(self.acceptedParameters[i].Pack(builder))
            EventLocatorDescriptionStartAcceptedParametersVector(builder, len(self.acceptedParameters))
            for i in reversed(range(len(self.acceptedParameters))):
                builder.PrependUOffsetTRelative(acceptedParameterslist[i])
            acceptedParameters = builder.EndVector()
        EventLocatorDescriptionStart(builder)
        if self.locatorClass is not None:
            EventLocatorDescriptionAddLocatorClass(builder, locatorClass)
        if self.locatorVersion is not None:
            EventLocatorDescriptionAddLocatorVersion(builder, locatorVersion)
        EventLocatorDescriptionAddObjectCount(builder, self.objectCount)
        if self.components is not None:
            EventLocatorDescriptionAddComponents(builder, components)
        if self.acceptedParameters is not None:
            EventLocatorDescriptionAddAcceptedParameters(builder, acceptedParameters)
        if self.defaultPolicy is not None:
            defaultPolicy = self.defaultPolicy.Pack(builder)
            EventLocatorDescriptionAddDefaultPolicy(builder, defaultPolicy)
        EventLocatorDescriptionAddMaxSafeScanStepSeconds(builder, self.maxSafeScanStepSeconds)
        eventLocatorDescription = EventLocatorDescriptionEnd(builder)
        return eventLocatorDescription
