# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# One scalar event function the locator offers. `name` is the key a consumer
# resolves through the SDS parameter-catalog record; this schema deliberately
# does NOT carry a parameter roster of its own, because a second roster is a
# second source of truth.
class EventComponent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventComponent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventComponent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventComponent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Index used by every ABI struct in this file. Dense, 0-based, stable for
    # the lifetime of one configuration.
    # EventComponent
    def ComponentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The catalog parameter or locator-defined component name.
    # EventComponent
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The unit `value`, `goalValue` and `valueTolerance` are expressed in.
    # EventComponent
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Capability-class description. Never a vendor or organization name.
    # EventComponent
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # For a stop condition, g = parameter - goalValue. For a pure locator
    # component (an eclipse shadow function) the goal is 0 and g is the
    # geometry itself.
    # EventComponent
    def GoalValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Direction filter for this component, ANDed with the interval's.
    # EventComponent
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # 1-based occurrence for this component. 0 = every occurrence.
    # EventComponent
    def Occurrence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # True when this component is a propagate-to-condition stop rather than an
    # observation. Hits from it carry `STOP_CONDITION`.
    # EventComponent
    def IsStopCondition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Which configured object this component is about.
    # EventComponent
    def ObjectIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The second object for a relative component (the station, the occulting
    # body, the observed body). Meaningful only when `usesTargetObject`.
    # EventComponent
    def TargetObjectIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Whether `targetObjectIndex` is used at all.
    # EventComponent
    def UsesTargetObject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # The frame this component's geometry is evaluated in.
    # EventComponent
    def ReferenceFrame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Continuity class, which decides whether interpolation is admissible.
    # EventComponent
    def Continuity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def EventComponentStart(builder):
    builder.StartObject(13)

def Start(builder):
    EventComponentStart(builder)

def EventComponentAddComponentId(builder, componentId):
    builder.PrependUint32Slot(0, componentId, 0)

def AddComponentId(builder, componentId):
    EventComponentAddComponentId(builder, componentId)

def EventComponentAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    EventComponentAddName(builder, name)

def EventComponentAddUnit(builder, unit):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder, unit):
    EventComponentAddUnit(builder, unit)

def EventComponentAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def AddDescription(builder, description):
    EventComponentAddDescription(builder, description)

def EventComponentAddGoalValue(builder, goalValue):
    builder.PrependFloat64Slot(4, goalValue, 0.0)

def AddGoalValue(builder, goalValue):
    EventComponentAddGoalValue(builder, goalValue)

def EventComponentAddDirection(builder, direction):
    builder.PrependInt8Slot(5, direction, 0)

def AddDirection(builder, direction):
    EventComponentAddDirection(builder, direction)

def EventComponentAddOccurrence(builder, occurrence):
    builder.PrependUint32Slot(6, occurrence, 0)

def AddOccurrence(builder, occurrence):
    EventComponentAddOccurrence(builder, occurrence)

def EventComponentAddIsStopCondition(builder, isStopCondition):
    builder.PrependBoolSlot(7, isStopCondition, 0)

def AddIsStopCondition(builder, isStopCondition):
    EventComponentAddIsStopCondition(builder, isStopCondition)

def EventComponentAddObjectIndex(builder, objectIndex):
    builder.PrependUint32Slot(8, objectIndex, 0)

def AddObjectIndex(builder, objectIndex):
    EventComponentAddObjectIndex(builder, objectIndex)

def EventComponentAddTargetObjectIndex(builder, targetObjectIndex):
    builder.PrependUint32Slot(9, targetObjectIndex, 0)

def AddTargetObjectIndex(builder, targetObjectIndex):
    EventComponentAddTargetObjectIndex(builder, targetObjectIndex)

def EventComponentAddUsesTargetObject(builder, usesTargetObject):
    builder.PrependBoolSlot(10, usesTargetObject, 0)

def AddUsesTargetObject(builder, usesTargetObject):
    EventComponentAddUsesTargetObject(builder, usesTargetObject)

def EventComponentAddReferenceFrame(builder, referenceFrame):
    builder.PrependUint8Slot(11, referenceFrame, 0)

def AddReferenceFrame(builder, referenceFrame):
    EventComponentAddReferenceFrame(builder, referenceFrame)

def EventComponentAddContinuity(builder, continuity):
    builder.PrependUint8Slot(12, continuity, 0)

def AddContinuity(builder, continuity):
    EventComponentAddContinuity(builder, continuity)

def EventComponentEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventComponentEnd(builder)


class EventComponentT(object):

    # EventComponentT
    def __init__(
        self,
        componentId = 0,
        name = None,
        unit = None,
        description = None,
        goalValue = 0.0,
        direction = 0,
        occurrence = 0,
        isStopCondition = False,
        objectIndex = 0,
        targetObjectIndex = 0,
        usesTargetObject = False,
        referenceFrame = 0,
        continuity = 0,
    ):
        self.componentId = componentId  # type: int
        self.name = name  # type: Optional[str]
        self.unit = unit  # type: Optional[str]
        self.description = description  # type: Optional[str]
        self.goalValue = goalValue  # type: float
        self.direction = direction  # type: int
        self.occurrence = occurrence  # type: int
        self.isStopCondition = isStopCondition  # type: bool
        self.objectIndex = objectIndex  # type: int
        self.targetObjectIndex = targetObjectIndex  # type: int
        self.usesTargetObject = usesTargetObject  # type: bool
        self.referenceFrame = referenceFrame  # type: int
        self.continuity = continuity  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        eventComponent = EventComponent()
        eventComponent.Init(buf, pos)
        return cls.InitFromObj(eventComponent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, eventComponent):
        x = EventComponentT()
        x._UnPack(eventComponent)
        return x

    # EventComponentT
    def _UnPack(self, eventComponent):
        if eventComponent is None:
            return
        self.componentId = eventComponent.ComponentId()
        self.name = eventComponent.Name()
        self.unit = eventComponent.Unit()
        self.description = eventComponent.Description()
        self.goalValue = eventComponent.GoalValue()
        self.direction = eventComponent.Direction()
        self.occurrence = eventComponent.Occurrence()
        self.isStopCondition = eventComponent.IsStopCondition()
        self.objectIndex = eventComponent.ObjectIndex()
        self.targetObjectIndex = eventComponent.TargetObjectIndex()
        self.usesTargetObject = eventComponent.UsesTargetObject()
        self.referenceFrame = eventComponent.ReferenceFrame()
        self.continuity = eventComponent.Continuity()

    # EventComponentT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.unit is not None:
            unit = builder.CreateString(self.unit)
        if self.description is not None:
            description = builder.CreateString(self.description)
        EventComponentStart(builder)
        EventComponentAddComponentId(builder, self.componentId)
        if self.name is not None:
            EventComponentAddName(builder, name)
        if self.unit is not None:
            EventComponentAddUnit(builder, unit)
        if self.description is not None:
            EventComponentAddDescription(builder, description)
        EventComponentAddGoalValue(builder, self.goalValue)
        EventComponentAddDirection(builder, self.direction)
        EventComponentAddOccurrence(builder, self.occurrence)
        EventComponentAddIsStopCondition(builder, self.isStopCondition)
        EventComponentAddObjectIndex(builder, self.objectIndex)
        EventComponentAddTargetObjectIndex(builder, self.targetObjectIndex)
        EventComponentAddUsesTargetObject(builder, self.usesTargetObject)
        EventComponentAddReferenceFrame(builder, self.referenceFrame)
        EventComponentAddContinuity(builder, self.continuity)
        eventComponent = EventComponentEnd(builder)
        return eventComponent
