# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# What the locator wants evaluated next — the guest-to-consumer half of the
# pull protocol. 16 bytes, 4-byte aligned.
#
# The consumer reads this, propagates the requested epochs through whatever
# module is wired to the propagator port, and returns the states through
# `plugin_event_supply`. The consumer chooses NOTHING: not the epochs, not
# the order, not when the scan ends.
class EventStateRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # EventStateRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # How many epochs were written to the caller's epoch buffer. The buffer
    # holds `2 * epoch_count` doubles: (jd_day, seconds) pairs, in scan order.
    # EventStateRequest
    def EpochCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # How many objects each epoch must be evaluated for. Every configured
    # object is evaluated at EVERY requested epoch — that is what makes a
    # multi-spacecraft (Formation) stop synchronized by construction rather
    # than by the consumer remembering to keep the epochs aligned.
    # EventStateRequest
    def ObjectCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # The frame the returned states must be expressed in. An
    # `OrbProReferenceFrame` value; the consumer converts through the frames
    # port if its propagator emits another frame, and a consumer that cannot
    # must fail loudly rather than supply a differently-framed state.
    # EventStateRequest
    def ReferenceFrame(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EventFlags bitfield describing the phase this request belongs to
    # (a coarse scan batch versus a single refinement abscissa).
    # EventStateRequest
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateEventStateRequest(builder, epochCount, objectCount, referenceFrame, flags):
    builder.Prep(4, 16)
    builder.PrependUint32(flags)
    builder.Pad(3)
    builder.PrependUint8(referenceFrame)
    builder.PrependUint32(objectCount)
    builder.PrependUint32(epochCount)
    return builder.Offset()


class EventStateRequestT(object):

    # EventStateRequestT
    def __init__(
        self,
        epochCount = 0,
        objectCount = 0,
        referenceFrame = 0,
        flags = 0,
    ):
        self.epochCount = epochCount  # type: int
        self.objectCount = objectCount  # type: int
        self.referenceFrame = referenceFrame  # type: int
        self.flags = flags  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        eventStateRequest = EventStateRequest()
        eventStateRequest.Init(buf, pos)
        return cls.InitFromObj(eventStateRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, eventStateRequest):
        x = EventStateRequestT()
        x._UnPack(eventStateRequest)
        return x

    # EventStateRequestT
    def _UnPack(self, eventStateRequest):
        if eventStateRequest is None:
            return
        self.epochCount = eventStateRequest.EpochCount()
        self.objectCount = eventStateRequest.ObjectCount()
        self.referenceFrame = eventStateRequest.ReferenceFrame()
        self.flags = eventStateRequest.Flags()

    # EventStateRequestT
    def Pack(self, builder):
        return CreateEventStateRequest(builder, self.epochCount, self.objectCount, self.referenceFrame, self.flags)
