# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# A named scalar or string the locator declares it accepts. This is how a
# locator is configured WITHOUT a schema per locator: the keys are published
# in the description, so the configuration is self-describing rather than
# free-form.
class EventParameter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventParameter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventParameter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventParameter
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventParameter
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventParameter
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EventParameter
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EventParameterStart(builder):
    builder.StartObject(3)

def Start(builder):
    EventParameterStart(builder)

def EventParameterAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    EventParameterAddKey(builder, key)

def EventParameterAddValue(builder, value):
    builder.PrependFloat64Slot(1, value, 0.0)

def AddValue(builder, value):
    EventParameterAddValue(builder, value)

def EventParameterAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def AddText(builder, text):
    EventParameterAddText(builder, text)

def EventParameterEnd(builder):
    return builder.EndObject()

def End(builder):
    return EventParameterEnd(builder)


class EventParameterT(object):

    # EventParameterT
    def __init__(
        self,
        key = None,
        value = 0.0,
        text = None,
    ):
        self.key = key  # type: Optional[str]
        self.value = value  # type: float
        self.text = text  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        eventParameter = EventParameter()
        eventParameter.Init(buf, pos)
        return cls.InitFromObj(eventParameter)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, eventParameter):
        x = EventParameterT()
        x._UnPack(eventParameter)
        return x

    # EventParameterT
    def _UnPack(self, eventParameter):
        if eventParameter is None:
            return
        self.key = eventParameter.Key()
        self.value = eventParameter.Value()
        self.text = eventParameter.Text()

    # EventParameterT
    def Pack(self, builder):
        if self.key is not None:
            key = builder.CreateString(self.key)
        if self.text is not None:
            text = builder.CreateString(self.text)
        EventParameterStart(builder)
        if self.key is not None:
            EventParameterAddKey(builder, key)
        EventParameterAddValue(builder, self.value)
        if self.text is not None:
            EventParameterAddText(builder, text)
        eventParameter = EventParameterEnd(builder)
        return eventParameter
