# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# The root-refinement policy — the SAME parameters for every locator, which
# is what makes two locators' epochs comparable. 32 bytes, 8-byte aligned.
#
# A zeroed policy is NOT a default: `orbpro_root_policy_init` zeroes it and
# `plugin_event_begin` refuses a zero `scan_step_seconds` with `BAD_INPUT`.
# A silent default step is how a scan misses every event shorter than it.
class RootPolicy(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # RootPolicy
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Coarse bracketing step, SECONDS, always positive. The runner applies the
    # interval's direction. This is the ONLY thing that decides which events
    # are found; the refinement decides only how precisely.
    # RootPolicy
    def ScanStepSeconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Convergence bar on the bracket width, SECONDS. Clamped up to the state
    # source's declared epoch resolution — see `EPOCH_RESOLUTION_LIMITED`.
    # RootPolicy
    def EpochToleranceSeconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # Convergence bar on |g|, in the component's own declared unit. 0 disables
    # the value test and converges on the bracket alone.
    # RootPolicy
    def ValueTolerance(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # Hard cap on refinement iterations for ONE root. Reaching it is reported
    # as `MAX_ITERATIONS`, never as a converged root.
    # RootPolicy
    def MaxIterations(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # Refinement algorithm.
    # RootPolicy
    def Method(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))

def CreateRootPolicy(builder, scanStepSeconds, epochToleranceSeconds, valueTolerance, maxIterations, method):
    builder.Prep(8, 32)
    builder.Pad(3)
    builder.PrependUint8(method)
    builder.PrependUint32(maxIterations)
    builder.PrependFloat64(valueTolerance)
    builder.PrependFloat64(epochToleranceSeconds)
    builder.PrependFloat64(scanStepSeconds)
    return builder.Offset()


class RootPolicyT(object):

    # RootPolicyT
    def __init__(
        self,
        scanStepSeconds = 0.0,
        epochToleranceSeconds = 0.0,
        valueTolerance = 0.0,
        maxIterations = 0,
        method = 0,
    ):
        self.scanStepSeconds = scanStepSeconds  # type: float
        self.epochToleranceSeconds = epochToleranceSeconds  # type: float
        self.valueTolerance = valueTolerance  # type: float
        self.maxIterations = maxIterations  # type: int
        self.method = method  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rootPolicy = RootPolicy()
        rootPolicy.Init(buf, pos)
        return cls.InitFromObj(rootPolicy)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rootPolicy):
        x = RootPolicyT()
        x._UnPack(rootPolicy)
        return x

    # RootPolicyT
    def _UnPack(self, rootPolicy):
        if rootPolicy is None:
            return
        self.scanStepSeconds = rootPolicy.ScanStepSeconds()
        self.epochToleranceSeconds = rootPolicy.EpochToleranceSeconds()
        self.valueTolerance = rootPolicy.ValueTolerance()
        self.maxIterations = rootPolicy.MaxIterations()
        self.method = rootPolicy.Method()

    # RootPolicyT
    def Pack(self, builder):
        return CreateRootPolicy(builder, self.scanStepSeconds, self.epochToleranceSeconds, self.valueTolerance, self.maxIterations, self.method)
