# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

# How a refinement ended. NEVER folded into the returned root: a root that
# stopped on the iteration cap and a root that converged are different
# answers, and a consumer that cannot tell them apart will publish the first
# as if it were the second.
class RootStatus(object):
    # |g| <= value_tolerance, or the bracket narrowed below epoch_tolerance.
    CONVERGED = 0
    # The iteration cap was reached with the bracket still wider than the
    # tolerance. The returned epoch is the best bracket midpoint.
    MAX_ITERATIONS = 1
    # g did not change sign across a bracket that the scan said it did — the
    # state source returned inconsistent values for the same epoch, or g is
    # not a function of epoch alone.
    FLAT_BRACKET = 2
    # g jumped across zero without passing through it within the epoch
    # tolerance: a discontinuity, not a root. Reported, never refined away.
    DISCONTINUOUS = 3
    # The scan hit `EventInterval.max_events` or `max_evaluations` and stopped
    # early. Everything reported is real; the list is not complete.
    TRUNCATED = 4
    # The bracket narrowed to the state source's declared epoch resolution
    # before it reached `epoch_tolerance_seconds`. The root is correct to that
    # resolution and NO FINER, and this is how the ABI says so instead of
    # reporting the tolerance it was asked for.
    EPOCH_RESOLUTION_LIMITED = 5
