# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

# The refinement algorithm the runner uses on a bracketed root. All three are
# bracketing methods: a root that is bracketed stays bracketed, so a locator
# can never report a root outside the interval that produced it.
class RootMethod(object):
    # Brent's method (inverse quadratic interpolation with bisection fallback).
    # The default: superlinear on smooth g, and it cannot diverge.
    BRENT = 0
    # Plain bisection. Slower, and chosen only when g is known to be noisy or
    # piecewise — it is the one method whose iteration count is a function of
    # the bracket width alone, which makes it the reproducibility fallback.
    BISECTION = 1
    # Illinois (modified regula falsi). Retained because it is the method the
    # legacy JavaScript eclipse scan used, so a like-for-like comparison
    # against the pre-module answer is possible without changing the method.
    ILLINOIS = 2
