/**
 * The conformance policy for the reference propagator.
 *
 * Nothing in this file is an expectation COPIED from the module. Tier B
 * anchors are closed-form quantities computed here, independently, from the
 * same inputs; Tier C invariants have no stored expectation at all. That
 * distinction is the whole point: a corpus generated by running the
 * implementation is a change-detector, not a conformance test.
 */

/// WGS-72 gravitational parameter, m^3/s^2. PINNED: the mean elements in an
/// OMM were fitted under this model, so a consumer using WGS-84 introduces a
/// bias unrelated to the two-body simplification.
export const MU = 398600.8e9;

/// Earth rotation rate, rad/s (IAU 1982).
export const EARTH_ROTATION_RATE = 7.292115146706979e-5;

export const SECONDS_PER_DAY = 86400.0;
export const J2000_JD = 2451545.0;

/**
 * Tolerance bands, per quantity rather than per case.
 *
 * `fail <=> |observed - expected| > abs + rel * |expected|`
 */
export const BANDS = Object.freeze({
  /// Positions are metres on a ~7e6 m orbit; 1e-6 relative is ~7 metres, and
  /// double-precision closed form should be far inside that.
  position: { abs: 1e-6, rel: 1e-9 },
  velocity: { abs: 1e-9, rel: 1e-9 },
  /// Julian dates carry ~1e-11 day of resolution at this magnitude.
  time: { abs: 1e-9, rel: 0 },
  angle: { abs: 1e-12, rel: 1e-12 },
  /// Byte-for-byte. Determinism admits no band.
  exact: { abs: 0, rel: 0 },
});

export function withinBand(observed, expected, band) {
  return Math.abs(observed - expected) <= band.abs + band.rel * Math.abs(expected);
}

/** Solve Kepler's equation independently of the module under test. */
export function solveKepler(meanAnomaly, eccentricity) {
  let M = meanAnomaly % (2 * Math.PI);
  if (M < 0) M += 2 * Math.PI;
  let E = eccentricity < 0.8 ? M : Math.PI;
  for (let i = 0; i < 200; i += 1) {
    const f = E - eccentricity * Math.sin(E) - M;
    const fp = 1 - eccentricity * Math.cos(E);
    const d = f / fp;
    E -= d;
    if (Math.abs(d) < 1e-15) return E;
  }
  throw new Error("reference Kepler solve did not converge");
}

/** Greenwich Mean Sidereal Time, radians (IAU 1982). */
export function gmstRadians(julianDate) {
  const tut1 = (julianDate - J2000_JD) / 36525.0;
  const seconds =
    67310.54841 +
    (876600.0 * 3600.0 + 8640184.812866) * tut1 +
    0.093104 * tut1 * tut1 -
    6.2e-6 * tut1 * tut1 * tut1;
  let gmst = (seconds * ((2 * Math.PI) / SECONDS_PER_DAY)) % (2 * Math.PI);
  if (gmst < 0) gmst += 2 * Math.PI;
  return gmst;
}

/**
 * The independent adjudicator: closed-form two-body propagation from mean
 * elements to an ECEF state, in METERS.
 *
 * This is written from the textbook relations, not from the module's source.
 * Where the two agree, they agree because two-body motion has one answer.
 */
export function propagateTwoBody(elements, julianDate) {
  const {
    epochJd,
    meanMotionRevPerDay,
    eccentricity,
    inclinationDeg,
    raOfAscNodeDeg,
    argOfPericenterDeg,
    meanAnomalyDeg,
  } = elements;

  const deg = Math.PI / 180;
  const n = (meanMotionRevPerDay * 2 * Math.PI) / SECONDS_PER_DAY;
  const a = Math.cbrt(MU / (n * n));
  const dt = (julianDate - epochJd) * SECONDS_PER_DAY;
  const M = meanAnomalyDeg * deg + n * dt;
  const E = solveKepler(M, eccentricity);

  const cosE = Math.cos(E);
  const sinE = Math.sin(E);
  const beta = Math.sqrt(1 - eccentricity * eccentricity);
  const xPqw = a * (cosE - eccentricity);
  const yPqw = a * beta * sinE;
  const eDot = n / (1 - eccentricity * cosE);
  const vxPqw = -a * sinE * eDot;
  const vyPqw = a * beta * cosE * eDot;

  const O = raOfAscNodeDeg * deg;
  const i = inclinationDeg * deg;
  const w = argOfPericenterDeg * deg;
  const cO = Math.cos(O);
  const sO = Math.sin(O);
  const ci = Math.cos(i);
  const si = Math.sin(i);
  const cw = Math.cos(w);
  const sw = Math.sin(w);

  const r11 = cO * cw - sO * sw * ci;
  const r12 = -cO * sw - sO * cw * ci;
  const r21 = sO * cw + cO * sw * ci;
  const r22 = -sO * sw + cO * cw * ci;
  const r31 = sw * si;
  const r32 = cw * si;

  const xI = r11 * xPqw + r12 * yPqw;
  const yI = r21 * xPqw + r22 * yPqw;
  const zI = r31 * xPqw + r32 * yPqw;
  const vxI = r11 * vxPqw + r12 * vyPqw;
  const vyI = r21 * vxPqw + r22 * vyPqw;
  const vzI = r31 * vxPqw + r32 * vyPqw;

  const theta = gmstRadians(julianDate);
  const ct = Math.cos(theta);
  const st = Math.sin(theta);

  const x = ct * xI + st * yI;
  const y = -st * xI + ct * yI;
  const z = zI;
  const vxRot = ct * vxI + st * vyI;
  const vyRot = -st * vxI + ct * vyI;

  return {
    position: [x, y, z],
    velocity: [
      vxRot + EARTH_ROTATION_RATE * y,
      vyRot - EARTH_ROTATION_RATE * x,
      vzI,
    ],
    semiMajorAxis: a,
    meanMotion: n,
  };
}

/** Inertial (TEME) speed and radius, for the vis-viva invariant. */
export function inertialMagnitudes(elements, julianDate) {
  const deg = Math.PI / 180;
  const n = (elements.meanMotionRevPerDay * 2 * Math.PI) / SECONDS_PER_DAY;
  const a = Math.cbrt(MU / (n * n));
  const dt = (julianDate - elements.epochJd) * SECONDS_PER_DAY;
  const E = solveKepler(elements.meanAnomalyDeg * deg + n * dt, elements.eccentricity);
  const r = a * (1 - elements.eccentricity * Math.cos(E));
  const v = Math.sqrt(MU * (2 / r - 1 / a));
  return { radius: r, speed: v, semiMajorAxis: a };
}
