/* Native SPK type 2/3 and body-chain verification.
 * Authority: NAIF SPK Required Reading types 2/3 and segment precedence,
 * https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/spk.html
 * Independent closed forms: T0=1, T1=x, T2=2*x*x-1, T3=4*x*x*x-3*x;
 * dT/dx=(0,1,4*x,12*x*x-3). Units km and km/s, frame J2000, epoch TDB
 * seconds past J2000. Binary-exact quarter-interval arguments and integer
 * coefficients permit 1e-12 km / 1e-12 km/s tolerances (round-off only).
 * These constructed polynomials verify the published representation, not a
 * golden trajectory generated by the implementation under test. DE440/CSPICE
 * integration values are separately exercised by de440_reference_native.cpp.
 */
#include <cmath>
#include <cstdio>
#include <cstring>
#include <limits>
#include <vector>
#include "spk_kernel.hpp"

static int failures = 0;
static int checks = 0;
#define CHECK(x) do { ++checks; if (!(x)) { ++failures; std::printf("FAIL line %d: %s\n", __LINE__, #x); } } while (0)

static void put_i32(std::vector<uint8_t>& b, size_t at, int32_t value, bool big) {
    const uint32_t bits = static_cast<uint32_t>(value);
    for (int i = 0; i < 4; ++i) b[at + i] = static_cast<uint8_t>(bits >> (8 * (big ? 3-i : i)));
}
static void put_f64(std::vector<uint8_t>& b, size_t at, double value, bool big) {
    uint64_t bits;
    std::memcpy(&bits, &value, 8);
    for (int i = 0; i < 8; ++i) b[at + i] = static_cast<uint8_t>(bits >> (8 * (big ? 7-i : i)));
}

struct Segment {
    int target = 301, center = 399, type = 2, frame = 1;
    double scale = 1.0;
};

static std::vector<uint8_t> kernel(const std::vector<Segment>& segments, bool big = false) {
    std::vector<uint8_t> b(16384, 0);
    std::memcpy(b.data(), "DAF/SPK ", 8);
    put_i32(b, 8, 2, big); put_i32(b, 12, 6, big);
    put_i32(b, 76, 2, big); put_i32(b, 80, 2, big);
    std::memcpy(b.data() + 88, big ? "BIG-IEEE" : "LTL-IEEE", 8);
    put_f64(b, 1024 + 16, static_cast<double>(segments.size()), big);
    size_t word = 385;
    for (size_t si = 0; si < segments.size(); ++si) {
        const Segment& s = segments[si];
        const size_t begin = word;
        const int components = s.type == 3 ? 6 : 3;
        const size_t record_size = 2 + 4 * components;
        for (int record = 0; record < 2; ++record) {
            put_f64(b, 8 * (word++ - 1), record * 16.0, big);
            put_f64(b, 8 * (word++ - 1), 8.0, big);
            for (int axis = 0; axis < components; ++axis) {
                const double c[4] = {
                    s.scale * (100.0 * (axis + 1) + 1000.0 * record),
                    s.scale * 2.0, s.scale * 3.0, s.scale * 4.0
                };
                for (double value : c) put_f64(b, 8 * (word++ - 1), value, big);
            }
        }
        for (double value : {-8.0, 16.0, static_cast<double>(record_size), 2.0}) {
            put_f64(b, 8 * (word++ - 1), value, big);
        }
        const size_t summary = 1024 + 24 + si * 40;
        put_f64(b, summary, -8.0, big); put_f64(b, summary + 8, 24.0, big);
        const int32_t ints[6] = {s.target, s.center, s.frame, s.type,
                                 static_cast<int32_t>(begin), static_cast<int32_t>(word - 1)};
        for (int i = 0; i < 6; ++i) put_i32(b, summary + 16 + 4*i, ints[i], big);
    }
    put_i32(b, 84, static_cast<int32_t>(word), big);
    b.resize(((8 * (word - 1) + 1023) / 1024) * 1024);
    return b;
}

static double position(double scale, int axis, double et) {
    const int record = et >= 8.0 ? 1 : 0;
    const double x = (et - record * 16.0) / 8.0;
    return scale * (100.0 * (axis + 1) + 1000.0 * record + 2*x +
                    3*(2*x*x - 1) + 4*(4*x*x*x - 3*x));
}
static double velocity(double scale, double et) {
    const int record = et >= 8.0 ? 1 : 0;
    const double x = (et - record * 16.0) / 8.0;
    return scale * (2 + 12*x + 4*(12*x*x - 3)) / 8.0;
}

static void polynomials() {
    for (bool big : {false, true}) for (int type : {2, 3}) {
        auto bytes = kernel({{301, 399, type, 1, 1}}, big);
        daf::File file;
        CHECK(daf::read(bytes.data(), bytes.size(), &file) == ephem::Status::Ok);
        for (double et : {-8.0, -6.0, 0.0, 2.0, 8.0, 10.0, 16.0, 24.0}) {
            ephem::StateRow state;
            CHECK(spk::evaluate(file, file.summaries[0], et, &state) == ephem::Status::Ok);
            CHECK(state.has_vel && state.epoch == et);
            for (int axis = 0; axis < 3; ++axis) {
                CHECK(std::abs(state.pos[axis] - position(1, axis, et)) <= 1e-12);
                const double expected = type == 2 ? velocity(1, et) : position(1, axis + 3, et);
                CHECK(std::abs(state.vel[axis] - expected) <= 1e-12);
            }
        }
        ephem::Series series;
        CHECK(spk::to_series(file, file.summaries[0], &series) == ephem::Status::Unsupported);
        ephem::StateRow state;
        CHECK(spk::evaluate(file, file.summaries[0], -9, &state) == ephem::Status::OutOfRange);
        CHECK(spk::evaluate(file, file.summaries[0], 25, &state) == ephem::Status::OutOfRange);
    }
}

static void chains() {
    // Moon -> EMB and Earth -> EMB works even if no EMB -> SSB data exists.
    for (bool big : {false, true}) {
        auto bytes = kernel({{301,3,2,1,10}, {399,3,2,1,-1}}, big);
        spk::Kernel k;
        CHECK(k.load(bytes.data(), bytes.size()) == ephem::Status::Ok);
        CHECK(k.loaded() && k.start_jd() < k.end_jd());
        ephem::StateRow moon, inverse, zero;
        CHECK(k.state_et(301,399,2,&moon) == ephem::Status::Ok);
        CHECK(k.state_et(399,301,2,&inverse) == ephem::Status::Ok);
        CHECK(k.state(301,301,2451545.0,&zero) == ephem::Status::Ok);
        for (int axis = 0; axis < 3; ++axis) {
            CHECK(std::abs(moon.pos[axis] - position(11,axis,2)) <= 1e-12);
            CHECK(std::abs(moon.vel[axis] - velocity(11,2)) <= 1e-12);
            CHECK(inverse.pos[axis] == -moon.pos[axis]);
            CHECK(inverse.vel[axis] == -moon.vel[axis]);
            CHECK(zero.pos[axis] == 0 && zero.vel[axis] == 0);
        }
        CHECK(k.state_et(301,0,2,&moon) == ephem::Status::OutOfRange);
        CHECK(k.state_et(10,399,2,&moon) == ephem::Status::OutOfRange);
        CHECK(k.state_et(301,399,25,&moon) == ephem::Status::OutOfRange);
        CHECK(k.state(301,399,2451545.0,&moon) == ephem::Status::Ok);
        CHECK(std::abs(moon.pos[0] - position(11,0,0)) <= 1e-12);
    }
    // Later segments supersede earlier ones, including unsupported segments.
    auto bytes = kernel({{301,399,2,1,1}, {301,399,2,1,3}});
    spk::Kernel k;
    ephem::StateRow row;
    CHECK(k.load(bytes.data(), bytes.size()) == ephem::Status::Ok);
    CHECK(k.state_et(301,399,2,&row) == ephem::Status::Ok);
    CHECK(row.pos[0] == position(3,0,2));
    put_i32(bytes, 1024+24+40+16+12, 5, false);
    CHECK(k.load(bytes.data(), bytes.size()) == ephem::Status::Ok);
    CHECK(k.state_et(301,399,2,&row) == ephem::Status::UnsupportedVariant);
    put_i32(bytes, 1024+24+40+16+12, 2, false);
    put_i32(bytes, 1024+24+40+16+8, 17, false);
    CHECK(k.load(bytes.data(), bytes.size()) == ephem::Status::Ok);
    CHECK(k.state_et(301,399,2,&row) == ephem::Status::UnsupportedVariant);
    bytes = kernel({{301,3,2,1,1}, {3,301,2,1,1}});
    CHECK(k.load(bytes.data(), bytes.size()) == ephem::Status::Ok);
    CHECK(k.state_et(301,399,2,&row) == ephem::Status::Malformed);
}

static void malformed() {
    const double nan = std::numeric_limits<double>::quiet_NaN();
    const auto good = kernel({{}});
    daf::File file;
    CHECK(daf::read(good.data(), good.size(), &file) == ephem::Status::Ok);
    const size_t end = static_cast<size_t>(file.summaries[0].ic[5]);
    const size_t begin = static_cast<size_t>(file.summaries[0].ic[4]);
    const std::vector<std::pair<size_t,double>> mutations = {
        {end,0}, {end,2.5}, {end,1e100}, {end-1,13}, {end-1,14.5},
        {end-2,0}, {end-2,nan}, {end-3,nan}, {begin,nan},
        {begin+1,0}, {begin+1,-8}, {begin+1,nan}, {begin+2,nan}
    };
    for (const auto& mutation : mutations) {
        auto bytes = good;
        put_f64(bytes, (mutation.first - 1) * 8, mutation.second, false);
        CHECK(daf::read(bytes.data(), bytes.size(), &file) == ephem::Status::Ok);
        ephem::StateRow row;
        CHECK(spk::evaluate(file, file.summaries[0], 2, &row) != ephem::Status::Ok);
    }
    spk::Kernel k;
    ephem::StateRow row;
    CHECK(k.load(good.data(), good.size()) == ephem::Status::Ok);
    CHECK(k.state_et(301,399,nan,&row) == ephem::Status::Malformed);
    CHECK(k.state(301,399,nan,&row) == ephem::Status::Malformed);
    CHECK(k.state_et(301,399,0,nullptr) == ephem::Status::Malformed);
    CHECK(k.load(good.data(), 1024) != ephem::Status::Ok);
    CHECK(!k.loaded());
    CHECK(k.state_et(301,399,0,&row) == ephem::Status::Malformed);
    CHECK(k.load(nullptr,0) == ephem::Status::Malformed);
    auto bytes = good;
    put_f64(bytes,1024+16,1.5,false);
    CHECK(k.load(bytes.data(),bytes.size()) == ephem::Status::Malformed);
    bytes = good;
    put_f64(bytes,1024,2.5,false);
    CHECK(k.load(bytes.data(),bytes.size()) == ephem::Status::Malformed);
    bytes = good;
    put_f64(bytes,1024+24,nan,false);
    CHECK(k.load(bytes.data(),bytes.size()) == ephem::Status::Malformed);
    CHECK(daf::read(good.data(),good.size(),&file) == ephem::Status::Ok);
    double value;
    CHECK(!file.word(std::numeric_limits<size_t>::max(),&value));
    CHECK(!file.words(1,std::numeric_limits<size_t>::max(),&value));
}

int main() {
    polynomials();
    chains();
    malformed();
    std::printf("SPK Chebyshev closed-form, endian, chain and refusal checks: %d checks, %d failures %s\n",
                checks, failures, failures == 0 ? "PASS" : "FAIL");
    return failures == 0 ? 0 : 1;
}
