// frames_validate.cpp — validate hp::frames GCRF<->ITRF against ERFA/SOFA.
//
// Reference matrices in frames_cases.inc were generated by pyerfa (ERFA 2.0.1.5)
// at four epochs with representative EOP. We rebuild the same GCRF->ITRF matrix
// from hp::frames (which wraps the same vendored ERFA core) and compare, then
// exercise the round-trip and a position/velocity transform for sanity.
//
// Build:
//   clang++ -std=c++17 -O2 -Iinclude -Ithird_party/erfa \
//       test/frames/frames_validate.cpp third_party/erfa/*.o -o frames_validate
//
#include <cstdio>
#include <cmath>
#include "higherpop/frames.hpp"

using namespace hp;
using namespace hp::frames;

#include "frames_cases.inc"

int main() {
  double worst_R = 0.0, worst_era = 0.0;
  printf("%-12s  %14s  %14s  %14s\n", "epoch", "max|dR|", "d(ERA)[rad]", "det");
  for (const auto& c : CASES) {
    UTCDate d{c.y,c.mo,c.d,c.h,c.mi,c.s};
    EOP e; e.dut1=c.dut1; e.xp_arcsec=c.xp; e.yp_arcsec=c.yp; e.dX_arcsec=c.dX; e.dY_arcsec=c.dY;
    JulianTT_UT1 t = timescales(d,e);
    Mat3 R = gcrf_to_itrf_matrix(t,e);
    // compare to reference matrix
    double mR=0.0;
    for(int i=0;i<3;++i) for(int j=0;j<3;++j) mR=std::max(mR,std::fabs(R[i][j]-c.R[i][j]));
    // ERA check
    double era = eraEra00(t.ut11,t.ut12);
    double dEra=std::fabs(era-c.era);
    // determinant (should be 1, proper rotation)
    double det = R[0][0]*(R[1][1]*R[2][2]-R[1][2]*R[2][1])
               - R[0][1]*(R[1][0]*R[2][2]-R[1][2]*R[2][0])
               + R[0][2]*(R[1][0]*R[2][1]-R[1][1]*R[2][0]);
    printf("%-12s  %14.3e  %14.3e  %14.12f\n", c.name, mR, dEra, det);
    worst_R=std::max(worst_R,mR); worst_era=std::max(worst_era,dEra);
  }
  printf("\nworst |dR| = %.3e   worst d(ERA) = %.3e\n", worst_R, worst_era);

  // ---- round-trip + PV sanity on case 0 ----
  const auto& c = CASES[0];
  UTCDate d{c.y,c.mo,c.d,c.h,c.mi,c.s};
  EOP e; e.dut1=c.dut1; e.xp_arcsec=c.xp; e.yp_arcsec=c.yp; e.dX_arcsec=c.dX; e.dY_arcsec=c.dY;
  // Vallado canonical GCRF state (km, km/s)
  StatePV g{ Vec3{5102.508958, 6123.011401, 6378.136928},
             Vec3{-4.74322016, 0.79053650, 5.53375528} };
  StatePV it = gcrfToItrf(g,d,e);
  StatePV back = itrfToGcrf(it,d,e);
  double dr = norm(back.r - g.r)*1000.0;      // m
  double dv = norm(back.v - g.v)*1000.0;      // mm/s (km/s*1e3 -> m/s; *1e3 again below)
  printf("\nPV round-trip: dr = %.3e m   dv = %.3e m/s\n", dr, norm(back.v-g.v)*1000.0);
  printf("ITRF position: [% .6f % .6f % .6f] km\n", it.r.x, it.r.y, it.r.z);

  // ---- geodetic round-trip ----
  Geodetic gd = itrfToGeodetic(it.r);
  Vec3 r2 = geodeticToItrf(gd);
  printf("geodetic: lat=%.6f deg lon=%.6f deg h=%.3f km  (roundtrip dr=%.3e m)\n",
         gd.lat_rad*180.0/M_PI, gd.lon_rad*180.0/M_PI, gd.height_km, norm(r2-it.r)*1000.0);

  bool ok = worst_R < 1e-12 && worst_era < 1e-12 && dr < 1e-6;
  printf("\n%s\n", ok ? "FRAMES VALIDATE: PASS (matches ERFA to machine precision)"
                       : "FRAMES VALIDATE: CHECK");
  return ok ? 0 : 1;
}
