# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

# ORDINAL FREEZE -- APPEND ONLY, FOREVER.
# A member's position IS its wire value: flatc writes it into the
# Record.value_type byte of every $REC ever serialized, including the
# publication trailer of every protected module artifact. Inserting,
# reordering or removing a member silently re-points every record ever
# written at the wrong standard. This has already happened three times;
# inserting $PGM mid-union (c1580d4700, 2026-07-08) moved $PNM 113 -> 114
# and broke protected-plugin decryption fleet-wide for three weeks.
# New standards are APPENDED at the end. A retired standard is deprecated
# in place, never deleted -- an ordinal is never reused.
# Contract: schema/REC/RECORDTYPE_ORDINALS.json
# Guard:    node scripts/checkRecordTypeOrdinals.mjs
# Records written before 2026-07-08 are only decodable via Record.standard,
# which is the sole discriminator that has never shifted.
class RecordType(object):
    NONE = 0
    ACL = 1
    ACM = 2
    ACR = 3
    ACW = 4
    AEM = 5
    ANI = 6
    AOF = 7
    APM = 8
    ARM = 9
    AST = 10
    ATD = 11
    ATM = 12
    BAL = 13
    BEM = 14
    BMC = 15
    BOV = 16
    BSP = 17
    BUS = 18
    CAQ = 19
    CAT = 20
    CDM = 21
    CFP = 22
    CHN = 23
    CLT = 24
    CMS = 25
    COM = 26
    COT = 27
    CRD = 28
    CRM = 29
    CSM = 30
    CTR = 31
    CZM = 32
    DFH = 33
    DMG = 34
    DOA = 35
    DPM = 36
    DSS = 37
    EME = 38
    ENC = 39
    ENV = 40
    EOO = 41
    EOP = 42
    EPM = 43
    ESL = 44
    ETM = 45
    EWR = 46
    FCS = 47
    FPC = 48
    FRM = 49
    GDI = 50
    GEO = 51
    GJN = 52
    GNO = 53
    GPX = 54
    GRV = 55
    GVH = 56
    HEL = 57
    HFC = 58
    HYP = 59
    IDM = 60
    ION = 61
    IRO = 62
    KMF = 63
    KML = 64
    KRF = 65
    LAM = 66
    LCC = 67
    LCF = 68
    LCH = 69
    LDM = 70
    LGR = 71
    LKS = 72
    LMO = 73
    LMR = 74
    LMS = 75
    LND = 76
    LNE = 77
    LPF = 78
    LWK = 79
    MBL = 80
    MET = 81
    MFE = 82
    MNF = 83
    MNV = 84
    MPE = 85
    MSL = 86
    MST = 87
    MTI = 88
    NAV = 89
    NUM = 90
    OBD = 91
    OBT = 92
    OCM = 93
    OEM = 94
    OMM = 95
    OOA = 96
    OOB = 97
    OOD = 98
    OOE = 99
    OOI = 100
    OOL = 101
    OON = 102
    OOS = 103
    OOT = 104
    OPM = 105
    OSM = 106
    PCF = 107
    PHY = 108
    PGM = 109
    PIV = 110
    PLD = 111
    PLG = 112
    PLK = 113
    PNM = 114
    PPE = 115
    PRG = 116
    PRR = 117
    PRW = 118
    PUR = 119
    RAF = 120
    RBK = 121
    RCF = 122
    RDM = 123
    RDO = 124
    REM = 125
    REV = 126
    RFB = 127
    RFE = 128
    RFM = 129
    RFO = 130
    ROC = 131
    SAR = 132
    SCM = 133
    SDF = 134
    SDL = 135
    SDR = 136
    SEN = 137
    SEO = 138
    SEV = 139
    SHW = 140
    SIT = 141
    SKI = 142
    SNR = 143
    SNW = 144
    SOI = 145
    SON = 146
    SPP = 147
    SPW = 148
    SRI = 149
    STF = 150
    STR = 151
    STV = 152
    SWR = 153
    TAB = 154
    TCF = 155
    TDM = 156
    TIM = 157
    TKG = 158
    TME = 159
    TMF = 160
    TNR = 161
    TPN = 162
    TRE = 163
    TRK = 164
    TRN = 165
    VCM = 166
    WPN = 167
    WTH = 168
    XTC = 169
    SCV = 170
    FSM = 171
    FSP = 172
    SCC = 173
    SCN = 174
    VST = 175
    ENT = 176
    VAM = 177
    APP = 178
    CMT = 179
    SCX = 180
    CVG = 181
    PKB = 182
    RPT = 183
    STO = 184
    SUB = 185
    WKS = 186
    CPS = 187
    FSB = 188
    FSO = 189
    GST = 190
    MDP = 191
    MDS = 192
    PNL = 193
    SHC = 194
    CES = 195
    QEM = 196
    SBM = 197
    PMM = 198
    OPP = 199
    IQC = 200
    CNP = 201
    CMR = 202
    TBS = 203
    CCT = 204
    ACI = 205
    CVP = 206
    RFL = 207
    RFS = 208
    TRS = 209
    GNP = 210
    DTT = 211
    AVL = 212
    TFN = 213
    TMS = 214
    VEP = 215
    EGP = 216
    APL = 217
    EMC = 218
    EPF = 219
    GEL = 220
    PAP = 221
    RSD = 222
    IRM = 223
    VCF = 224
    STX = 225
    TXS = 226
    BPF = 227
    EVL = 228
    PCE = 229
    NCD = 230
    MEM = 231
    ODR = 232
    TRH = 233
    SLP = 234
    PSS = 235
    ICN = 236
    TRP = 237
    TRV = 238
    ACT = 239
    AGR = 240
    NDS = 241
    NST = 242
    QRP = 243
    TCT = 244
    WXF = 245
    CLM = 246
    GCT = 247

def RecordTypeCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == RecordType.ACL:
        import spacedatanetwork_astro.sds.REC.ACL as ACL
        return ACL.ACLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ACM:
        import spacedatanetwork_astro.sds.REC.ACM as ACM
        return ACM.ACMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ACR:
        import spacedatanetwork_astro.sds.REC.ACR as ACR
        return ACR.ACRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ACW:
        import spacedatanetwork_astro.sds.REC.ACW as ACW
        return ACW.ACWT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.AEM:
        import spacedatanetwork_astro.sds.REC.AEM as AEM
        return AEM.AEMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ANI:
        import spacedatanetwork_astro.sds.REC.ANI as ANI
        return ANI.ANIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.AOF:
        import spacedatanetwork_astro.sds.REC.AOF as AOF
        return AOF.AOFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.APM:
        import spacedatanetwork_astro.sds.REC.APM as APM
        return APM.APMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ARM:
        import spacedatanetwork_astro.sds.REC.ARM as ARM
        return ARM.ARMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.AST:
        import spacedatanetwork_astro.sds.REC.AST as AST
        return AST.ASTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ATD:
        import spacedatanetwork_astro.sds.REC.ATD as ATD
        return ATD.ATDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ATM:
        import spacedatanetwork_astro.sds.REC.ATM as ATM
        return ATM.ATMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BAL:
        import spacedatanetwork_astro.sds.REC.BAL as BAL
        return BAL.BALT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BEM:
        import spacedatanetwork_astro.sds.REC.BEM as BEM
        return BEM.BEMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BMC:
        import spacedatanetwork_astro.sds.REC.BMC as BMC
        return BMC.BMCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BOV:
        import spacedatanetwork_astro.sds.REC.BOV as BOV
        return BOV.BOVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BSP:
        import spacedatanetwork_astro.sds.REC.BSP as BSP
        return BSP.BSPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BUS:
        import spacedatanetwork_astro.sds.REC.BUS as BUS
        return BUS.BUST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CAQ:
        import spacedatanetwork_astro.sds.REC.CAQ as CAQ
        return CAQ.CAQT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CAT:
        import spacedatanetwork_astro.sds.REC.CAT as CAT
        return CAT.CATT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CDM:
        import spacedatanetwork_astro.sds.REC.CDM as CDM
        return CDM.CDMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CFP:
        import spacedatanetwork_astro.sds.REC.CFP as CFP
        return CFP.CFPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CHN:
        import spacedatanetwork_astro.sds.REC.CHN as CHN
        return CHN.CHNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CLT:
        import spacedatanetwork_astro.sds.REC.CLT as CLT
        return CLT.CLTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CMS:
        import spacedatanetwork_astro.sds.REC.CMS as CMS
        return CMS.CMST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.COM:
        import spacedatanetwork_astro.sds.REC.COM as COM
        return COM.COMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.COT:
        import spacedatanetwork_astro.sds.REC.COT as COT
        return COT.COTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CRD:
        import spacedatanetwork_astro.sds.REC.CRD as CRD
        return CRD.CRDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CRM:
        import spacedatanetwork_astro.sds.REC.CRM as CRM
        return CRM.CRMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CSM:
        import spacedatanetwork_astro.sds.REC.CSM as CSM
        return CSM.CSMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CTR:
        import spacedatanetwork_astro.sds.REC.CTR as CTR
        return CTR.CTRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CZM:
        import spacedatanetwork_astro.sds.REC.CZM as CZM
        return CZM.CZMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DFH:
        import spacedatanetwork_astro.sds.REC.DFH as DFH
        return DFH.DFHT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DMG:
        import spacedatanetwork_astro.sds.REC.DMG as DMG
        return DMG.DMGT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DOA:
        import spacedatanetwork_astro.sds.REC.DOA as DOA
        return DOA.DOAT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DPM:
        import spacedatanetwork_astro.sds.REC.DPM as DPM
        return DPM.DPMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DSS:
        import spacedatanetwork_astro.sds.REC.DSS as DSS
        return DSS.DSST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EME:
        import spacedatanetwork_astro.sds.REC.EME as EME
        return EME.EMET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ENC:
        import spacedatanetwork_astro.sds.REC.ENC as ENC
        return ENC.ENCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ENV:
        import spacedatanetwork_astro.sds.REC.ENV as ENV
        return ENV.ENVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EOO:
        import spacedatanetwork_astro.sds.REC.EOO as EOO
        return EOO.EOOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EOP:
        import spacedatanetwork_astro.sds.REC.EOP as EOP
        return EOP.EOPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EPM:
        import spacedatanetwork_astro.sds.REC.EPM as EPM
        return EPM.EPMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ESL:
        import spacedatanetwork_astro.sds.REC.ESL as ESL
        return ESL.ESLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ETM:
        import spacedatanetwork_astro.sds.REC.ETM as ETM
        return ETM.ETMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EWR:
        import spacedatanetwork_astro.sds.REC.EWR as EWR
        return EWR.EWRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FCS:
        import spacedatanetwork_astro.sds.REC.FCS as FCS
        return FCS.FCST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FPC:
        import spacedatanetwork_astro.sds.REC.FPC as FPC
        return FPC.FPCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FRM:
        import spacedatanetwork_astro.sds.REC.FRM as FRM
        return FRM.FRMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GDI:
        import spacedatanetwork_astro.sds.REC.GDI as GDI
        return GDI.GDIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GEO:
        import spacedatanetwork_astro.sds.REC.GEO as GEO
        return GEO.GEOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GJN:
        import spacedatanetwork_astro.sds.REC.GJN as GJN
        return GJN.GJNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GNO:
        import spacedatanetwork_astro.sds.REC.GNO as GNO
        return GNO.GNOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GPX:
        import spacedatanetwork_astro.sds.REC.GPX as GPX
        return GPX.GPXT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GRV:
        import spacedatanetwork_astro.sds.REC.GRV as GRV
        return GRV.GRVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GVH:
        import spacedatanetwork_astro.sds.REC.GVH as GVH
        return GVH.GVHT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.HEL:
        import spacedatanetwork_astro.sds.REC.HEL as HEL
        return HEL.HELT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.HFC:
        import spacedatanetwork_astro.sds.REC.HFC as HFC
        return HFC.HFCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.HYP:
        import spacedatanetwork_astro.sds.REC.HYP as HYP
        return HYP.HYPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.IDM:
        import spacedatanetwork_astro.sds.REC.IDM as IDM
        return IDM.IDMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ION:
        import spacedatanetwork_astro.sds.REC.ION as ION
        return ION.IONT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.IRO:
        import spacedatanetwork_astro.sds.REC.IRO as IRO
        return IRO.IROT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.KMF:
        import spacedatanetwork_astro.sds.REC.KMF as KMF
        return KMF.KMFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.KML:
        import spacedatanetwork_astro.sds.REC.KML as KML
        return KML.KMLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.KRF:
        import spacedatanetwork_astro.sds.REC.KRF as KRF
        return KRF.KRFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LAM:
        import spacedatanetwork_astro.sds.REC.LAM as LAM
        return LAM.LAMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LCC:
        import spacedatanetwork_astro.sds.REC.LCC as LCC
        return LCC.LCCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LCF:
        import spacedatanetwork_astro.sds.REC.LCF as LCF
        return LCF.LCFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LCH:
        import spacedatanetwork_astro.sds.REC.LCH as LCH
        return LCH.LCHT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LDM:
        import spacedatanetwork_astro.sds.REC.LDM as LDM
        return LDM.LDMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LGR:
        import spacedatanetwork_astro.sds.REC.LGR as LGR
        return LGR.LGRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LKS:
        import spacedatanetwork_astro.sds.REC.LKS as LKS
        return LKS.LKST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LMO:
        import spacedatanetwork_astro.sds.REC.LMO as LMO
        return LMO.LMOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LMR:
        import spacedatanetwork_astro.sds.REC.LMR as LMR
        return LMR.LMRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LMS:
        import spacedatanetwork_astro.sds.REC.LMS as LMS
        return LMS.LMST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LND:
        import spacedatanetwork_astro.sds.REC.LND as LND
        return LND.LNDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LNE:
        import spacedatanetwork_astro.sds.REC.LNE as LNE
        return LNE.LNET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LPF:
        import spacedatanetwork_astro.sds.REC.LPF as LPF
        return LPF.LPFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.LWK:
        import spacedatanetwork_astro.sds.REC.LWK as LWK
        return LWK.LWKT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MBL:
        import spacedatanetwork_astro.sds.REC.MBL as MBL
        return MBL.MBLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MET:
        import spacedatanetwork_astro.sds.REC.MET as MET
        return MET.METT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MFE:
        import spacedatanetwork_astro.sds.REC.MFE as MFE
        return MFE.MFET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MNF:
        import spacedatanetwork_astro.sds.REC.MNF as MNF
        return MNF.MNFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MNV:
        import spacedatanetwork_astro.sds.REC.MNV as MNV
        return MNV.MNVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MPE:
        import spacedatanetwork_astro.sds.REC.MPE as MPE
        return MPE.MPET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MSL:
        import spacedatanetwork_astro.sds.REC.MSL as MSL
        return MSL.MSLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MST:
        import spacedatanetwork_astro.sds.REC.MST as MST
        return MST.MSTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MTI:
        import spacedatanetwork_astro.sds.REC.MTI as MTI
        return MTI.MTIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.NAV:
        import spacedatanetwork_astro.sds.REC.NAV as NAV
        return NAV.NAVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.NUM:
        import spacedatanetwork_astro.sds.REC.NUM as NUM
        return NUM.NUMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OBD:
        import spacedatanetwork_astro.sds.REC.OBD as OBD
        return OBD.OBDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OBT:
        import spacedatanetwork_astro.sds.REC.OBT as OBT
        return OBT.OBTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OCM:
        import spacedatanetwork_astro.sds.REC.OCM as OCM
        return OCM.OCMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OEM:
        import spacedatanetwork_astro.sds.REC.OEM as OEM
        return OEM.OEMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OMM:
        import spacedatanetwork_astro.sds.REC.OMM as OMM
        return OMM.OMMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOA:
        import spacedatanetwork_astro.sds.REC.OOA as OOA
        return OOA.OOAT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOB:
        import spacedatanetwork_astro.sds.REC.OOB as OOB
        return OOB.OOBT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOD:
        import spacedatanetwork_astro.sds.REC.OOD as OOD
        return OOD.OODT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOE:
        import spacedatanetwork_astro.sds.REC.OOE as OOE
        return OOE.OOET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOI:
        import spacedatanetwork_astro.sds.REC.OOI as OOI
        return OOI.OOIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOL:
        import spacedatanetwork_astro.sds.REC.OOL as OOL
        return OOL.OOLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OON:
        import spacedatanetwork_astro.sds.REC.OON as OON
        return OON.OONT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOS:
        import spacedatanetwork_astro.sds.REC.OOS as OOS
        return OOS.OOST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OOT:
        import spacedatanetwork_astro.sds.REC.OOT as OOT
        return OOT.OOTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OPM:
        import spacedatanetwork_astro.sds.REC.OPM as OPM
        return OPM.OPMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OSM:
        import spacedatanetwork_astro.sds.REC.OSM as OSM
        return OSM.OSMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PCF:
        import spacedatanetwork_astro.sds.REC.PCF as PCF
        return PCF.PCFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PHY:
        import spacedatanetwork_astro.sds.REC.PHY as PHY
        return PHY.PHYT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PGM:
        import spacedatanetwork_astro.sds.REC.PGM as PGM
        return PGM.PGMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PIV:
        import spacedatanetwork_astro.sds.REC.PIV as PIV
        return PIV.PIVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PLD:
        import spacedatanetwork_astro.sds.REC.PLD as PLD
        return PLD.PLDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PLG:
        import spacedatanetwork_astro.sds.REC.PLG as PLG
        return PLG.PLGT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PLK:
        import spacedatanetwork_astro.sds.REC.PLK as PLK
        return PLK.PLKT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PNM:
        import spacedatanetwork_astro.sds.REC.PNM as PNM
        return PNM.PNMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PPE:
        import spacedatanetwork_astro.sds.REC.PPE as PPE
        return PPE.PPET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PRG:
        import spacedatanetwork_astro.sds.REC.PRG as PRG
        return PRG.PRGT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PRR:
        import spacedatanetwork_astro.sds.REC.PRR as PRR
        return PRR.PRRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PRW:
        import spacedatanetwork_astro.sds.REC.PRW as PRW
        return PRW.PRWT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PUR:
        import spacedatanetwork_astro.sds.REC.PUR as PUR
        return PUR.PURT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RAF:
        import spacedatanetwork_astro.sds.REC.RAF as RAF
        return RAF.RAFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RBK:
        import spacedatanetwork_astro.sds.REC.RBK as RBK
        return RBK.RBKT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RCF:
        import spacedatanetwork_astro.sds.REC.RCF as RCF
        return RCF.RCFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RDM:
        import spacedatanetwork_astro.sds.REC.RDM as RDM
        return RDM.RDMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RDO:
        import spacedatanetwork_astro.sds.REC.RDO as RDO
        return RDO.RDOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.REM:
        import spacedatanetwork_astro.sds.REC.REM as REM
        return REM.REMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.REV:
        import spacedatanetwork_astro.sds.REC.REV as REV
        return REV.REVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFB:
        import spacedatanetwork_astro.sds.REC.RFB as RFB
        return RFB.RFBT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFE:
        import spacedatanetwork_astro.sds.REC.RFE as RFE
        return RFE.RFET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFM:
        import spacedatanetwork_astro.sds.REC.RFM as RFM
        return RFM.RFMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFO:
        import spacedatanetwork_astro.sds.REC.RFO as RFO
        return RFO.RFOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ROC:
        import spacedatanetwork_astro.sds.REC.ROC as ROC
        return ROC.ROCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SAR:
        import spacedatanetwork_astro.sds.REC.SAR as SAR
        return SAR.SART.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SCM:
        import spacedatanetwork_astro.sds.REC.SCM as SCM
        return SCM.SCMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SDF:
        import spacedatanetwork_astro.sds.REC.SDF as SDF
        return SDF.SDFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SDL:
        import spacedatanetwork_astro.sds.REC.SDL as SDL
        return SDL.SDLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SDR:
        import spacedatanetwork_astro.sds.REC.SDR as SDR
        return SDR.SDRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SEN:
        import spacedatanetwork_astro.sds.REC.SEN as SEN
        return SEN.SENT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SEO:
        import spacedatanetwork_astro.sds.REC.SEO as SEO
        return SEO.SEOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SEV:
        import spacedatanetwork_astro.sds.REC.SEV as SEV
        return SEV.SEVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SHW:
        import spacedatanetwork_astro.sds.REC.SHW as SHW
        return SHW.SHWT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SIT:
        import spacedatanetwork_astro.sds.REC.SIT as SIT
        return SIT.SITT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SKI:
        import spacedatanetwork_astro.sds.REC.SKI as SKI
        return SKI.SKIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SNR:
        import spacedatanetwork_astro.sds.REC.SNR as SNR
        return SNR.SNRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SNW:
        import spacedatanetwork_astro.sds.REC.SNW as SNW
        return SNW.SNWT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SOI:
        import spacedatanetwork_astro.sds.REC.SOI as SOI
        return SOI.SOIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SON:
        import spacedatanetwork_astro.sds.REC.SON as SON
        return SON.SONT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SPP:
        import spacedatanetwork_astro.sds.REC.SPP as SPP
        return SPP.SPPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SPW:
        import spacedatanetwork_astro.sds.REC.SPW as SPW
        return SPW.SPWT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SRI:
        import spacedatanetwork_astro.sds.REC.SRI as SRI
        return SRI.SRIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.STF:
        import spacedatanetwork_astro.sds.REC.STF as STF
        return STF.STFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.STR:
        import spacedatanetwork_astro.sds.REC.STR as STR
        return STR.STRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.STV:
        import spacedatanetwork_astro.sds.REC.STV as STV
        return STV.STVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SWR:
        import spacedatanetwork_astro.sds.REC.SWR as SWR
        return SWR.SWRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TAB:
        import spacedatanetwork_astro.sds.REC.TAB as TAB
        return TAB.TABT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TCF:
        import spacedatanetwork_astro.sds.REC.TCF as TCF
        return TCF.TCFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TDM:
        import spacedatanetwork_astro.sds.REC.TDM as TDM
        return TDM.TDMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TIM:
        import spacedatanetwork_astro.sds.REC.TIM as TIM
        return TIM.TIMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TKG:
        import spacedatanetwork_astro.sds.REC.TKG as TKG
        return TKG.TKGT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TME:
        import spacedatanetwork_astro.sds.REC.TME as TME
        return TME.TMET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TMF:
        import spacedatanetwork_astro.sds.REC.TMF as TMF
        return TMF.TMFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TNR:
        import spacedatanetwork_astro.sds.REC.TNR as TNR
        return TNR.TNRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TPN:
        import spacedatanetwork_astro.sds.REC.TPN as TPN
        return TPN.TPNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRE:
        import spacedatanetwork_astro.sds.REC.TRE as TRE
        return TRE.TRET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRK:
        import spacedatanetwork_astro.sds.REC.TRK as TRK
        return TRK.TRKT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRN:
        import spacedatanetwork_astro.sds.REC.TRN as TRN
        return TRN.TRNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.VCM:
        import spacedatanetwork_astro.sds.REC.VCM as VCM
        return VCM.VCMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.WPN:
        import spacedatanetwork_astro.sds.REC.WPN as WPN
        return WPN.WPNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.WTH:
        import spacedatanetwork_astro.sds.REC.WTH as WTH
        return WTH.WTHT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.XTC:
        import spacedatanetwork_astro.sds.REC.XTC as XTC
        return XTC.XTCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SCV:
        import spacedatanetwork_astro.sds.REC.SCV as SCV
        return SCV.SCVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FSM:
        import spacedatanetwork_astro.sds.REC.FSM as FSM
        return FSM.FSMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FSP:
        import spacedatanetwork_astro.sds.REC.FSP as FSP
        return FSP.FSPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SCC:
        import spacedatanetwork_astro.sds.REC.SCC as SCC
        return SCC.SCCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SCN:
        import spacedatanetwork_astro.sds.REC.SCN as SCN
        return SCN.SCNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.VST:
        import spacedatanetwork_astro.sds.REC.VST as VST
        return VST.VSTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ENT:
        import spacedatanetwork_astro.sds.REC.ENT as ENT
        return ENT.ENTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.VAM:
        import spacedatanetwork_astro.sds.REC.VAM as VAM
        return VAM.VAMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.APP:
        import spacedatanetwork_astro.sds.REC.APP as APP
        return APP.APPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CMT:
        import spacedatanetwork_astro.sds.REC.CMT as CMT
        return CMT.CMTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SCX:
        import spacedatanetwork_astro.sds.REC.SCX as SCX
        return SCX.SCXT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CVG:
        import spacedatanetwork_astro.sds.REC.CVG as CVG
        return CVG.CVGT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PKB:
        import spacedatanetwork_astro.sds.REC.PKB as PKB
        return PKB.PKBT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RPT:
        import spacedatanetwork_astro.sds.REC.RPT as RPT
        return RPT.RPTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.STO:
        import spacedatanetwork_astro.sds.REC.STO as STO
        return STO.STOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SUB:
        import spacedatanetwork_astro.sds.REC.SUB as SUB
        return SUB.SUBT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.WKS:
        import spacedatanetwork_astro.sds.REC.WKS as WKS
        return WKS.WKST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CPS:
        import spacedatanetwork_astro.sds.REC.CPS as CPS
        return CPS.CPST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FSB:
        import spacedatanetwork_astro.sds.REC.FSB as FSB
        return FSB.FSBT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.FSO:
        import spacedatanetwork_astro.sds.REC.FSO as FSO
        return FSO.FSOT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GST:
        import spacedatanetwork_astro.sds.REC.GST as GST
        return GST.GSTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MDP:
        import spacedatanetwork_astro.sds.REC.MDP as MDP
        return MDP.MDPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MDS:
        import spacedatanetwork_astro.sds.REC.MDS as MDS
        return MDS.MDST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PNL:
        import spacedatanetwork_astro.sds.REC.PNL as PNL
        return PNL.PNLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SHC:
        import spacedatanetwork_astro.sds.REC.SHC as SHC
        return SHC.SHCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CES:
        import spacedatanetwork_astro.sds.REC.CES as CES
        return CES.CEST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.QEM:
        import spacedatanetwork_astro.sds.REC.QEM as QEM
        return QEM.QEMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SBM:
        import spacedatanetwork_astro.sds.REC.SBM as SBM
        return SBM.SBMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PMM:
        import spacedatanetwork_astro.sds.REC.PMM as PMM
        return PMM.PMMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.OPP:
        import spacedatanetwork_astro.sds.REC.OPP as OPP
        return OPP.OPPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.IQC:
        import spacedatanetwork_astro.sds.REC.IQC as IQC
        return IQC.IQCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CNP:
        import spacedatanetwork_astro.sds.REC.CNP as CNP
        return CNP.CNPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CMR:
        import spacedatanetwork_astro.sds.REC.CMR as CMR
        return CMR.CMRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TBS:
        import spacedatanetwork_astro.sds.REC.TBS as TBS
        return TBS.TBST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CCT:
        import spacedatanetwork_astro.sds.REC.CCT as CCT
        return CCT.CCTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ACI:
        import spacedatanetwork_astro.sds.REC.ACI as ACI
        return ACI.ACIT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CVP:
        import spacedatanetwork_astro.sds.REC.CVP as CVP
        return CVP.CVPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFL:
        import spacedatanetwork_astro.sds.REC.RFL as RFL
        return RFL.RFLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RFS:
        import spacedatanetwork_astro.sds.REC.RFS as RFS
        return RFS.RFST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRS:
        import spacedatanetwork_astro.sds.REC.TRS as TRS
        return TRS.TRST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GNP:
        import spacedatanetwork_astro.sds.REC.GNP as GNP
        return GNP.GNPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.DTT:
        import spacedatanetwork_astro.sds.REC.DTT as DTT
        return DTT.DTTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.AVL:
        import spacedatanetwork_astro.sds.REC.AVL as AVL
        return AVL.AVLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TFN:
        import spacedatanetwork_astro.sds.REC.TFN as TFN
        return TFN.TFNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TMS:
        import spacedatanetwork_astro.sds.REC.TMS as TMS
        return TMS.TMST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.VEP:
        import spacedatanetwork_astro.sds.REC.VEP as VEP
        return VEP.VEPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EGP:
        import spacedatanetwork_astro.sds.REC.EGP as EGP
        return EGP.EGPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.APL:
        import spacedatanetwork_astro.sds.REC.APL as APL
        return APL.APLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EMC:
        import spacedatanetwork_astro.sds.REC.EMC as EMC
        return EMC.EMCT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EPF:
        import spacedatanetwork_astro.sds.REC.EPF as EPF
        return EPF.EPFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GEL:
        import spacedatanetwork_astro.sds.REC.GEL as GEL
        return GEL.GELT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PAP:
        import spacedatanetwork_astro.sds.REC.PAP as PAP
        return PAP.PAPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.RSD:
        import spacedatanetwork_astro.sds.REC.RSD as RSD
        return RSD.RSDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.IRM:
        import spacedatanetwork_astro.sds.REC.IRM as IRM
        return IRM.IRMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.VCF:
        import spacedatanetwork_astro.sds.REC.VCF as VCF
        return VCF.VCFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.STX:
        import spacedatanetwork_astro.sds.REC.STX as STX
        return STX.STXT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TXS:
        import spacedatanetwork_astro.sds.REC.TXS as TXS
        return TXS.TXST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.BPF:
        import spacedatanetwork_astro.sds.REC.BPF as BPF
        return BPF.BPFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.EVL:
        import spacedatanetwork_astro.sds.REC.EVL as EVL
        return EVL.EVLT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PCE:
        import spacedatanetwork_astro.sds.REC.PCE as PCE
        return PCE.PCET.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.NCD:
        import spacedatanetwork_astro.sds.REC.NCD as NCD
        return NCD.NCDT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.MEM:
        import spacedatanetwork_astro.sds.REC.MEM as MEM
        return MEM.MEMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ODR:
        import spacedatanetwork_astro.sds.REC.ODR as ODR
        return ODR.ODRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRH:
        import spacedatanetwork_astro.sds.REC.TRH as TRH
        return TRH.TRHT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.SLP:
        import spacedatanetwork_astro.sds.REC.SLP as SLP
        return SLP.SLPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.PSS:
        import spacedatanetwork_astro.sds.REC.PSS as PSS
        return PSS.PSST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ICN:
        import spacedatanetwork_astro.sds.REC.ICN as ICN
        return ICN.ICNT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRP:
        import spacedatanetwork_astro.sds.REC.TRP as TRP
        return TRP.TRPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TRV:
        import spacedatanetwork_astro.sds.REC.TRV as TRV
        return TRV.TRVT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.ACT:
        import spacedatanetwork_astro.sds.REC.ACT as ACT
        return ACT.ACTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.AGR:
        import spacedatanetwork_astro.sds.REC.AGR as AGR
        return AGR.AGRT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.NDS:
        import spacedatanetwork_astro.sds.REC.NDS as NDS
        return NDS.NDST.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.NST:
        import spacedatanetwork_astro.sds.REC.NST as NST
        return NST.NSTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.QRP:
        import spacedatanetwork_astro.sds.REC.QRP as QRP
        return QRP.QRPT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.TCT:
        import spacedatanetwork_astro.sds.REC.TCT as TCT
        return TCT.TCTT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.WXF:
        import spacedatanetwork_astro.sds.REC.WXF as WXF
        return WXF.WXFT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.CLM:
        import spacedatanetwork_astro.sds.REC.CLM as CLM
        return CLM.CLMT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == RecordType.GCT:
        import spacedatanetwork_astro.sds.REC.GCT as GCT
        return GCT.GCTT.InitFromBuf(table.Bytes, table.Pos)
    return None
