# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EstimationEpoch(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # EstimationEpoch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstimationEpoch
    def JdDay(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EstimationEpoch
    def Seconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateEstimationEpoch(builder, jdDay, seconds):
    builder.Prep(8, 16)
    builder.PrependFloat64(seconds)
    builder.PrependFloat64(jdDay)
    return builder.Offset()


class EstimationEpochT(object):

    # EstimationEpochT
    def __init__(
        self,
        jdDay = 0.0,
        seconds = 0.0,
    ):
        self.jdDay = jdDay  # type: float
        self.seconds = seconds  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        estimationEpoch = EstimationEpoch()
        estimationEpoch.Init(buf, pos)
        return cls.InitFromObj(estimationEpoch)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, estimationEpoch):
        x = EstimationEpochT()
        x._UnPack(estimationEpoch)
        return x

    # EstimationEpochT
    def _UnPack(self, estimationEpoch):
        if estimationEpoch is None:
            return
        self.jdDay = estimationEpoch.JdDay()
        self.seconds = estimationEpoch.Seconds()

    # EstimationEpochT
    def Pack(self, builder):
        return CreateEstimationEpoch(builder, self.jdDay, self.seconds)
