# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EstimationResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EstimationResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEstimationResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EstimationResultBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x24\x45\x53\x54", size_prefixed=size_prefixed)

    # EstimationResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstimationResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EstimationResult
    def Estimate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from spacedatanetwork_astro.invoke.orbpro.estimation.EstimationState import EstimationState
            obj = EstimationState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EstimationResult
    def FilterHistory(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 696
            from spacedatanetwork_astro.invoke.orbpro.estimation.FilterEpoch import FilterEpoch
            obj = FilterEpoch()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EstimationResult
    def FilterHistoryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def FilterHistoryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # EstimationResult
    def Residuals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # EstimationResult
    def ResidualsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # EstimationResult
    def ResidualsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def ResidualsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Row-major 6x6 covariance blocks, one per batch iteration, in iteration
    # order. Empty for sequential estimators.
    # EstimationResult
    def IterationCovariances(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # EstimationResult
    def IterationCovariancesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # EstimationResult
    def IterationCovariancesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def IterationCovariancesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # EstimationResult
    def RejectedObservationIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EstimationResult
    def RejectedObservationIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # EstimationResult
    def RejectedObservationIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def RejectedObservationIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # EstimationResult
    def OdrRecord(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # EstimationResult
    def OdrRecordAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # EstimationResult
    def OdrRecordLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def OdrRecordIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # EstimationResult
    def OcmRecord(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # EstimationResult
    def OcmRecordAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # EstimationResult
    def OcmRecordLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationResult
    def OcmRecordIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # EstimationResult
    def ErrorMessage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EstimationResult
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EstimationResultStart(builder):
    builder.StartObject(10)

def Start(builder):
    EstimationResultStart(builder)

def EstimationResultAddStatus(builder, status):
    builder.PrependInt32Slot(0, status, 0)

def AddStatus(builder, status):
    EstimationResultAddStatus(builder, status)

def EstimationResultAddEstimate(builder, estimate):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(estimate), 0)

def AddEstimate(builder, estimate):
    EstimationResultAddEstimate(builder, estimate)

def EstimationResultAddFilterHistory(builder, filterHistory):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(filterHistory), 0)

def AddFilterHistory(builder, filterHistory):
    EstimationResultAddFilterHistory(builder, filterHistory)

def EstimationResultStartFilterHistoryVector(builder, numElems):
    return builder.StartVector(696, numElems, 8)

def StartFilterHistoryVector(builder, numElems):
    return EstimationResultStartFilterHistoryVector(builder, numElems)

def EstimationResultCreateFilterHistoryVector(builder, data):
    data = list(data)
    builder.StartVector(696, len(data), 8)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateFilterHistoryVector(builder, data):
    EstimationResultCreateFilterHistoryVector(builder, data)

def EstimationResultAddResiduals(builder, residuals):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(residuals), 0)

def AddResiduals(builder, residuals):
    EstimationResultAddResiduals(builder, residuals)

def EstimationResultStartResidualsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartResidualsVector(builder, numElems):
    return EstimationResultStartResidualsVector(builder, numElems)

def EstimationResultCreateResidualsVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependFloat64(item)
    return builder.EndVector()

def CreateResidualsVector(builder, data):
    EstimationResultCreateResidualsVector(builder, data)

def EstimationResultAddIterationCovariances(builder, iterationCovariances):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(iterationCovariances), 0)

def AddIterationCovariances(builder, iterationCovariances):
    EstimationResultAddIterationCovariances(builder, iterationCovariances)

def EstimationResultStartIterationCovariancesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartIterationCovariancesVector(builder, numElems):
    return EstimationResultStartIterationCovariancesVector(builder, numElems)

def EstimationResultCreateIterationCovariancesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependFloat64(item)
    return builder.EndVector()

def CreateIterationCovariancesVector(builder, data):
    EstimationResultCreateIterationCovariancesVector(builder, data)

def EstimationResultAddRejectedObservationIndices(builder, rejectedObservationIndices):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rejectedObservationIndices), 0)

def AddRejectedObservationIndices(builder, rejectedObservationIndices):
    EstimationResultAddRejectedObservationIndices(builder, rejectedObservationIndices)

def EstimationResultStartRejectedObservationIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRejectedObservationIndicesVector(builder, numElems):
    return EstimationResultStartRejectedObservationIndicesVector(builder, numElems)

def EstimationResultCreateRejectedObservationIndicesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateRejectedObservationIndicesVector(builder, data):
    EstimationResultCreateRejectedObservationIndicesVector(builder, data)

def EstimationResultAddOdrRecord(builder, odrRecord):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(odrRecord), 0)

def AddOdrRecord(builder, odrRecord):
    EstimationResultAddOdrRecord(builder, odrRecord)

def EstimationResultStartOdrRecordVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartOdrRecordVector(builder, numElems):
    return EstimationResultStartOdrRecordVector(builder, numElems)

def EstimationResultCreateOdrRecordVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateOdrRecordVector(builder, data):
    EstimationResultCreateOdrRecordVector(builder, data)

def EstimationResultAddOcmRecord(builder, ocmRecord):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(ocmRecord), 0)

def AddOcmRecord(builder, ocmRecord):
    EstimationResultAddOcmRecord(builder, ocmRecord)

def EstimationResultStartOcmRecordVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartOcmRecordVector(builder, numElems):
    return EstimationResultStartOcmRecordVector(builder, numElems)

def EstimationResultCreateOcmRecordVector(builder, data):
    data = list(data)
    builder.StartVector(1, len(data), 1)
    for item in reversed(data):
        builder.PrependUint8(item)
    return builder.EndVector()

def CreateOcmRecordVector(builder, data):
    EstimationResultCreateOcmRecordVector(builder, data)

def EstimationResultAddErrorMessage(builder, errorMessage):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(errorMessage), 0)

def AddErrorMessage(builder, errorMessage):
    EstimationResultAddErrorMessage(builder, errorMessage)

def EstimationResultAddTraceId(builder, traceId):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)

def AddTraceId(builder, traceId):
    EstimationResultAddTraceId(builder, traceId)

def EstimationResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return EstimationResultEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationState
import spacedatanetwork_astro.invoke.orbpro.estimation.FilterEpoch
try:
    from typing import List, Optional
except:
    pass

class EstimationResultT(object):

    # EstimationResultT
    def __init__(
        self,
        status = 0,
        estimate = None,
        filterHistory = None,
        residuals = None,
        iterationCovariances = None,
        rejectedObservationIndices = None,
        odrRecord = None,
        ocmRecord = None,
        errorMessage = None,
        traceId = None,
    ):
        self.status = status  # type: int
        self.estimate = estimate  # type: Optional[orbpro.estimation.EstimationState.EstimationStateT]
        self.filterHistory = filterHistory  # type: Optional[List[orbpro.estimation.FilterEpoch.FilterEpochT]]
        self.residuals = residuals  # type: Optional[List[float]]
        self.iterationCovariances = iterationCovariances  # type: Optional[List[float]]
        self.rejectedObservationIndices = rejectedObservationIndices  # type: Optional[List[int]]
        self.odrRecord = odrRecord  # type: Optional[List[int]]
        self.ocmRecord = ocmRecord  # type: Optional[List[int]]
        self.errorMessage = errorMessage  # type: Optional[str]
        self.traceId = traceId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        estimationResult = EstimationResult()
        estimationResult.Init(buf, pos)
        return cls.InitFromObj(estimationResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, estimationResult):
        x = EstimationResultT()
        x._UnPack(estimationResult)
        return x

    # EstimationResultT
    def _UnPack(self, estimationResult):
        if estimationResult is None:
            return
        self.status = estimationResult.Status()
        if estimationResult.Estimate() is not None:
            self.estimate = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationState.EstimationStateT.InitFromObj(estimationResult.Estimate())
        if not estimationResult.FilterHistoryIsNone():
            self.filterHistory = []
            for i in range(estimationResult.FilterHistoryLength()):
                if estimationResult.FilterHistory(i) is None:
                    self.filterHistory.append(None)
                else:
                    filterEpoch_ = spacedatanetwork_astro.invoke.orbpro.estimation.FilterEpoch.FilterEpochT.InitFromObj(estimationResult.FilterHistory(i))
                    self.filterHistory.append(filterEpoch_)
        if not estimationResult.ResidualsIsNone():
            if np is None:
                self.residuals = []
                for i in range(estimationResult.ResidualsLength()):
                    self.residuals.append(estimationResult.Residuals(i))
            else:
                self.residuals = estimationResult.ResidualsAsNumpy()
        if not estimationResult.IterationCovariancesIsNone():
            if np is None:
                self.iterationCovariances = []
                for i in range(estimationResult.IterationCovariancesLength()):
                    self.iterationCovariances.append(estimationResult.IterationCovariances(i))
            else:
                self.iterationCovariances = estimationResult.IterationCovariancesAsNumpy()
        if not estimationResult.RejectedObservationIndicesIsNone():
            if np is None:
                self.rejectedObservationIndices = []
                for i in range(estimationResult.RejectedObservationIndicesLength()):
                    self.rejectedObservationIndices.append(estimationResult.RejectedObservationIndices(i))
            else:
                self.rejectedObservationIndices = estimationResult.RejectedObservationIndicesAsNumpy()
        if not estimationResult.OdrRecordIsNone():
            if np is None:
                self.odrRecord = []
                for i in range(estimationResult.OdrRecordLength()):
                    self.odrRecord.append(estimationResult.OdrRecord(i))
            else:
                self.odrRecord = estimationResult.OdrRecordAsNumpy()
        if not estimationResult.OcmRecordIsNone():
            if np is None:
                self.ocmRecord = []
                for i in range(estimationResult.OcmRecordLength()):
                    self.ocmRecord.append(estimationResult.OcmRecord(i))
            else:
                self.ocmRecord = estimationResult.OcmRecordAsNumpy()
        self.errorMessage = estimationResult.ErrorMessage()
        self.traceId = estimationResult.TraceId()

    # EstimationResultT
    def Pack(self, builder):
        if self.filterHistory is not None:
            EstimationResultStartFilterHistoryVector(builder, len(self.filterHistory))
            for i in reversed(range(len(self.filterHistory))):
                self.filterHistory[i].Pack(builder)
            filterHistory = builder.EndVector()
        if self.residuals is not None:
            if np is not None and type(self.residuals) is np.ndarray:
                residuals = builder.CreateNumpyVector(self.residuals)
            else:
                EstimationResultStartResidualsVector(builder, len(self.residuals))
                for i in reversed(range(len(self.residuals))):
                    builder.PrependFloat64(self.residuals[i])
                residuals = builder.EndVector()
        if self.iterationCovariances is not None:
            if np is not None and type(self.iterationCovariances) is np.ndarray:
                iterationCovariances = builder.CreateNumpyVector(self.iterationCovariances)
            else:
                EstimationResultStartIterationCovariancesVector(builder, len(self.iterationCovariances))
                for i in reversed(range(len(self.iterationCovariances))):
                    builder.PrependFloat64(self.iterationCovariances[i])
                iterationCovariances = builder.EndVector()
        if self.rejectedObservationIndices is not None:
            if np is not None and type(self.rejectedObservationIndices) is np.ndarray:
                rejectedObservationIndices = builder.CreateNumpyVector(self.rejectedObservationIndices)
            else:
                EstimationResultStartRejectedObservationIndicesVector(builder, len(self.rejectedObservationIndices))
                for i in reversed(range(len(self.rejectedObservationIndices))):
                    builder.PrependUint32(self.rejectedObservationIndices[i])
                rejectedObservationIndices = builder.EndVector()
        if self.odrRecord is not None:
            if np is not None and type(self.odrRecord) is np.ndarray:
                odrRecord = builder.CreateNumpyVector(self.odrRecord)
            else:
                EstimationResultStartOdrRecordVector(builder, len(self.odrRecord))
                for i in reversed(range(len(self.odrRecord))):
                    builder.PrependUint8(self.odrRecord[i])
                odrRecord = builder.EndVector()
        if self.ocmRecord is not None:
            if np is not None and type(self.ocmRecord) is np.ndarray:
                ocmRecord = builder.CreateNumpyVector(self.ocmRecord)
            else:
                EstimationResultStartOcmRecordVector(builder, len(self.ocmRecord))
                for i in reversed(range(len(self.ocmRecord))):
                    builder.PrependUint8(self.ocmRecord[i])
                ocmRecord = builder.EndVector()
        if self.errorMessage is not None:
            errorMessage = builder.CreateString(self.errorMessage)
        if self.traceId is not None:
            traceId = builder.CreateString(self.traceId)
        EstimationResultStart(builder)
        EstimationResultAddStatus(builder, self.status)
        if self.estimate is not None:
            estimate = self.estimate.Pack(builder)
            EstimationResultAddEstimate(builder, estimate)
        if self.filterHistory is not None:
            EstimationResultAddFilterHistory(builder, filterHistory)
        if self.residuals is not None:
            EstimationResultAddResiduals(builder, residuals)
        if self.iterationCovariances is not None:
            EstimationResultAddIterationCovariances(builder, iterationCovariances)
        if self.rejectedObservationIndices is not None:
            EstimationResultAddRejectedObservationIndices(builder, rejectedObservationIndices)
        if self.odrRecord is not None:
            EstimationResultAddOdrRecord(builder, odrRecord)
        if self.ocmRecord is not None:
            EstimationResultAddOcmRecord(builder, ocmRecord)
        if self.errorMessage is not None:
            EstimationResultAddErrorMessage(builder, errorMessage)
        if self.traceId is not None:
            EstimationResultAddTraceId(builder, traceId)
        estimationResult = EstimationResultEnd(builder)
        return estimationResult
