# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Fixed configuration copied byte-for-byte in every runtime. initial_state
# is Cartesian [x,y,z,vx,vy,vz] in metres and metres per second; covariance
# is row-major 6 by 6 in matching SI units.
class EstimationConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 448

    # EstimationConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstimationConfig
    def InitialEpoch(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # EstimationConfig
    def InitialState(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + i * 8)) for i in range(self.InitialStateLength())]
        elif j >= 0 and j < self.InitialStateLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + j * 8))
        else:
            return None

    # EstimationConfig
    def InitialStateAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 16, self.InitialStateLength())

    # EstimationConfig
    def InitialStateLength(self):
        return 6

    # EstimationConfig
    def InitialStateIsNone(self):
        return False

    # EstimationConfig
    def InitialCovariance(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64 + i * 8)) for i in range(self.InitialCovarianceLength())]
        elif j >= 0 and j < self.InitialCovarianceLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64 + j * 8))
        else:
            return None

    # EstimationConfig
    def InitialCovarianceAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 64, self.InitialCovarianceLength())

    # EstimationConfig
    def InitialCovarianceLength(self):
        return 36

    # EstimationConfig
    def InitialCovarianceIsNone(self):
        return False

    # EstimationConfig
    def ProcessNoiseSpectralDensity(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(352 + i * 8)) for i in range(self.ProcessNoiseSpectralDensityLength())]
        elif j >= 0 and j < self.ProcessNoiseSpectralDensityLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(352 + j * 8))
        else:
            return None

    # EstimationConfig
    def ProcessNoiseSpectralDensityAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 352, self.ProcessNoiseSpectralDensityLength())

    # EstimationConfig
    def ProcessNoiseSpectralDensityLength(self):
        return 6

    # EstimationConfig
    def ProcessNoiseSpectralDensityIsNone(self):
        return False

    # EstimationConfig
    def StateConvergenceTolerance(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(400))
    # EstimationConfig
    def RmsConvergenceTolerance(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(408))
    # EstimationConfig
    def SigmaEditThreshold(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(416))
    # EstimationConfig
    def DynamicModelCorrelationTimeSeconds(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(424))
    # EstimationConfig
    def MaximumIterations(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(432))
    # EstimationConfig
    def ReferenceFrame(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(436))
    # EstimationConfig
    def Estimator(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(437))
    # EstimationConfig
    def ProcessNoise(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(438))
    # EstimationConfig
    def Flags(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(440))

def CreateEstimationConfig(builder, initialEpoch_jdDay, initialEpoch_seconds, initialState, initialCovariance, processNoiseSpectralDensity, stateConvergenceTolerance, rmsConvergenceTolerance, sigmaEditThreshold, dynamicModelCorrelationTimeSeconds, maximumIterations, referenceFrame, estimator, processNoise, flags):
    builder.Prep(8, 448)
    builder.Pad(6)
    builder.PrependUint16(flags)
    builder.Pad(1)
    builder.PrependUint8(processNoise)
    builder.PrependUint8(estimator)
    builder.PrependUint8(referenceFrame)
    builder.PrependUint32(maximumIterations)
    builder.PrependFloat64(dynamicModelCorrelationTimeSeconds)
    builder.PrependFloat64(sigmaEditThreshold)
    builder.PrependFloat64(rmsConvergenceTolerance)
    builder.PrependFloat64(stateConvergenceTolerance)
    for _idx0 in range(6 , 0, -1):
        builder.PrependFloat64(processNoiseSpectralDensity[_idx0-1])
    for _idx0 in range(36 , 0, -1):
        builder.PrependFloat64(initialCovariance[_idx0-1])
    for _idx0 in range(6 , 0, -1):
        builder.PrependFloat64(initialState[_idx0-1])
    builder.Prep(8, 16)
    builder.PrependFloat64(initialEpoch_seconds)
    builder.PrependFloat64(initialEpoch_jdDay)
    return builder.Offset()

import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch
try:
    from typing import List, Optional
except:
    pass

class EstimationConfigT(object):

    # EstimationConfigT
    def __init__(
        self,
        initialEpoch = None,
        initialState = None,
        initialCovariance = None,
        processNoiseSpectralDensity = None,
        stateConvergenceTolerance = 0.0,
        rmsConvergenceTolerance = 0.0,
        sigmaEditThreshold = 0.0,
        dynamicModelCorrelationTimeSeconds = 0.0,
        maximumIterations = 0,
        referenceFrame = 0,
        estimator = 0,
        processNoise = 0,
        flags = 0,
    ):
        self.initialEpoch = initialEpoch  # type: Optional[orbpro.estimation.EstimationEpoch.EstimationEpochT]
        self.initialState = initialState  # type: Optional[List[float]]
        self.initialCovariance = initialCovariance  # type: Optional[List[float]]
        self.processNoiseSpectralDensity = processNoiseSpectralDensity  # type: Optional[List[float]]
        self.stateConvergenceTolerance = stateConvergenceTolerance  # type: float
        self.rmsConvergenceTolerance = rmsConvergenceTolerance  # type: float
        self.sigmaEditThreshold = sigmaEditThreshold  # type: float
        self.dynamicModelCorrelationTimeSeconds = dynamicModelCorrelationTimeSeconds  # type: float
        self.maximumIterations = maximumIterations  # type: int
        self.referenceFrame = referenceFrame  # type: int
        self.estimator = estimator  # type: int
        self.processNoise = processNoise  # type: int
        self.flags = flags  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        estimationConfig = EstimationConfig()
        estimationConfig.Init(buf, pos)
        return cls.InitFromObj(estimationConfig)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, estimationConfig):
        x = EstimationConfigT()
        x._UnPack(estimationConfig)
        return x

    # EstimationConfigT
    def _UnPack(self, estimationConfig):
        if estimationConfig is None:
            return
        if estimationConfig.InitialEpoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()) is not None:
            self.initialEpoch = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpochT.InitFromObj(estimationConfig.InitialEpoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()))
        if not estimationConfig.InitialStateIsNone():
            if np is None:
                self.initialState = []
                for i in range(estimationConfig.InitialStateLength()):
                    self.initialState.append(estimationConfig.InitialState(i))
            else:
                self.initialState = estimationConfig.InitialStateAsNumpy()
        if not estimationConfig.InitialCovarianceIsNone():
            if np is None:
                self.initialCovariance = []
                for i in range(estimationConfig.InitialCovarianceLength()):
                    self.initialCovariance.append(estimationConfig.InitialCovariance(i))
            else:
                self.initialCovariance = estimationConfig.InitialCovarianceAsNumpy()
        if not estimationConfig.ProcessNoiseSpectralDensityIsNone():
            if np is None:
                self.processNoiseSpectralDensity = []
                for i in range(estimationConfig.ProcessNoiseSpectralDensityLength()):
                    self.processNoiseSpectralDensity.append(estimationConfig.ProcessNoiseSpectralDensity(i))
            else:
                self.processNoiseSpectralDensity = estimationConfig.ProcessNoiseSpectralDensityAsNumpy()
        self.stateConvergenceTolerance = estimationConfig.StateConvergenceTolerance()
        self.rmsConvergenceTolerance = estimationConfig.RmsConvergenceTolerance()
        self.sigmaEditThreshold = estimationConfig.SigmaEditThreshold()
        self.dynamicModelCorrelationTimeSeconds = estimationConfig.DynamicModelCorrelationTimeSeconds()
        self.maximumIterations = estimationConfig.MaximumIterations()
        self.referenceFrame = estimationConfig.ReferenceFrame()
        self.estimator = estimationConfig.Estimator()
        self.processNoise = estimationConfig.ProcessNoise()
        self.flags = estimationConfig.Flags()

    # EstimationConfigT
    def Pack(self, builder):
        return CreateEstimationConfig(builder, self.initialEpoch.jdDay, self.initialEpoch.seconds, self.initialState, self.initialCovariance, self.processNoiseSpectralDensity, self.stateConvergenceTolerance, self.rmsConvergenceTolerance, self.sigmaEditThreshold, self.dynamicModelCorrelationTimeSeconds, self.maximumIterations, self.referenceFrame, self.estimator, self.processNoise, self.flags)
