# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Request/result wire. observations are decoded from $TDM/$CRD before they
# cross this family boundary; their source record identifiers remain on the
# request for a complete provenance trail.
class EstimationRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EstimationRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEstimationRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EstimationRequestBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x24\x45\x53\x54", size_prefixed=size_prefixed)

    # EstimationRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstimationRequest
    def Config(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from spacedatanetwork_astro.invoke.orbpro.estimation.EstimationConfig import EstimationConfig
            obj = EstimationConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EstimationRequest
    def Observations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 376
            from spacedatanetwork_astro.invoke.orbpro.estimation.EstimationObservation import EstimationObservation
            obj = EstimationObservation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EstimationRequest
    def ObservationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationRequest
    def ObservationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # EstimationRequest
    def ErrorModels(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 72
            from spacedatanetwork_astro.invoke.orbpro.estimation.EstimationErrorModel import EstimationErrorModel
            obj = EstimationErrorModel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EstimationRequest
    def ErrorModelsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationRequest
    def ErrorModelsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # EstimationRequest
    def SourceRecordIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # EstimationRequest
    def SourceRecordIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EstimationRequest
    def SourceRecordIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # EstimationRequest
    def PropagatorPortId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EstimationRequest
    def PropagatorCapability(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EstimationRequest
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EstimationRequestStart(builder):
    builder.StartObject(7)

def Start(builder):
    EstimationRequestStart(builder)

def EstimationRequestAddConfig(builder, config):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(config), 0)

def AddConfig(builder, config):
    EstimationRequestAddConfig(builder, config)

def EstimationRequestAddObservations(builder, observations):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(observations), 0)

def AddObservations(builder, observations):
    EstimationRequestAddObservations(builder, observations)

def EstimationRequestStartObservationsVector(builder, numElems):
    return builder.StartVector(376, numElems, 8)

def StartObservationsVector(builder, numElems):
    return EstimationRequestStartObservationsVector(builder, numElems)

def EstimationRequestCreateObservationsVector(builder, data):
    data = list(data)
    builder.StartVector(376, len(data), 8)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateObservationsVector(builder, data):
    EstimationRequestCreateObservationsVector(builder, data)

def EstimationRequestAddErrorModels(builder, errorModels):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(errorModels), 0)

def AddErrorModels(builder, errorModels):
    EstimationRequestAddErrorModels(builder, errorModels)

def EstimationRequestStartErrorModelsVector(builder, numElems):
    return builder.StartVector(72, numElems, 8)

def StartErrorModelsVector(builder, numElems):
    return EstimationRequestStartErrorModelsVector(builder, numElems)

def EstimationRequestCreateErrorModelsVector(builder, data):
    data = list(data)
    builder.StartVector(72, len(data), 8)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateErrorModelsVector(builder, data):
    EstimationRequestCreateErrorModelsVector(builder, data)

def EstimationRequestAddSourceRecordIds(builder, sourceRecordIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sourceRecordIds), 0)

def AddSourceRecordIds(builder, sourceRecordIds):
    EstimationRequestAddSourceRecordIds(builder, sourceRecordIds)

def EstimationRequestStartSourceRecordIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSourceRecordIdsVector(builder, numElems):
    return EstimationRequestStartSourceRecordIdsVector(builder, numElems)

def EstimationRequestCreateSourceRecordIdsVector(builder, data):
    return builder.CreateVectorOfTables(data)

def CreateSourceRecordIdsVector(builder, data):
    EstimationRequestCreateSourceRecordIdsVector(builder, data)

def EstimationRequestAddPropagatorPortId(builder, propagatorPortId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(propagatorPortId), 0)

def AddPropagatorPortId(builder, propagatorPortId):
    EstimationRequestAddPropagatorPortId(builder, propagatorPortId)

def EstimationRequestAddPropagatorCapability(builder, propagatorCapability):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(propagatorCapability), 0)

def AddPropagatorCapability(builder, propagatorCapability):
    EstimationRequestAddPropagatorCapability(builder, propagatorCapability)

def EstimationRequestAddTraceId(builder, traceId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)

def AddTraceId(builder, traceId):
    EstimationRequestAddTraceId(builder, traceId)

def EstimationRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return EstimationRequestEnd(builder)

import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationConfig
import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationErrorModel
import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationObservation
try:
    from typing import List, Optional
except:
    pass

class EstimationRequestT(object):

    # EstimationRequestT
    def __init__(
        self,
        config = None,
        observations = None,
        errorModels = None,
        sourceRecordIds = None,
        propagatorPortId = None,
        propagatorCapability = None,
        traceId = None,
    ):
        self.config = config  # type: Optional[orbpro.estimation.EstimationConfig.EstimationConfigT]
        self.observations = observations  # type: Optional[List[orbpro.estimation.EstimationObservation.EstimationObservationT]]
        self.errorModels = errorModels  # type: Optional[List[orbpro.estimation.EstimationErrorModel.EstimationErrorModelT]]
        self.sourceRecordIds = sourceRecordIds  # type: Optional[List[Optional[str]]]
        self.propagatorPortId = propagatorPortId  # type: Optional[str]
        self.propagatorCapability = propagatorCapability  # type: Optional[str]
        self.traceId = traceId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        estimationRequest = EstimationRequest()
        estimationRequest.Init(buf, pos)
        return cls.InitFromObj(estimationRequest)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, estimationRequest):
        x = EstimationRequestT()
        x._UnPack(estimationRequest)
        return x

    # EstimationRequestT
    def _UnPack(self, estimationRequest):
        if estimationRequest is None:
            return
        if estimationRequest.Config() is not None:
            self.config = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationConfig.EstimationConfigT.InitFromObj(estimationRequest.Config())
        if not estimationRequest.ObservationsIsNone():
            self.observations = []
            for i in range(estimationRequest.ObservationsLength()):
                if estimationRequest.Observations(i) is None:
                    self.observations.append(None)
                else:
                    estimationObservation_ = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationObservation.EstimationObservationT.InitFromObj(estimationRequest.Observations(i))
                    self.observations.append(estimationObservation_)
        if not estimationRequest.ErrorModelsIsNone():
            self.errorModels = []
            for i in range(estimationRequest.ErrorModelsLength()):
                if estimationRequest.ErrorModels(i) is None:
                    self.errorModels.append(None)
                else:
                    estimationErrorModel_ = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationErrorModel.EstimationErrorModelT.InitFromObj(estimationRequest.ErrorModels(i))
                    self.errorModels.append(estimationErrorModel_)
        if not estimationRequest.SourceRecordIdsIsNone():
            self.sourceRecordIds = []
            for i in range(estimationRequest.SourceRecordIdsLength()):
                self.sourceRecordIds.append(estimationRequest.SourceRecordIds(i))
        self.propagatorPortId = estimationRequest.PropagatorPortId()
        self.propagatorCapability = estimationRequest.PropagatorCapability()
        self.traceId = estimationRequest.TraceId()

    # EstimationRequestT
    def Pack(self, builder):
        if self.observations is not None:
            EstimationRequestStartObservationsVector(builder, len(self.observations))
            for i in reversed(range(len(self.observations))):
                self.observations[i].Pack(builder)
            observations = builder.EndVector()
        if self.errorModels is not None:
            EstimationRequestStartErrorModelsVector(builder, len(self.errorModels))
            for i in reversed(range(len(self.errorModels))):
                self.errorModels[i].Pack(builder)
            errorModels = builder.EndVector()
        if self.sourceRecordIds is not None:
            sourceRecordIdslist = []
            for i in range(len(self.sourceRecordIds)):
                sourceRecordIdslist.append(builder.CreateString(self.sourceRecordIds[i]))
            EstimationRequestStartSourceRecordIdsVector(builder, len(self.sourceRecordIds))
            for i in reversed(range(len(self.sourceRecordIds))):
                builder.PrependUOffsetTRelative(sourceRecordIdslist[i])
            sourceRecordIds = builder.EndVector()
        if self.propagatorPortId is not None:
            propagatorPortId = builder.CreateString(self.propagatorPortId)
        if self.propagatorCapability is not None:
            propagatorCapability = builder.CreateString(self.propagatorCapability)
        if self.traceId is not None:
            traceId = builder.CreateString(self.traceId)
        EstimationRequestStart(builder)
        if self.config is not None:
            config = self.config.Pack(builder)
            EstimationRequestAddConfig(builder, config)
        if self.observations is not None:
            EstimationRequestAddObservations(builder, observations)
        if self.errorModels is not None:
            EstimationRequestAddErrorModels(builder, errorModels)
        if self.sourceRecordIds is not None:
            EstimationRequestAddSourceRecordIds(builder, sourceRecordIds)
        if self.propagatorPortId is not None:
            EstimationRequestAddPropagatorPortId(builder, propagatorPortId)
        if self.propagatorCapability is not None:
            EstimationRequestAddPropagatorCapability(builder, propagatorCapability)
        if self.traceId is not None:
            EstimationRequestAddTraceId(builder, traceId)
        estimationRequest = EstimationRequestEnd(builder)
        return estimationRequest
