# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EstimationState(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 384

    # EstimationState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstimationState
    def Epoch(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # EstimationState
    def State(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + i * 8)) for i in range(self.StateLength())]
        elif j >= 0 and j < self.StateLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + j * 8))
        else:
            return None

    # EstimationState
    def StateAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 16, self.StateLength())

    # EstimationState
    def StateLength(self):
        return 6

    # EstimationState
    def StateIsNone(self):
        return False

    # EstimationState
    def Covariance(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64 + i * 8)) for i in range(self.CovarianceLength())]
        elif j >= 0 and j < self.CovarianceLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64 + j * 8))
        else:
            return None

    # EstimationState
    def CovarianceAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 64, self.CovarianceLength())

    # EstimationState
    def CovarianceLength(self):
        return 36

    # EstimationState
    def CovarianceIsNone(self):
        return False

    # EstimationState
    def ResidualRms(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(352))
    # EstimationState
    def RecoveredNoiseSigma(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(360))
    # EstimationState
    def IterationCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(368))
    # EstimationState
    def AcceptedCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(372))
    # EstimationState
    def RejectedCount(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(376))
    # EstimationState
    def ReferenceFrame(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(380))
    # EstimationState
    def Converged(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(381))
    # EstimationState
    def Smoothed(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(382))
    # EstimationState
    def Estimator(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(383))

def CreateEstimationState(builder, epoch_jdDay, epoch_seconds, state, covariance, residualRms, recoveredNoiseSigma, iterationCount, acceptedCount, rejectedCount, referenceFrame, converged, smoothed, estimator):
    builder.Prep(8, 384)
    builder.PrependUint8(estimator)
    builder.PrependUint8(smoothed)
    builder.PrependUint8(converged)
    builder.PrependUint8(referenceFrame)
    builder.PrependUint32(rejectedCount)
    builder.PrependUint32(acceptedCount)
    builder.PrependUint32(iterationCount)
    builder.PrependFloat64(recoveredNoiseSigma)
    builder.PrependFloat64(residualRms)
    for _idx0 in range(36 , 0, -1):
        builder.PrependFloat64(covariance[_idx0-1])
    for _idx0 in range(6 , 0, -1):
        builder.PrependFloat64(state[_idx0-1])
    builder.Prep(8, 16)
    builder.PrependFloat64(epoch_seconds)
    builder.PrependFloat64(epoch_jdDay)
    return builder.Offset()

import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch
try:
    from typing import List, Optional
except:
    pass

class EstimationStateT(object):

    # EstimationStateT
    def __init__(
        self,
        epoch = None,
        state = None,
        covariance = None,
        residualRms = 0.0,
        recoveredNoiseSigma = 0.0,
        iterationCount = 0,
        acceptedCount = 0,
        rejectedCount = 0,
        referenceFrame = 0,
        converged = 0,
        smoothed = 0,
        estimator = 0,
    ):
        self.epoch = epoch  # type: Optional[orbpro.estimation.EstimationEpoch.EstimationEpochT]
        self.state = state  # type: Optional[List[float]]
        self.covariance = covariance  # type: Optional[List[float]]
        self.residualRms = residualRms  # type: float
        self.recoveredNoiseSigma = recoveredNoiseSigma  # type: float
        self.iterationCount = iterationCount  # type: int
        self.acceptedCount = acceptedCount  # type: int
        self.rejectedCount = rejectedCount  # type: int
        self.referenceFrame = referenceFrame  # type: int
        self.converged = converged  # type: int
        self.smoothed = smoothed  # type: int
        self.estimator = estimator  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        estimationState = EstimationState()
        estimationState.Init(buf, pos)
        return cls.InitFromObj(estimationState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, estimationState):
        x = EstimationStateT()
        x._UnPack(estimationState)
        return x

    # EstimationStateT
    def _UnPack(self, estimationState):
        if estimationState is None:
            return
        if estimationState.Epoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()) is not None:
            self.epoch = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpochT.InitFromObj(estimationState.Epoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()))
        if not estimationState.StateIsNone():
            if np is None:
                self.state = []
                for i in range(estimationState.StateLength()):
                    self.state.append(estimationState.State(i))
            else:
                self.state = estimationState.StateAsNumpy()
        if not estimationState.CovarianceIsNone():
            if np is None:
                self.covariance = []
                for i in range(estimationState.CovarianceLength()):
                    self.covariance.append(estimationState.Covariance(i))
            else:
                self.covariance = estimationState.CovarianceAsNumpy()
        self.residualRms = estimationState.ResidualRms()
        self.recoveredNoiseSigma = estimationState.RecoveredNoiseSigma()
        self.iterationCount = estimationState.IterationCount()
        self.acceptedCount = estimationState.AcceptedCount()
        self.rejectedCount = estimationState.RejectedCount()
        self.referenceFrame = estimationState.ReferenceFrame()
        self.converged = estimationState.Converged()
        self.smoothed = estimationState.Smoothed()
        self.estimator = estimationState.Estimator()

    # EstimationStateT
    def Pack(self, builder):
        return CreateEstimationState(builder, self.epoch.jdDay, self.epoch.seconds, self.state, self.covariance, self.residualRms, self.recoveredNoiseSigma, self.iterationCount, self.acceptedCount, self.rejectedCount, self.referenceFrame, self.converged, self.smoothed, self.estimator)
