# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

class EstimatorKind(object):
    BATCH_WEIGHTED_LEAST_SQUARES = 0
    EXTENDED_KALMAN_FILTER = 1
    UNSCENTED_KALMAN_FILTER = 2
    EXTENDED_KALMAN_FILTER_WITH_RTS = 3
