# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

class EstimationStatus(object):
    INTERNAL = -20
    PROPAGATOR_PROTOCOL = -19
    BUFFER_TOO_SMALL = -18
    NOT_CONVERGED = -5
    BAD_INPUT = -4
    NULL_OUTPUT = -3
    NOT_CONFIGURED = -1
    OK = 0
