# automatically generated by the FlatBuffers compiler, do not modify

# namespace: estimation

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InitialOrbitResult(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 80

    # InitialOrbitResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InitialOrbitResult
    def Epoch(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # InitialOrbitResult
    def State(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + i * 8)) for i in range(self.StateLength())]
        elif j >= 0 and j < self.StateLength():
            return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16 + j * 8))
        else:
            return None

    # InitialOrbitResult
    def StateAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float64Flags, self._tab.Pos + 16, self.StateLength())

    # InitialOrbitResult
    def StateLength(self):
        return 6

    # InitialOrbitResult
    def StateIsNone(self):
        return False

    # InitialOrbitResult
    def Iterations(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(64))
    # InitialOrbitResult
    def ReferenceFrame(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(68))
    # InitialOrbitResult
    def Status(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(72))

def CreateInitialOrbitResult(builder, epoch_jdDay, epoch_seconds, state, iterations, referenceFrame, status):
    builder.Prep(8, 80)
    builder.Pad(4)
    builder.PrependInt32(status)
    builder.Pad(3)
    builder.PrependUint8(referenceFrame)
    builder.PrependUint32(iterations)
    for _idx0 in range(6 , 0, -1):
        builder.PrependFloat64(state[_idx0-1])
    builder.Prep(8, 16)
    builder.PrependFloat64(epoch_seconds)
    builder.PrependFloat64(epoch_jdDay)
    return builder.Offset()

import spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch
try:
    from typing import List, Optional
except:
    pass

class InitialOrbitResultT(object):

    # InitialOrbitResultT
    def __init__(
        self,
        epoch = None,
        state = None,
        iterations = 0,
        referenceFrame = 0,
        status = 0,
    ):
        self.epoch = epoch  # type: Optional[orbpro.estimation.EstimationEpoch.EstimationEpochT]
        self.state = state  # type: Optional[List[float]]
        self.iterations = iterations  # type: int
        self.referenceFrame = referenceFrame  # type: int
        self.status = status  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        initialOrbitResult = InitialOrbitResult()
        initialOrbitResult.Init(buf, pos)
        return cls.InitFromObj(initialOrbitResult)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, initialOrbitResult):
        x = InitialOrbitResultT()
        x._UnPack(initialOrbitResult)
        return x

    # InitialOrbitResultT
    def _UnPack(self, initialOrbitResult):
        if initialOrbitResult is None:
            return
        if initialOrbitResult.Epoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()) is not None:
            self.epoch = spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpochT.InitFromObj(initialOrbitResult.Epoch(spacedatanetwork_astro.invoke.orbpro.estimation.EstimationEpoch.EstimationEpoch()))
        if not initialOrbitResult.StateIsNone():
            if np is None:
                self.state = []
                for i in range(initialOrbitResult.StateLength()):
                    self.state.append(initialOrbitResult.State(i))
            else:
                self.state = initialOrbitResult.StateAsNumpy()
        self.iterations = initialOrbitResult.Iterations()
        self.referenceFrame = initialOrbitResult.ReferenceFrame()
        self.status = initialOrbitResult.Status()

    # InitialOrbitResultT
    def Pack(self, builder):
        return CreateInitialOrbitResult(builder, self.epoch.jdDay, self.epoch.seconds, self.state, self.iterations, self.referenceFrame, self.status)
